### ISSUE TITLE
Deleting a user should not delete their playlists and smartblocks

### ISSUE THREAD

**Issue by kmahelona** [LibreTime/libretime#1005]
**Describe the bug**
Unless this is made explicitly clear when deleting a user and doubled warned about it just seems like a terrible idea. I've done this many times before and oops I did it again (and my daily db backups weren't working!). I can see an issue here... `creator=null` but postgresql does allow null fields so I can't see why we would delete playlists and smart blocks that are in use when we delete a user. I've flagged this as a bug because I feel it's pretty important enough rather than being a feature request.

**To Reproduce**
1. Go to Settings > Users
2. Click the x next to the user
3. Accept the prompt
4. The user is deleted as well as the content they created.

**Expected behavior**
**Delete all content of user when user is deleted:** In this case, we should show a warning that all playlists, smart blocks, and tracks will be deleted if the user is deleted.
**Preserve all content when user is deleted:** This seems like a more *expected* way to handle this situation. Otherwise we should give the option to keep or delete the the content created by the user being deleted.

**LibreTime version:**
Latest master

**Installation method:**
 - OS: Debian
 - OS Version 10
 - Method: ./install

**Screenshots**
I'd go create some but I'm too afraid too 😅

**Comment by Robbt** [comment]
I agree. 
It looks the the User controller code has an option to donateFiles but it evidently isn't being used.
https://github.com/LibreTime/libretime/blob/960b4fae21ae39a9ac6e47f79ced473a2d6bc471/airtime_mvc/application/controllers/UserController.php#L197-L245

It doesn't look like either option is flagged when the page is called here
https://github.com/LibreTime/libretime/blob/960b4fae21ae39a9ac6e47f79ced473a2d6bc471/airtime_mvc/public/js/airtime/user/user.js#L46-L56

So this would be the place to intervene, one possibility would be to prompt the admin who is deleting the user whether they want to delete all files or donate them. I suspect that smartblocks and playlists are considered part of the files owned by a user which is why they are being deleted.

So I've identified the places in the code that would need to be changed now we just need to decide upon an ideal solution.
