### ISSUE TITLE
Soundcloud Publish untested and not working

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#1043]
We have a button that claims to publish to Soundcloud but we have not tested this integration and I don't know what level of functionality exists here. It has been reported that it does not work by a user on the forum - https://discourse.libretime.org/t/my-podcasts-wont-pubish/559

I suggest that we validate the feature and if it isn't working we remove it before we publish a beta with a broken functionality.

**Comment by gusaus** [comment]
Assuming this was a feature implemented in AirTime? Is there a similar half-baked feature for Mixcloud? https://github.com/LibreTime/libretime/issues/769

**Comment by paddatrapper** [comment]
> Assuming this was a feature implemented in AirTime? 

Yup

> Is there a similar half-baked feature for Mixcloud?

Not that I know of. It is implemented in the Python code, so may be extendable there

**Comment by gusaus** [comment]
If the SoundCloud feature doesn't work, possibly it could be consolidated with the Mixcloud integration request? https://github.com/LibreTime/libretime/issues/769

**Comment by Robbt** [comment]
Other than the similar sounding name SoundCloud and Mixcloud likely have different APIs etc. So it probably makes sense to just remove Soundcloud Publish if it doesn't work.

**Comment by gusaus** [comment]
> So it probably makes sense to just remove Soundcloud Publish if it doesn't work.

Agreed - obviously we're talking about different platforms - would make sense to properly integrate after 3.0 is out the door.

**Comment by zklosko** [comment]
In addition, publishing to "My Podcast" doesn't work either. :(

**Comment by zklosko** [comment]
My vote is to remove the entire "My Podcast" and publishing sections. If a station has a podcast, they'd get more traction and it would be easier with Anchor.fm or the Bluberry Wordpress plugin, to name two. Also, this feature doesn't really benefit stations like WRIR who are using Libretime behind a firewall as an internal service, not exposing the server to the outside internet.

If you're recording a show using Libretime it would make sense to want to share the file and/or download it to local storage. Libretime can't record files, so the feature seems moot to me because DJs can either livestream or upload prerecorded files. DJs would probably get a better experience recording their show locally as they broadcast.

**Comment by paddatrapper** [comment]
The advantage of having it in LibreTime is that it gives the production team a single place to pull things for podcasts from even when using external podcasting systems. Getting things from presenters can be tricky. But I agree that removing it is better than leaving it in and have it not work

**Comment by zklosko** [comment]
In that case, we should incorporate a download button that would allow users to download uploaded tracks from within the interface.
