### ISSUE TITLE
Question/Security: Isolate the Libretime from port 80 to another

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#105]
How to isolate/hide the Libretime CMS to another port (8090 example), and leave the main radio page on port 80?
or maybe there is a way to hide or rename /login page?

**Comment by hairmare** [comment]
Most stations I known have a separate CMS from their radio automation, drupal and wordpress seem to be popular. I'm not sure if the radio page is worth the effort since it's such a simple page. There have been talks about creating native plugins for platforms like drupal or wordpress.

You can already hide the login link on the page, but that is not what you  are looking for.

Maybe you can put everything behind a proxy and only open parts of it selectively. I'm not sure if that's practical though. You might also be able to protect the login page with some apache config. ie. only allowing access to `/login` from your ip similar to the following untested example:

```apache
<Location /login>
    Require ip <your-client-ip>
</Location>
```

It really depends on your exact use-case. In my deploy LibreTime will most likely be running in a totally different network segment than the internet and only the bare minimum parts of the api needed at our station will be exposed to the internet through a revproxy in the DMZ. DJs will access the instance through VPN.

**Comment by korotkov13** [comment]
Thanks for interesting thoughts.
I like the standard radio page. it is simple and without any unnecessary information. 
Other CMS can't load information about new podcasts, and the standard page like its minimalism.

**Comment by hairmare** [comment]
Podcasts should be fairly easy to integrate with any modern CMS via their RSS feed at `/feeds/station-rss`, we do need more such integration points though. 

I personally like the minimalism of the radio page as well, it's just I'm sure like 90% of our users will have a "real" website in addition to it. For that reason I prefer not to invest too much time into it.

**Comment by korotkov13** [comment]
for noobs like me i found this solution.
I added this
`  <Location /login>
  SetHandler server-status 
      Order deny,allow
      deny from all
      allow from xxx.xxx.xxx.xxx
      allow from xxx.xxx.xxx.xxx
      allow from xxx.xxx.xxx.xxx
      allow from xxx.xxx.xxx.xxx
</Location>`
at the end of airtime.conf (/etc/apache2) Ubuntu 14.04
I didn't find easy solution with MAC addresses

**Comment by hairmare** [comment]
I'm gonna close this when I release 3.0.0-alpha.1. Let me know know if you feel that there is still something open.

**Comment by korotkov13** [comment]
@hairmare  ok
