### ISSUE TITLE
Celery v5 not starting

### ISSUE THREAD

**Issue by matias-tecnosoul** [libretime/libretime#1084]
I've pulled the git today and installed it on a fresh Ubuntu 18.04 Lxc container (as I'm already doing with other LT installs).
However when I arrive to the configuration checklist after starting the services I get a "Looks like something went wrong!" saying that Celery is not running.
When I do a `systemctl restart libretime-celery` it seems to start but then I get an error message in the status:
```
# systemctl status libretime-celery
● libretime-celery.service - LibreTime Celery Service
   Loaded: loaded (/etc/systemd/system/libretime-celery.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-08-21 11:46:26 -03; 2min 6s ago
  Process: 5692 ExecStart=/usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=1800 --concurrency=1 --config=celeryconfig -l INFO (code=ex
 Main PID: 5692 (code=exited, status=2)

Aug 21 11:46:26 elektrona-space systemd[1]: libretime-celery.service: Service hold-off time over, scheduling restart.
Aug 21 11:46:26 elektrona-space systemd[1]: libretime-celery.service: Scheduled restart job, restart counter is at 5.
Aug 21 11:46:26 elektrona-space systemd[1]: Stopped LibreTime Celery Service.
Aug 21 11:46:26 elektrona-space systemd[1]: libretime-celery.service: Start request repeated too quickly.
Aug 21 11:46:26 elektrona-space systemd[1]: libretime-celery.service: Failed with result 'exit-code'.
Aug 21 11:46:26 elektrona-space systemd[1]: Failed to start LibreTime Celery Service.

```
Also I see in syslog:
```
Aug 21 11:50:31 elektrona-space celery[5794]: Error: no such option: -A
Aug 21 11:50:31 elektrona-space systemd[1]: libretime-celery.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 21 11:50:31 elektrona-space systemd[1]: libretime-celery.service: Failed with result 'exit-code'.

```
So I try the command in /etc/systemd/system/libretime-celery.service
`ExecStart=/usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=1800 --concurrency=1 --config=celeryconfig -l INFO`

and indeed I get a "no such option: -A" error:
```
#/usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=1800 --concurrency=1 --config=celeryconfig -l INFO
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.
Error: no such option: -A
```
I checked Celery version:
```
# celery --version
5.0.0b1 (cliffs)

```
In other LT installs I checked and have an older Celery version.
```
celery --version
4.4.6 (cliffs)
```
So, could it be a Celery v5 issue??
Any hints?
thanks...

**LibreTime version:**
5ac18aa4e

**Installation method:**
 - OS: Ubuntu in a LXC container
 - OS Version: 18.04.5 LTS 
 - Method: ./instal script

**Comment by paddatrapper** [comment]
`airtime-celery` is a celery script. We install the celery engine from pip: https://github.com/LibreTime/libretime/blob/master/python_apps/airtime-celery/setup.py#L51

**Comment by eskapiste** [comment]
same thing here, i cant make it work

`● libretime-celery.service - LibreTime Celery Service
   Loaded: loaded (/etc/systemd/system/libretime-celery.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-08-23 19:16:58 EET; 5min ago
  Process: 3275 ExecStart=/usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=1800 --concurrency=1 --config=celeryconfig -l INFO (code=exited, status=2)
 Main PID: 3275 (code=exited, status=2)
`

other services are ok.
is there any way to solve it?
or downgrade to previous version of celery?

**Comment by matias-tecnosoul** [comment]
if we roll back the LT git version, are we going to downgrade Celery as well? or it will still be obtained from the same place (and therefore get the same version not working now)?

**Comment by paddatrapper** [comment]
No. You need to specify the version of celery in the setup.py file I linked before. Then re-run `python3 ./setup.py install --no-init-script` from within the `airtime-celery` directory

**Comment by eskapiste** [comment]
i might be noob, but i cant understand how to. i changed 0.1 to 4.4.6, and then started setuo.py
still have 5.0.0

**Comment by gr0ebi** [comment]
set Version back to "0.1" and change Line 51 to 
`install_requires=["soundcloud", "celery==4.4.7", "kombu==4.6.10", "configobj"],`

**Comment by eskapiste** [comment]
it seems like it is running now, but now i got this problem with AUTH. same things happen when i try to upload files via GUI control panel.

> 
● libretime-celery.service - LibreTime Celery Service
   Loaded: loaded (/etc/systemd/system/libretime-celery.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-08-23 22:57:23 EET; 2s ago
 Main PID: 3273 (celery)
    Tasks: 1 (limit: 2338)
   CGroup: /system.slice/libretime-celery.service
           └─3273 /usr/bin/python3 /usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=1800 --concurrency=1 --config=celeryconfig -l INFO

Aug 23 22:57:24 tapatown celery[3273]:     return self.on_inbound_frame(frame)
Aug 23 22:57:24 tapatown celery[3273]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.6.1-py3.6.egg/amqp/method_framing.py", line 55, in on_frame
Aug 23 22:57:24 tapatown celery[3273]:     callback(channel, method_sig, buf, None)
Aug 23 22:57:24 tapatown celery[3273]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.6.1-py3.6.egg/amqp/connection.py", line 521, in on_inbound_method
Aug 23 22:57:24 tapatown celery[3273]:     method_sig, payload, content,
Aug 23 22:57:24 tapatown celery[3273]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.6.1-py3.6.egg/amqp/abstract_channel.py", line 145, in dispatch_method
Aug 23 22:57:24 tapatown celery[3273]:     listener(*args)
Aug 23 22:57:24 tapatown celery[3273]:   File "/usr/local/lib/python3.6/dist-packages/amqp-2.6.1-py3.6.egg/amqp/connection.py", line 651, in _on_close
Aug 23 22:57:24 tapatown celery[3273]:     (class_id, method_id), ConnectionError)
Aug 23 22:57:24 tapatown celery[3273]: amqp.exceptions.AccessRefused: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.

>

**Comment by gr0ebi** [comment]
Did you use the correct python3 install command that @paddatrapper wrote?
> No. You need to specify the version of celery in the setup.py file I linked before. Then re-run `python3 ./setup.py install --no-init-script` from within the `airtime-celery` directory

**Comment by eskapiste** [comment]
> Did you use the correct python3 install command that @paddatrapper wrote?
> 
> > No. You need to specify the version of celery in the setup.py file I linked before. Then re-run `python3 ./setup.py install --no-init-script` from within the `airtime-celery` directory

yes. it seems that everything ok with celery. i guess there is problem with something else, not celery.

> Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.

**Comment by klaus13** [comment]
Hi, I got the same issue. System is Xubuntu 18.04.5 Celery service don't want to start up and I see that **Replay Gain** don't work too. After setup Libretime-Master, I had also no access to the localhost Apach2 server. Faust helped me and I got access with this command line: sudo chown -R www-data:www-data /usr/share/airtime/php/airtime_mvc/
That's maybe not the best solution but it works. To be sure that my problem is true I made 2 new installations today ! The same issue in each one. Thank you for research to fix this issues.

**Comment by LordFader** [comment]
Ubuntu 18.04.5 LTS fresh install.
Got this issue to.
Is there a user friendly way to solve this after the installation?
Or is something we need to do during the installation process?

Sorry I'm just a simple user of Libretime I'm not a developer soo.. I got some limitations! 
If there is a way to solve this... It will be nice. 

- Download a new install? 
- Change a file after install? 
- Add any kind of "code" in a specific file location? 
- Instructions over CLI after install?

Thank you.

**Comment by kaldown** [comment]
How to debug celery to understand at least WHY it is restarting with `systemd`?

**Comment by jooola** [comment]
@triangle-stream Please open a dedicated issue for your problem.

**Comment by jooola** [comment]
Celery upgrade to >=5.0.0 is handled in #1800
