### ISSUE TITLE
CentOS support is out of date

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#1113]
We currently support CentOS 7.3. The current CentOS 7 release is 7.9 and CentOS 8 has been released. I think we need to re-evaluate our CentOS support. It is not first class in the installer (users have to manually install the packages required before starting the install) and there has been no work on getting CentOS 8 support. CentOS is currently the only reason we still support PHP 5 and I think it would be a good idea to drop that requirement if we drop CentOS support

**Comment by zklosko** [comment]
Is there a way we can take a poll of our userbase?

**Comment by paddatrapper** [comment]
Furthermore, CentOS 7 doesn't ship Python 3 at all. Users need to install it externally

**Comment by paddatrapper** [comment]
> Is there a way we can take a poll of our userbase?

Not really. We can open issues here and discuss on discourse and mattermost, but that is about it

**Comment by Robbt** [comment]
Centos was never officially supported as far as I remember. It was kind of a pet project of @hairmare because he preferred centos but we always understood their might be issues. If centos has an old version of phpunit maybe we can use it to run tests. Otherwise the python 3 issue would make us supporting it with our installed kind of a challenge. If anyone is going to install LibreTime on Centos they probably need to know more than just how to run a shell script.

**Comment by hairmare** [comment]
My production runs on [these RPMs](https://build.opensuse.org/package/show/home:radiorabe:airtime/libretime) that have [a python2 patch](https://build.opensuse.org/package/view_file/home:radiorabe:airtime/libretime/_service:download_files:liquidsoap-1.3-for-3.0.0-alpha.7.patch?expand=1) that I never ended up contributing.

I've been working on getting ready to upgrade to CentOS 8 & have been sorting dependencies like silan and liquidsdoap. I expect to be able to put some real work into CentOS 8 support later this year after finally getting most deps sorted. 3.0.0-alpha.9 will most likely either support only CentOS 8 or it might forego official CentOS support completely with me putting some reverse-patches from the python3 rewrite into my RPMs... I'm not sure yet.

I've also been holding off upstreaming my packaging work to somewhere like EPEL or RPMforge because I wanted to wait for CentOS 8.

One thing to note about CentOS 8 is that we won't be stuck with outdated python or php versions since CentOS 8 makes it easier to upgrade non os-core packages compared to CentOS 7.

**Comment by hairmare** [comment]
The main issue I'm facing on this is that i haven't found an icecast package for CentOS 8 yet. I might end up backporting a Fedora version until icecast gets back into EPEL proper.

**Comment by hairmare** [comment]
I found some icecast packages that work and am preparing a PR that will update the installer to CentOS 8 & fix it.

For CentOS 8 to be viable we will need to add support for liquidsoap 1.4 as per #1136 though.

**Comment by zklosko** [comment]
@hairmare about CentOS 8... I'm sure you heard the news about the change in support. Are you planning to keep supporting CentOS or ditch for a fork or derivative of RHEL?

**Comment by hairmare** [comment]
The announcement does't change anything for the time being. The packages i've been building (esp. liquidsoap) work fine on any EL distro (incl. CentOS, RHEL, ...). I've even started building CentOS 8 Stream packages for all deps recently.
