### ISSUE TITLE
liquidsoap 1.4 support

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#1136]
**Describe the bug**
Our ls_script.liq and ls_lib.liq do not currently support liquidsoap 1.4.

**To Reproduce**
1. Install liquidsoap 1.4.3
2. Start `libretime-liquidsoap`
3. See error
```
At /usr/local/lib/python3.6/site-packages/airtime_playout-1.0-py3.6.egg/liquidsoap/ls_lib.liq, line 55, char 8-13:
Error 5: this value has type
  (source(_), ...) -> _ (inferred at /usr/local/lib/python3.6/site-packages/airtime_playout-1.0-py3.6.egg/liquidsoap/ls_lib.liq, line 54, char 10-49)
but it should be a subtype of
  (float, ...) -> _
```

**Expected behavior**
`libretime-liquidsoap` script starts and `libretime-pypo` connects to it.

**LibreTime version:**
2a62c99eac36fbaa1649a26fb3c6808218172a90

**Installation method:**
 - OS: CentOS 8 (with hacked installer that I am preparing to PR)
 - Method: `vagrant up centos`
 - Details: local checkout of above version

**Additional context**
I'm not surprised that our current script doesn't work but was not able to figure out what we need to change to fix it. If we want to support the full range of liquidsoap (1.1.1, 1.3.x & 1.4.x) we'll have to keep a third version of the .liq files available (in addition to the current default & the 1.1.1 legacy versions).

**Comment by hairmare** [comment]
The mentioned error points to these lines of liq code:

https://github.com/LibreTime/libretime/blob/9c137180697e98ba32265f2604693c48a0ff5f91/python_apps/pypo/liquidsoap/ls_lib.liq#L54-L55

**Comment by paddatrapper** [comment]
I do find it annoying that liquidsoap doesn't follow semantic versioning and just breaks things on point releases...

**Comment by toots** [comment]
We actually have been following semantic versioning since `1.3.x` but in the way that most of fast-moving projects seem to be doing it nowadays, i.e. using the caret versioning as documented for node modules here: https://github.com/npm/node-semver#caret-ranges-123-025-004

> Allows changes that do not modify the left-most non-zero element in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.
> 
> Many authors treat a 0.x version as if the x were the major "breaking-change" indicator.
> 
> Caret ranges are ideal when an author may make breaking changes between 0.2.4 and 0.3.0 releases, which is a common practice. However, it presumes that there will not be breaking changes between 0.2.4 and 0.2.5. It allows for changes that are presumed to be additive (but non-breaking), according to commonly observed practices.

More generally, I highly recommend to consult _any_ changelog before updating to a new version. Bugfixes sometimes change existing implementation-defined behavior and _can_ break a script, in particular if the script was relying in a bogus behavior.

Last, we also do sometimes add breaking changes in bugfix release when we consider that it is important enough. One example happened in `1.4.2` and was properly documented in the changelog: https://github.com/savonet/liquidsoap/releases/tag/v1.4.2

In general, our philosophy is to provide stable functionalities over the course of a release cycle (e.g. `1.4.x`) but we do not suggest to blindly update to any version without properly testing an existing script.

**Comment by paddatrapper** [comment]
So essentially any and every release could bring breaking changes... We use distro packaged versions of Liquidsoap, so we do have a set of versions we have to support without control over what they are. We don't blindly update versions - hence this issue, but this is something that rears its head every time we have a new version of a distro to support.

Are there better ways of handling incompatible changes than having a script for each version? Duplicating the script makes maintenance very difficult, as it leads to much code duplication.

**Comment by toots** [comment]
Starting with `1.4.x` (I believe), we have started adding deprecated wrappers to maintain backward compatibility as much as possible. See: https://github.com/savonet/liquidsoap/blob/1.4.3/libs/deprecations.liq

The advice above is conservative. We try to make it as easy as possible to upgrade versions. However, because of the nature of the script language and its purpose, it's inherently difficult to keep total compatibility. Where a shared library or a traditional programming language mostly have to worry about maintaining compatible API signatures, some of the dynamic elements of liquidsoap, e.g. how we handle metadata can be pretty complex and, sometimes, fixing a bug means changing things that can potentially break other scripts, for instance specific behavior around metadata or track callbacks.

We have switched to `opam` as our favorite way of installing liquidsoap. Mostly because we cannot afford to maintain and work with multiple distribution at the same time. However, `opam` also provides a nice element of abstraction in that it can provide up-to date versions of both the OCaml compiler and all the packages that we depend upon.

Adding to that that most underlying dependencies, `libmp3lame` and etc are pretty stable now, using `opam` makes it possible to install pretty much any version on liquidsoap of your choosing on any fairly recent OS. I would certainly suggest exploring that or, perhaps, using a docker image, which we also provide for each release now.

Lastly, for some distributions, we do provide custom-built debian packages but I would recommend that as a last option.

**Comment by paddatrapper** [comment]
My issue with opam is mainly security updates for users. Our target user is not very technical, hence the goal to make install and management require as little of the shell as possible. It is reasonable to expect them to keep distro-provided packages up to date - Ubuntu and Debian even ship automatic updates out of the box, but adding additional methods of package install is problematic and probably will lead to outdated packages with security vulnerabilities. Even the pip dependencies we currently use for the python modules are questionable and I would much rather they be provided by distro packages (part of the Debian LT packaging I have been working on intermittently over the last few years. Using only distro packages as far as possible ensures consistent upgrades of packages in lockstep with security patches coming as distros provide them.

**Comment by hairmare** [comment]
First of all, thank you very much @toots. Your feedback is always very much appreciated.

With the RPM packages I have been building for CentOS (and lately also for Fedora) I tend to recommend users switch to opam if they need stuff which I cannot easily build into the packages. The packages really only exist because they make it very easy to manage their lifecycle on the admittedly over-engineered infrastructure @radiorabe.

The reason that these "we need to support liquidsoap 1.n+1" issues pop up at a regular interval is that we would like to support up-to-date versions so we don't run into issues like with 1.1.1 anymore. I guess we're a bit burnt-out by all of our dependencies being outdated due to that being a lot of work during our initial fork from our legacy upstream project.

In the case of switching to liquidsoap 1.4 the PR I just made is forcing us to modernize our scripts which are still more or less untouched since we forked. I think this is a good thing since it will also help us make use of more of your hard work (ie. my PR switches to use `crossfade(smart=true)` in one place where I feel it will make for better transitions for all of our users).

btw, I just registered for [liquidshop](http://www.liquidsoap.info/liquidshop/) and am looking forward to continuing this conversation there 🚀

**Comment by toots** [comment]
Hi guys! Thanks for this conversation. In return, I totally understand the complex nature of keeping track of our versions AND our dependencies and really, really appreciate the effort to make the software accessible to your users.

One thing I could recommend trying is to use the `opam` build process to harness the package build. The packages we build for Debian in our CI typically do that. First we install all deps using `opam` and, then, we recompile a liquidsoap with the proper `./configure` options.

Essentially this goes like this:
```
... setup opam (including issuing call to eval $(opam env))
# You can install external dependencies explicitly or do:
~ opam depext -y liquidsoap.<version> <liquidsoap deps>
# Then:
~ opam install -y liquidsoap.<version> <liquidsoap deps>
# Or, in one step:
~ opam depext -y -i liquidsoap.<version> <liquidsoap deps>
~ cd /path/to/liquidsoap/sources
~ ./configure <options>
~ make
~ make install
```
Then, at this point you can just collect the binary and package it like before.

Considering that we keep track of our installation scripts in `opam`, including external dependencies, this should be a pretty robust way of packaging. You can even tap on unreleased/pinned packages if needed.

The only trick with this way of doing it is that you also need to install the `camomile` files, which we do this way in our CI debian packages:
```
cp -rf `ocamlfind ocamlc -where`/../../share/camomile $(DESTDIR)/usr/share/liquidsoap
```

If that can help, the files for our CI are all here: https://github.com/savonet/liquidsoap/tree/master/.github

Hope this helps, looking forward to connecting virtually next month!
