### ISSUE TITLE
Migrate Python package installs to PEP 517

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1154]
We should eventually migrate our `setuptools` based Python app installers to [PEP 517](https://www.python.org/dev/peps/pep-0517/). This provides a declarative install process that allows us to do things like define test dependencies.

**Comment by jooola** [comment]
Even if our setup.py / Makefile / requirements-dev.txt seems to work Okish, I propose to consider [poetry](https://python-poetry.org/) as dependency manager and start to adopt the `pyproject.toml` file for managing deps and configurations.

If we go in that direction, we should wait for poetry v1.2 (currently in alpha [v1.2.0a2](https://github.com/python-poetry/poetry/releases)) as it contains a set of features we require so we don't totally deviate from our current development workflow (a feature similar to `pip install --editable .` will be available at this point).

**Comment by jooola** [comment]
I propose to move to poetry sooner than I proposed, as we do not necessarily have to rely on the `pip install --editable .` feature.

This feature seem to be controversial and isn't a high priority feature in poetry.
See https://github.com/python-poetry/poetry/issues/34
See https://github.com/python-poetry/poetry/discussions/1135

Poetry actually install your package in "dev" mode by default, but it won't allow system wide install (`pip install -e .` without being in a venv). It will always work within a virtual env, which forces you to execute common tasks trough poetry (through the venv, as usual actually, but it is somewhat hidden by poetry).

So I wonder if we rely on this system wide editable install feature ?

A way to get as close as possible from the previous workflow, is to use the following https://python-poetry.org/docs/configuration/#virtualenvsin-project setting to have the generated venv (during `poetry install`) within the project dir and then activate the venv as you would usually do with `source .venv/bin/activate`. I found this really useful as I always need my IDE to load the venv in order to run linting/formatting tool.

This answers some of my own question I had in the past, and therefor I will propose an attempt to solve this issue. But before that I would like to have your input @paddatrapper.

**Comment by paddatrapper** [comment]
The issue with poetry is that it is very new. There are only packages in Debian testing and unstable. It hasn't made it into a stable release of either Debian or Ubuntu yet. So using it as the packaging system precludes us from building deb packages for our Python apps unless we support both poetry and setup.py methods until we drop Bullseye, 20.04 and 18.04 support in about 3 years time (assuming 22.04 will have it in)

**Comment by jooola** [comment]
While the discussion on poetry remains, I am going to move our packages to PEP 517.

**Comment by jooola** [comment]
Let's open another issue if we think we should use poetry. For now pep 517 has been implemented with #1533
