### ISSUE TITLE
Playlist is not updating

### ISSUE THREAD

**Issue by ps-513** [LibreTime/libretime#1176]
Hi, I ran into such a problem that if you delete a track from the playlist, it will still remain in the previously created shows where this playlist participates, what should I do?
That is, it turns out that the playlist has not updated its track list and how to fix it

**Comment by paddatrapper** [comment]
Are you saying that future shows that have the playlist scheduled reflect the tracks from before the change to the playlist? How long is the change before the show is scheduled to start? LibreTime caches the list before the show starts (1hr I think). You can manually delete the tracks from the shows. But this seems like a bug

**Comment by ps-513** [comment]
> Вы хотите сказать, что будущие шоу с запланированным плейлистом будут отражать треки до изменения плейлиста? Как долго длится смена до запланированного начала шоу? LibreTime кэширует список до начала шоу (кажется, 1 час). Вы можете вручную удалить треки из шоу. Но это похоже на ошибку

Then how can you remove the caching time? Or lower it down to 1 minute?

**Comment by ps-513** [comment]
> Вы хотите сказать, что будущие шоу с запланированным плейлистом будут отражать треки до изменения плейлиста? Как долго длится смена до запланированного начала шоу? LibreTime кэширует список до начала шоу (кажется, 1 час). Вы можете вручную удалить треки из шоу. Но это похоже на ошибку

or make it so that as soon as the track is removed from the playlist, then the playlist immediately refreshes the cache in all scheduled schedules

**Comment by paddatrapper** [comment]
> Then how can you remove the caching time? Or lower it down to 1 minute?

You cannot currently

**Comment by Robbt** [comment]
I think I see two issues here. Playlists once they are scheduled no longer exist in any meaningful way in the database. This is because they are converted from converted from a set of tracks to the individual tracks.

So once the playlist is added to the show you would need to edit the show to remove the tracks.

The autoloading playlist adds the tracks contained in it one hour before a show airs. There is currently no UI to change this.

You can delete tracks from shows even while they are playing but sometimes it does cause unexpected behaviour. I think we need to get a better understanding of how the caching is implemented by the libretime-playout module to improve this and remove some of the bugs that crop up.

**Comment by klaus13** [comment]
I don't delete the tracks. I have to **clear** the played shows in the calendar, so the playlist with the newest audio files can get loaded one hour before playing time. If I don't clear the show content, the older content is still loaded and played. The clear function should be automatic, about one hour before that the new content can be loaded, I think.
