### ISSUE TITLE
Enable Semantic Commits

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1180]
This is for after 3.0 beta release.

Semantic commits ([conventialcommits](https://www.conventionalcommits.org/en/v1.0.0/)) allows automatic creation of changelogs and better indication of breaking changes. It can be used in conjunction with `semantic-release` to automatically release LT on a schedule with versioning based on semantic versioning

**Comment by jooola** [comment]
An alternative or complement to consider : https://github.com/atlassian/changesets

**Comment by jooola** [comment]
Also https://github.com/git-chglog/git-chglog

**Comment by jooola** [comment]
Another great tool https://github.com/twisted/towncrier

**Comment by jooola** [comment]
Another one, different style https://github.com/release-drafter/release-drafter

**Comment by jooola** [comment]
Another tool suggested by hairmaire https://github.com/go-semantic-release/semantic-release.

This has been discussed in the community meeting the 17/09/2021.

We need to decide whether conventional commits is a too high barrier for newcomers. They might face a wall if they are not used to it, so we need to consider with regards to contributors.

Also this can be mitigated if we squash (rebase if possible) our PR and let the maintainers edit the PR title to match the conventional commit format.

But we should set this up, no need to wait for v3.

**Comment by jooola** [comment]
I am actually happy with the conventional commit message for this repository, we should now enforce it using CI and some dev tools. And I think we all agree on this.

The tooling around conventional commit messages to generate changelogs or releases can be done after some extra research and testing.

**Comment by jooola** [comment]
Maybe https://github.com/commitizen-tools/commitizen can enforce a commit message format

**Comment by paddatrapper** [comment]
We're using squash and merge, which takes the PR name as the commit message if there is more than 1 commit. So this should probably be enforced at the PR naming level

**Comment by jooola** [comment]
I am looking for a way to generate a change log from the conventional commit message history.

Here are some concerns I have.

## Spell / prose errors

Commit messages are possibly filled with spelling errors, as we don't have any spell checker on the commit messages. This make the change log full of spelling errors, and regenerating the change log will always introduce the same spelling errors.

We could ignore the change log file for spelling errors, but I feel we should fix the source of the errors rather than allowing them to land in the repo.

## Breaking change notice format

We can extract the breaking changes messages to build some upgrade procedure, but depending on how well the procedure is written, we might need to add some extra context and better formatting. I've been writing such breaking change notice and I think I can start document and design a format for user to follow while writing these changes.

For the time being I would rather copy paste and improve those breaking changes notices in the releases notes, and maybe once we have a proper format/guidelines for these messages, and a way to enforce it, we could depend on the change log generator to bring those upgrade procedure to the users.

## Only generate a changelog after v3 ?

The tools used to generate a changelog require the commit history to be perfect, while our commit history is slowly improving, we aren't quiet there yet. The changelog isn't as clean as expected.

I propose we use the changelog generator to build releases notes until we have reached a point were our commit history has reached this required perfection and then generate the changelog.

**Comment by paddatrapper** [comment]
I think using the changelog generator for the moment works well. It should give us the flexibility we require while the commit history improves.

**Comment by jooola** [comment]
The BREAKING CHANGES footnotes in the commit message is a good idea to describe what the commit is breaking, but I made a mistake thinking we could use to generate upgrade procedures.

Since commit message are immutable, we cannot improve/fix/merge some upgrade steps. So I think we should keep using the BREAKING CHANGE footnotes to describe as much as possible the changes, but we should rely on the release note draft to properly write the upgrade procedure (Maybe this would have worked if we maintained a library, seem more difficult with a entire webapp).

The procedure described above is how I've been working for the past months, and haven't had any troubles with it. We should probably make it "official".

Regarding changelogs generation, we should not add those BREAKING CHANGES footnotes as I don't think we bring a lot of details to the users, users should rather use the upgrade release notes.

We should only prepend new logs to the existing CHANGELOG.md file. This allow us to fix spelling errors and keep the fixes by not regenerating the an entire changelog file. Some ideas in #1956.

I wonder if we can streamline all this conventional commit workflow, by using a single tool, such as https://github.com/commitizen-tools/commitizen.

I would like to close this and make it "official".

**Comment by jooola** [comment]
In addition, we don't want to follow semantic releases, but conventional commits. I've been mixing both some while ago, but our focus is on commit history, changelogs, and documentation instead of automatic version bump and automatic release.

**Comment by paddatrapper** [comment]
Yeah, sounds good. Need to have a look at commitizen, I haven't used it before
