### ISSUE TITLE
feature-request: Option to repeat auto playlist until a shows schedule is full

### ISSUE THREAD

**Issue by squiggleuk** [LibreTime/libretime#119]
When you have a show that uses the auto playlist, my understanding is that the auto playlist will append itself to any already scheduled content in that show.

This works well if you have a smartblock that will add lots of music etc, but in some situations it's a bit restrictive.

For example: I want to completely fill a show with the following repeating pattern of content:

Ident -> Advert - > Ident - > Long-mix

I can do this by using a playlist containing smartblocks (which randomly select one of each item), but it only runs through once, and can leave us with incomplete schedules. If we had another checkbox in the show config underneath 'enable autoplaylist', to enable the looping/repeating of the auto playlist until the shows schedule was full, it would be easy to build these kind of pattern based lineups, regardless of show length etc, etc...

**Comment by Robbt** [comment]
Ok, so this is a good idea. The question is what to do with the end of the track where they meet the end of the show, if we don't specifically program the smartblock to fit we will either have dead air or tracks being cut off in the middle.

**Comment by squiggleuk** [comment]
A good point - I guess a cut off track is always better than dead air... getting it to fit would be quite tricky to do, and would potentially end up turning random track/mix selections into a more repeated selection.

I run things by playing long dj mixes, if we had to pick two 'random' ones that totalled exactly 3 hrs, we'd always end up selecting the same ones to make them fit, rather than a true random selection...

With 'normal' length tracks, the above would be far less of a problem...

Maybe add another option to enable/disable trying to match content to show length, as it won't work well for all situations?

**Comment by Robbt** [comment]
Yeah, it is definitely a problem that could use some more thought. We already modified the smart blocks so that they would select tracks up to but not overflowing their time limit, which will mean that they will be more likely to have dead air if used without some kind of filler after them. 

In regards to the algorithm selecting the same tracks over and over again to fit the width this isn't likely with our current set-up because it doesn't add tracks based upon whether they fit, it just won't add a track that will go over the time limit (if you for instance had a number of tracks that met the criteria and were over 3 hours long but you had a time limit of 3 hours it would never add them via the smartblock. On the other hand if you are using the number of items criteria it doesn't impose any length limits.

I also had the idea that it might be useful to have a auto-playlist that prepends the playlist before the scheduled tracks for instances like always adding a station ID etc. I'm not sure if it makes sense to complicate the UI to have two autoplaylists. 

I also had the idea of making a special smart block that would expand its time to meet but not exceed whatever time is left in a show but this would be more complicated to set-up than simply setting a playlist to repeat until it fills the show. 

From my original thinking behind AutoPlaylists there are a number of options that could be created.

1. prepend playlist -> this is a playlist that will go before whatever is scheduled on the show.
2. replace playlist -> this is a automatic playlist that will wipe out anything scheduled in a show with the contents of the autoplaylist (the use case for this seem pretty iffy, why would people be scheduling content only to have it deleted by LibreTime). 
3. append playlist -> this is the playlist that we have currently that simply adds the content of the playlist, dynamic smartblocks after whatever if anything is already scheduled.

At this point we only have the append playlist. I'm not sure if it is a high priority to add a prepend playlist. If we should simply make it an option to have the autoplaylist prepend or append or to have two separate auto playlists. 

An option to have the playlists repeat until the show is full is a good idea. It might make sense to have this option with a prepend playlist for people who like to buffer their content with adverts, idents, top of the hour news etc on the front end of shows and people who want filler on the end. If we decided to create two separate auto playlists then the repeat until full option could be checked for one or both. If it was selected for both it would be necessary to add a track from one and then add a track from the other one otherwise the prepend playlist autofill would usually override the append playlist autofill. 

I think making an option for the autofill to add tracks that exceed the show length and one that doesn't is also a good idea. I'll have to look into how to best program this. Any feedback on functionality is welcome. I also don't want to make the UI overly complex.

Another quirk of the way I built autoplaylists is that they won't schedule if you don't have tracks being played within an hour of the time they are supposed to be broadcast. This is because the API calls by pypo-playout are what triggers the autoplaylist schedule. If you have dead air and are expecting the autoplaylist to come in and change that it won't with the current set-up. (I think I will pre-emptively add this as a bug/problem)

The only other thoughts I have on the autoplaylist is it might good to have something like a default automatic playlist option that will fill any empty shows on a global level. This would be similar to the AutoDJ functionality provided by Airtime.pro via their AutoDJ option. Basically it would be a playlist that goes in and repeats to fill any shows that have time left at the end of them but it could be configured via the Settings page vs. an individual page. Any autofill options in the show itself should take precedence.

The other option that could be created is setting the time at which an autoplaylist is added to the show. It right now defaults to an hour before the show is scheduled. This could be user configurable on a site-wide setting and overridden on a per show basis. I'm not sure how useful this would be.

The last bit of functionality built into the UI would be updating the calendar to show tracks with auto-playlists as differently than the red ! mark. Rethinking this would depend upon the options implemented from above.
