### ISSUE TITLE
Consider gRPC for synced internal service communications

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1381]
**Is your feature request related to a problem? Please describe.**

We are using a mix of rabbitMQ queues and http api client to communicate between services.

A message queue is a good way of dispatching async request to services, but for request/response communication the current api client is not the best solution in my opinion.

**Describe the solution you'd like**

We should consider using the gRPC framework for internal communication between our service. Most of the code is generated, fully typed, and reduce a communication call to a single python function call.

But we need to find the downsides of this technology.

https://grpc.io/docs/what-is-grpc/introduction/
https://grpc.io/docs/languages/python/basics/

**Comment by paddatrapper** [comment]
If anything, I would prefer using the MQ to report back the result instead of anything else. I still prefer HTTP requests over gRPC though, as it is well defined, used (especially once we move to the Vue frontend) and a known quantity. We already have retry and failure monitoring/management built-in. I don't see how a 3rd format and process is going to help us simplify things...
