### ISSUE TITLE
More caching for packages install in vagrant boxes

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1396]
**Is your feature request related to a problem? Please describe.**

We should find a way of caching the packages installation in the vagrant box, so we don't have to run the huge packages installation over and over. Or at least cache the downloaded packages.

**Describe the solution you'd like**

- Mount the apt cache folder to prevent downloading over and over the same files
- Build on the fly a new image with only the package installation and use that cached image instead (like docker caching ?)

**Comment by jooola** [comment]
I am not a fan of having to alter the host os setup to provide a solution for a single project. I would prefer to simply mount the apt cache dir on the guest and reuse it for the next box install.

https://gist.github.com/juanje/3797297

**Comment by paddatrapper** [comment]
The extent of the modification required is `sudo apt install apt-cacher-ng`. It is very handy for a variety of things: Debian packaging uses it extensively as well as containerization and virtualization hosts. You can also run it on a network attached server to serve the entire network.

I wonder if there is a way of using apt-cacher-ng if it is available, otherwise mount the cache as a shared directory
