### ISSUE TITLE
airtime-import not installed when installing from the git .gz file

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#144]
I can see it in the the gz but where does libretime expect to find it?
A file search says it is not anywhere on the system except in the GZ

**Comment by hairmare** [comment]
I think that is the expected behaviour 😞 A quick look at the script tells me that it is still largely based on media-monitor which has been mostly replaced.

Depending on your needs maybe the the [`ftp-upload-hook.sh`](https://github.com/LibreTime/libretime/blob/e5295a0d583a12cf7e0491272790fef30bd7bb6a/python_apps/airtime_analyzer/tools/ftp-upload-hook.sh) script might be of use to you. Otherwise I'd assume that re-adding watched folders as is being implemented in #111 might work for you.

**Comment by JohnnyC1951** [comment]
I just found that the RSS import is failing here too. I will go digging

**Comment by Robbt** [comment]
The RSS import currently only happens if you have music/tracks playing due to its dependence upon API calls by the pypo scheduler. This will be fixed in the near future when I have time to make it happen periodically independent of tracks being played. Can you confirm if this is the reason it isn't working.

**Comment by hairmare** [comment]
You can also trigger it by requesting `/api/version` in you browser if that's the issue.

**Comment by JohnnyC1951** [comment]
Fixed it by new external code.
