### ISSUE TITLE
Run python tests through travis

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#15]
Currently the available python tests are not getting run regularly.

Travis was configured to run php tests in #14 and python needs to catch up.

Solution: Add python to travis setup and run tests.

This needs a bit of a complex setup since we install python in addition to the already available php.

Travis is on ubuntu10 so I don't see any surprises there. An example of how to install python on a project that is on a different language is at https://github.com/travis-ci/travis-ci/issues/4090#issuecomment-184811689.

* [x] analyzer
* [ ] pypo
* [ ] api_clients

**Comment by hairmare** [comment]
I've got the analyzer mostly figured out and will do a pr on that after cleaning up my local branch.

I looked into pypo and api_clients, to no avail. I'd be glad to pass on the torch for getting those test sets running after i finish the analyzer parts.

**Comment by hairmare** [comment]
Now that analyzer is mostly tested in #21. I'm de-assigning myself from this issue. I'm just not that much of a python buff to figure out what is wrong with the pypo and api_clients tests.

**Comment by Robbt** [comment]
I'm looking into revisiting this, or at least the python testing in general. It seems like tests were wrote for Analyzer using nose but I don't really see any comprehensive testing for pypo, there is a test of the API which just tests that it can connect and a test_modify_cue_in test and that depends upon pytest which needs to be installed with `sudo pip install pytest`

That results in an error with importing the PypoPush class - ```

ImportError while importing test module '/vagrant/python_apps/pypo/tests/test_modify_cue_in.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_modify_cue_in.py:1: in <module>
    from pypopush import PypoPush
E   ImportError: No module named pypopush

```

So that will require some troubleshoot or perhaps we should try to rewrite the tests. I have an intuition that proper testing might help us troubleshoot some of the inconsistent behavior we have with pypo in production #232  but I'm also not sure how to go about testing properly since it involves working with liquidsoap.

**Comment by hairmare** [comment]
IMHO pytest is the way to go anyhow.

I've seen that the analyzer nosetests are runnable with pytest, so we're good there.

I haven't had any luck with the pypo tests either (a stumbled over the pypopush error as well).

When it comes to the API we probably won't get away with unit testing alone. Some of the tests are end to end test and not really focussed on units. We will probably have to set up and tear down an API instance to test against for those cases. This also concerns the selenium tests as per #16.

Getting the tests to work will probably help with troubleshooting, it will also help us not introduce any regression errors. The tests can also help with re-factoring where it is needed.

**Comment by Robbt** [comment]
Speaking of tests this is unrelated the the PythonTests but more to do with the PhpUnit Tests.
I discovered a few random tests under airtime_mvc/application/models/tests which use PhpUnit but aren't compatible with the current environment. I am trying to get them working but they weren't written to use the current model framework or schema so they will need moved and rewritten or scrapped.

**Comment by hairmare** [comment]
Feel free to scrap them, I can't see anything recognizable in them (I haven't seen `Application_Model_ScheduleGroup` in our current code base).

Also, muppets 😛

**Comment by Robbt** [comment]
Yeah I am just trying to figure out the best way to write good tests for things like say the SmartBlock code. If we were able to implement anything resembling good coverage for tests it might speed up development. Before I go about refactoring it, it'd be nice to make sure that any changes I implement don't break the existing functionality etc.

At this point the current test coverage seems to be somewhat random and there is no documented way to write tests for a lot of things. I spent some time pouring over the old Wiki pages from wiki.sourcefabric.org to see what I could retrieve for our documentation purposes but someone at SourceFabric deleted or removed permission from the public for reading most of the stuff that was linked to under DeveloperDocs. I found some  interesting stuff that was still around but not directly linked to on the page.

I think it'd be good for us to document how to populate a test database and also it'd be good to figure out a way to really test the Pypo code with Liquidsoap. 

I'll try to be better about documenting everything while I'm working both for my own personal reference and so that we can make it easier for people to contribute in the future.

**Comment by hairmare** [comment]
[This test](https://github.com/LibreTime/libretime/blob/f1e467c3e645d6642419330e6551e46ac4490947/airtime_mvc/tests/application/models/database/ScheduleDbTest.php) has some db setup in it (it is php, but the datasets used there might be re-usable for python to some extent).

I've found that some of the sourcefabric wiki can be accessed through the wayback machine. I think this [link](https://web.archive.org/web/*/http://wiki.sourcefabric.org/display/CC/*) has most stuff.

To test pypo against a real env we might have to set up a "test" libretime-web to run the tests against.

On travis we are currently using their docker infra. I assume that we would need to switch to `sudo: true` so we can set up our own system to test against... I can refactor the travis stuff once we figure out how to run the tests locally.

**Comment by paddatrapper** [comment]
api_clients tests are now run in Travis. With no tests happening in pypo, I'm going to close this issue and open new ones for the other issues identified here
