### ISSUE TITLE
Drop python 3.6 support

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1751]
I propose to drop support for python3.6 as it is EOL and many packages start dropping support for python3.6.

On systems that still rely on python3.6 as default, such as bionic, we could do the following:
```sh
# Install python 3.7
sudo apt-get install python3.7

# Create python3 alternatives
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2

# Set the default alternative to python3.7
sudo update-alternatives  --set python3 /usr/bin/python3.7
```

I am unsure whether this small trick is less headache than having to watch our requirements to prevent incompatible upgrades.

**Comment by paddatrapper** [comment]
Changing the system default Python version is a really bad idea. It can cause things to break in many ways that we don't expect (because some system components are written in Python). I don't think we should drop python 3.6 support until 18.04 is EOL next year.

The alternative is to be explicit in the python3 binary on 18.04 and invoke `python3.7` instead of `python3`.
