### ISSUE TITLE
Push Data To TuneIn not working here

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#189]
Not sure how to troubleshoot this.
Went back to JohnnyC's AT contrib, using php cron job based code, and that still works - using the same credentials.

**Comment by hairmare** [comment]
You should see requests from pypo/api_client going to an API URL with `update-metadata-on-tunein` in your access logs.

The used api call should log any errors to ` /var/log/airtime/zendphp.log`. At least the test call from the ui does on my Ubuntu trusty vagrant box, All I can see is a sad tape since the api returns non xml when called with invalid parameters :(

I just cross checked the code against tuneins API docs and everything checks out so I can only assume that pypo isn't triggering the mvc properly if nothing is in the logs.
