### ISSUE TITLE
Question. Re self-updating repeating show content. (Talk Radio)

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#194]
This really only concerns talk-show stations, I guess. We have a good working solution for updating long talk show programs automatically. But it is involved, machine intensive and uses a lot of Sox to do it.

The problem is that incoming shows may vary in length from, say 1:10:00 to 1:30:00 so we have to pad & cross-fade them with music, adverts etc. to make a single track of the same length and filename and then update the show title, other stuff like show logo, and description. This is working live right now.

We used to use watch folders, made an interim solution, but now we do not have to and are working directly on the database and imported folder tree.

**So under Libretime is there a better way that we missed?** If not could we add such a feature to that incoming shows self schedule? Example: get the length of the show file and autoplaylist to the end of the slot - even if the main file length has changed? We never change the core, but there are limits.

JohnnyC is talking about making a new engine optimized because this (and handling video YouTube/Roku/MP4 with 'Postcard' Video leveraging GPUs) which sounds overkill, but what do I know?

**Comment by hairmare** [comment]
> The problem is that incoming shows may vary in length from, say 1:10:00 to 1:30:00 

At first I though your case sounds like a use case for an [asi card](www.audioscience.com/internet/products/livewire/asi6585_asi6685.htm) that can do time scaling on its DSP. But that only gets you +/- 20% scaling and might sound weird if you use its available headroom. So you do need something to help solve the issue.

> so we have to pad & cross-fade them with music, adverts etc. to make a single track of the same length and filename 

Doing this part in pre-production doesn't seem like the worst solution. It takes the load off of liquidsoap and allows you much more control over the process in the long run. Metadata (PAD) is a different question though (depending on your needs).

> and then update the show title, other stuff like show logo, and description. This is working live right now.

I think parts of this might be achievable with some of the poorly documented APIs LibreTime offers. In theory the show logo can be managed with the [show image api](https://github.com/LibreTime/libretime/blob/master/airtime_mvc/application/modules/rest/controllers/ShowImageController.php). At a glance it can be used to upload and remove show images. It needs testing, documentation and probably some implementation work/bugfixes. 

> We used to use watch folders, made an interim solution, but now we do not have to and are working directly on the database and imported folder tree.

I think there is nothing inherently bad with both of those solutions. I really depends on what works for you. 

Once watching folders works again that might take some burden off your code. 

At rabe we also have some value added software that interacts directly with the database (like an [idjc](http://idjc.sourceforge.net/) fork for studio playout or an external [archiving solution](github.com/radiorabe/raar)). For the most part those are read-only and I am thinking of replacing the database integration points we are using with some API in the long run.

> So under Libretime is there a better way that we missed? 

Right now, I don't think so. In the future there might be more and better APIs to help integrating your own solution. 

> If not could we add such a feature to that incoming shows self schedule? Example: get the length of the show file and autoplaylist to the end of the slot - even if the main file length has changed? 

I think a combination of smart blocks and autoplaylist might do the trick. The smart block would take care of scheduling the main contents and the autoplaylist would then add filler material to fill the show instance up to the next show. I think you would also want watched folder support (#111) and relative filtering (#13) for an easy to set up solution.

> We never change the core, but there are limits.

I have been thinking about adding some integration points to the core liquidsoap scripts to allow for pluggable encoders, processors, and replaceable silence. I don't think this should be in the UI because it would make it much too easy for folks to break things. I was thinking something along the lines of being able to define `/etc/airtime/encoder.local.liq` and then have that code loaded in the proper place. We would need to define a low level API for it (like a liquidsoap function with a magic name that gets called). I plan on tidying up the liquidsoap code before I give hackable encoders and processors much consideration though.

**Comment by Robby262** [comment]
At the moment we scan through the active scheduled shows and from that do a lookup on filtered cc_files to find its main filename, replace the main file in /import and update the show info from ID3 tags from the incoming file.

Can smart-blocks cope with a changed file length? Before, using AT watched folders, it did update the file and silan it but the playing time, in the show instances, remained the same - hence the need to pad the file to a known length - else the end of the incoming show got truncated or under-ran.

With regard to Liquid soap modification, most people just want to add some emergency auto-dj. If you simply had a default named 'silence auto-playlist', I think that would keep most people happy.

**Comment by hairmare** [comment]
> Can smart-blocks cope with a changed file length?

I think they can, at least dynamic smart blocks should be able to do this. `libretime-watch` would still need to do the right thing for changed files for everything to work out. I'm assuming that the first implementation will behave like legacy `airtime-watch` did, changing that to update file lengths and metadata should be fairly straightforward.

> If dynamic ones recalculated the list when it cached the files, each run, that would solve it.

I'm not sure when exactly dynamic smart blocks get recalculated. I think they get populated when they are assigned to a show. For this to work the smart block would need to get scheduled by the autoplaylist feature. That needs to be verified since I'm not exactly sure that if we have a solution that adds up to your use-case.

> A use overridable .liq is a good idea. With regard to Liquid soap modification, most people just want to add some emergency auto-dj.

Personally I'm more interested in on air processing and pluggable encoders. The silence thing is probably of more use to the community at large.

**Comment by bburton** [comment]
@hairmare I have already implemented hooks or callbacks at three points in the ls_script.liq file:

1. **Scheduled Fallback - custom.scheduled_fallback()** - Fallback to a different stream when there's no scheduled content. Instead of hijacking the default stream like various hacks, this one uses a new stream and integrates in a more sensible manner so the default fallback still works.
2. **Submit Metadata - custom.submit_metadata(s)** - I currently use this to post track updates to Liquidsoap Flows and Tunein.com. In the latter case, there's some logic to look at the track metadata and set commercial=true/false. This hook might be better named, _custom.metadata_changed()_.
3. **Stream output - custom.output(s)** - Send output to one or more targets. Could be used to send output to one or more stream(s) or implement stream-based recording. I've used it successfully for the latter where it created a new recording every hour.

Like you proposed, I have my custom logic in a file in /etc/airtime which is %include'd into ls_script.liq so upgrades won't wipe it out but a default version of the file must exist whether or not an admin makes any customizations.

**Comment by Robby262** [comment]
No. I just checked. Dynamic start blocks are calculated at schedule not play-out time. I raised a new issue for this #195

**Comment by Robbt** [comment]
@Robby262 if a show length is changed after it is scheduled there is no way for LibreTime to know that the show is not as long as it should be. One way around this is to use the SmartBlock & AutoPlaylist to schedule the show right before it is supposed to air and not manually hacking the file system by overwriting the file. If you were overwriting the file directly on the file system the LibreTime calendar would then have incorrect values for what is supposed to be airing and how long it will air. 

In my opinion the goal here should be to make the system work without these sorts of hacks that were required previously due to the poor support for actual automation. 

Otherwise we are talking silence detection and using liquidsoap to select tracks and that is a whole other avenue of work that I haven't done yet but I know others have. Whether it is feasible to build a web interface to interact with this or if we just go ahead with making it easier for people to add their own custom liquidsoap hacks w/o messing with LibreTime's UI is still up in the air. Obviously the 2nd one is easier and probably a good first step.

 Otherwise we are talking about building an function for LibreTime to go in and automatically adjust schedules and rescan files before playout which is somewhat redundant with what the autoplaylist is supposed to do. This notion of filler tracks or unscheduled smartblocks was considered but it was going to require a much bigger overhaul of the UI than the approach I ended up taking. 

But I chose my approach of triggering a schedule of playlists automatically vs. building a separate style of block back when I was building this myself w/o anybody to help and I was hoping that I would be able to push my code back to Airtime to avoid a fork and I wanted to do the least intrusive approach. The negatives remaining from my approach are the UI shows unscheduled autoplaylist shows as red ! and the UI is still not widely understood or documented by the interface. It is also currently limited to appending onto the end of whatever else someone might schedule in the beginning.

I had the idea of making multiple autoplaylists such as a prepend in addition to the append one so that it could simply insert a Station ID before every show that may already be scheduled. It could also be good to make a smartblock length that when scheduled it reads whatever time is remaining and schedules to that limit. But I want to finish work on relative dates #13 and fix the autoplaylist #129 first.

**Comment by Robby262** [comment]
I am testing this right now Robbt.. Will report back

**Comment by Robby262** [comment]
I have been using this for some days now on all shows with a Jingle followed by a smartblock in the Autoplaylist. That works well and my LS AutoDJ fills to the end of the slot.
Next, I shall try adding items after the smartblock and see what happens. EG Webstreams / Other Smartblocks
