### ISSUE TITLE
Problem: update checker is too naggy in tarball install

### ISSUE THREAD

**Issue by ghost** [LibreTime/libretime#198]
New version available: 3.0.0-alpha.1

    Multiple major updates for LibreTime installation are available. Please upgrade as soon as possible.

**Comment by hairmare** [comment]
The root of this is multiple issues, the installer doesn't install the VERSION file properly so the code assumes to be at version `3` leading to an undefined state in the actual checking code (and more naggieness than needed).The checker is also a bit too naggy in general (especially on pre releases).

I didn't notice the install issues because vagrant usually uses the `--in-place` arguement that points the wwwroot to the git repo in `/vagrant` where the file is available.

I plan on waiting to fix this in the installer until we get the systemd detection changes into it. Enabling those will make things more stable on all affected platforms so I'm giving it priority.

As a workaround you can create a `VERSION` file containing the current version next to the `airtime_mvc` folder in your docroot. I think the web_root currently defaults to `/usr/share/airtime` so the following should get rid of some of the naggieness.

```bash
echo '3.0.0-alpha.1' > /usr/share/airtime/VERSION
```

The overall naggieness only affects pre releases. When I started implementing it there were no releases so I implemented parts of it against other repos with similar version numbers. Hardly an ideal situation to start with. I expect it to become less naggy once we get closer to a release. Given it being broken doesn't impact any core functionality it isn't at the top of my list. I plan on sorting this out once we have some beta releases (or get closer to them). 

If someone else is motivated to give making the update checker better a go, #102 should help you figure out what parts of the code make it up. The current behaviour from there is loosley based on what legacy upstream was doing but also tries to take into account semver.org.
