### ISSUE TITLE
I do wish you guys had a forum or used the one we provided - as you do not I must post this as an Issue which it really is not.

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#208]
JohhnyC & I must have done eleven real LT installs between us and lots more to come.
A note. But before someone says these are not LT issues (which, indeed they are not) some patterns are emerging of problematic installs.

#1 by far is RabbitMQ and Host, Hosts files and the ways that VPS providers set (or fail to set) this up.

Example: one popular VPS systems makes a host file of like: 123.456.789.1 and that is the whole file! 
We have seen: 123.456.789.1 UnixUsername 
and 123.456.789.1 <empty>
RabbitMQ won't start at the end, but the install continues for 4 minutes, or so, but the install doesn't work.
We suggest a 'pre-flight test' - something that checks host and hosts file and at least warns if it obviously wrong/invalid and stops - with some useful suggestion - or tells RabbitMQ to use IP IP which seems to work.
Sneering will get a sharp and very final response.

**Comment by Robby262** [comment]
Never mind.

**Comment by hairmare** [comment]
>Never mind. I was just told that is a user issue.

We can't delete issues, all that is possible is to delete their text and that doesn't help for the most part since it's just plain confusing.

We would prefer to understand such issues users are running into. For the most case they can be 'fixed' by adding info to the docs.

> Example: one popular VPS systems makes a host file of like: 123.456.789.1 and that is the whole file!
> We have seen: 123.456.789.1 UnixUsername
> and 123.456.789.1 

The `123.456.789.1 UnixUsername` looks valid, the plain `123.456.789.1` looks completely invalid. At least for a `/etc/hosts` file.

> RabbitMQ won't start at the end, but the install continues for 4 minutes, or so, but the install doesn't work.

Wrapping the startup call with a `timeout` might help it not hang for ages. Maybe this gets better once systemd is the norm.

The "preparing the server" docs have a [hint about the RabbitMQ hostname](http://libretime.org/manual/preparing-the-server/#rabbitmq-hostname) but it doesn't have a simple working example. Would it help if there was an example to configure RabbitMQ to run on localhost? 

Maybe RabbitMQ should have it's own chapter in the docs. This could also contain specific info for widely used platforms (ie. supported operating systems as well as maybe ovh, digital ocean, and more).

> We suggest a 'pre-flight test' - something that checks host and hosts file and at least warns if it obviously wrong/invalid and stops - with some useful suggestion - or tells RabbitMQ to use IP IP which seems to work.

Checking the `/etc/hosts` file is hard since it is different on most targets. Maybe a check for rabbitmq listeners to make sure it's running can help. Right now most of this check is done during setup after entering rabbitmq config values. Maybe that is too late.

> Sneering will get a sharp and very final response.

Yes, it will. What can be done about the following?

> We would say that user issues are important, but we will bow to youth and their greater wisdom and experience,
