### ISSUE TITLE
Random lenght of FadeIN and FadeOUT

### ISSUE THREAD

**Issue by aresstokrat** [LibreTime/libretime#219]
problem randomly appears in silan 0.3.3 , using this package from https://github.com/LibreTime/libretime/issues/214#issuecomment-305988355
In admin panel 'FADE IN' and 'FADE OUT' set to '0.1'

In reality its fadeIN or fadeOUT  from 0.1 to 40 seconds !!!
The length of tracks are correct after upload.

**Comment by hairmare** [comment]
Can you check what their value is in the database?

You can query the files using the following statement, just replace "Voodoo" with something that is part of the affected files name.

```
sudo -u postgres psql -c "
    SELECT id, filepath, cuein, cueout, length
    FROM cc_files 
    WHERE filepath LIKE '%Voodoo%';
" airtime
```

If you can compare these results to what silan is returning when called directly that would be awesome. It will help to figure out if this is primarily a silan or a LibreTime issue (I always assume silan to be the propblem, maybe I'm wrong). 
You can run `silan --format=JSON <filename>`, where `<filename>` is the path to an affected file from the above query, to use silan in the same way LibreTime does during the import.

I've been searching for libre (ie. Creative Commons or public domain) files that exhibit this issue for a while now. If someone has any it would help in creating an upstream issue to try figuring this out. 

BTW, this issue seems somewhat similar to #125. Maybe you can see something that matches up with your issue that I'm missing.

**Comment by aresstokrat** [comment]
Hi @hairmare !
10 secs of this track was a FadeIN:

postgres q:

```
 id  |                                                filepath                                                |      cuein      |     cueout      |     length      
-----+--------------------------------------------------------------------------------------------------------+-----------------+-----------------+-----------------
 225 | imported/1/Paul Oakenfold/Swordfish <<The Album>>/Paul_Oakenfold_-_Dope_Smugglaz_-_Word_[PMT_Remix.mp3 | 00:00:00.006213 | 00:04:31.830181 | 00:04:31.773333
```

direct:

```
$ silan --format=JSON "/srv/airtime/stor/imported/1/Paul Oakenfold/Swordfish <<The Album>>/Paul_Oakenfold_-_Dope_Smugglaz_-_Word_[PMT_Remix.mp3"
{ "sound":[ [ 0.006236, 271.830181 ]], "file duration":271.830181, "sample rate":44100}

```

#125 i met in my practise, but now after last install from git there is no such defect for me.

**Comment by hairmare** [comment]
The `length` seems to match. I need to look at the code to compare the `cuein` and `cueout` values. At a glance the `cueout` value seems a bit high.

I'll also do some testing with the fader settings, this might be an issue with how liquidsoap fades the tracks rather than with silan.

**Comment by aresstokrat** [comment]
fades does't use silan?

**Comment by hairmare** [comment]
> fades does't use silan?

Silan is used to decide when to cue in and out of tracks, liquidsoap does the actual crossfading (while taking silan information into account).
