### ISSUE TITLE
Question: Can't find settings for Podcast limits list per page

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#227]
I have 10 podcasts per page, I broke my head, but can't find the settings of file where these settings are. 
I want to change limit from 10 podcasts per page to 5. 
I would be appreciate if you tell where to dig.
Thanks

**Comment by hairmare** [comment]
There doesn't seem to be a way to set this 😞 

The feed response is made in [`FeedsController::stationRssAction()`](https://github.com/LibreTime/libretime/blob/dea59558a2047ab21e14278ed7a85e85317614a9/airtime_mvc/application/controllers/FeedsController.php#L19). I found [the propel query](https://github.com/LibreTime/libretime/blob/dea59558a2047ab21e14278ed7a85e85317614a9/airtime_mvc/application/services/PodcastService.php#L411) that looks like it's the one responsible for loading episodes.
I can't explain why it's limiting to exactly 10 😕

## Proposed Solution
If we implement this it would probably be editable in «My Podcasts» in a new block «Settings» and it would store the value somewhere in `Application_Model_Preferences`.

## Workaround
If I'm not mistaken a quick hack to the propel query would be adding `->limit(5)` instead of [this](https://github.com/LibreTime/libretime/blob/dea59558a2047ab21e14278ed7a85e85317614a9/airtime_mvc/application/services/PodcastService.php#L411)
```php
$episodes = PodcastEpisodesQuery::create()->filterByDbPodcastId($stationPodcastId)->limit(5)->find();
```

**Comment by korotkov13** [comment]
Thanks for reply! I changed it but it didn't helped.(

**Comment by hairmare** [comment]
I'll need to test it locally then.
