### ISSUE TITLE
Airtime-Playout doesn't produce logs on Ubuntu 14.04

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#234]
There is an issue with our configuration that is preventing airtime-playout from updating or producing logs on Ubuntu 14.04.

This worked with 2.5.x and has been referred to as being readable via systemd but the files are not being written to or updated with the default set-up from the installer.

**Comment by hairmare** [comment]
A bit offtopic since this is about Trusty: AFAIK systemd based distros should manage some of these requirements through the [systemd journald service](https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html) in combination with [tmpfiles.d](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html).
