### ISSUE TITLE
Player Widget shows the track filename not the title

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#242]
EG. Shows joe378910.mp3 instead of 'All Along The Watchtower'.

**Comment by hairmare** [comment]
Does it show the right metadata when you "Edit..." the file in question through the context menu in the library?

When the analyzer has issues due to special characters in the metadata it can happen that files get imported without metadata. Can you post the output of `airtime_analyzer --debug` when re-uploading the exact same file? That would help narrow down the issue.

**Comment by Robby262** [comment]
The correct metadata is displaying in the context menu.
However, please note this. These files were imported as Podcast. When importing as 'Podcast', every item shows FAILED in the right-hand box and the Created by Field is also always blank. However, the files do show up in tracks and work.
