### ISSUE TITLE
Port Python code to Python 3

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#257]
Python 2.7 is EOL in 2020. Distros are getting reluctant to accept new packages with python 2.7 code as they are promoting the use of Python 3. Debian for example will soon have a lintian warning tag on packages using Python 2.7. The python scripts used in LibreTime should be ported to Python 3

**Comment by hairmare** [comment]
Absolutely, I've started looking into [2to3](https://docs.python.org/2/library/2to3.html) and the whole conversion process but won't get around to doing any serious damage anytime soon. 

Using [python future](https://pypi.python.org/pypi/future) we should be able to maintain the code base in a way that it maintains python 2 compatibility until everything is really ready.

**Comment by paddatrapper** [comment]
I fully understand that this is not a trivial issue and I'm glad to see it's on your radar. I doubt I'll be able to help, as my python skills are barely usable at best, but will try if I get time

**Comment by hairmare** [comment]
I'm also not much of a python guy myself, but I'm learning.

As far as I can tell most of the rewriting needed is pretty basic. I see most issues in having to use external requirements that work on both versions as well.

**Comment by paddatrapper** [comment]
It's default on pretty much all of them, but as far as I know all of them support running python 3 through `/usr/bin/python3`

**Comment by hairmare** [comment]
Yupp, except CentOS which still only support 3.4 (using `/usr/bin/python34`). If we can wait until CentOS 8 is released with dropping python2 support that would be awesome and make life for the `./install` installer much easier.

Quite some of the python3 work can be done without breaking py2 anyway.

**Comment by paddatrapper** [comment]
Ah I see... When is Centos 8 due?

**Comment by hairmare** [comment]
No definitive date yet, but a RHEL8beta was recently release so it won't take ages.

**Comment by chaudum** [comment]
Hi, I am happy to help porting the Python applications to Python 3. Are there any resources I could have a look at first, otherwise I would just go through each app individually after each other.
I guess, packaging would be affected, so any hints regarding that would be very helpful!

Ideally, the port would require Python >= 3.5 (to be future bound) and I would not suggest to support Python 2 any longer thereafter.

CentOS 8 is [still not released](https://wiki.centos.org/About/Building_8), but RHEL 8 was released in May 2019.

**Comment by Robbt** [comment]
Well help with the porting is definitely welcome, the challenge will be ensuring that it doesn't introduce any more bugs or worsen any of the existing ones.

*Airtime-celery* should be pretty straightforward to convert and is minimal code it just connects 

Pypo is the glue that handles communication between liquidsoap and the web interface and is highly critical and has some bugs or undefined behaviour that can occur and screw up the broadcast. I think if and when we rewrite this it would be good to try to build a proper test suite that confirms the messages sent to liquidsoap always make sense. Since none of the current developers have touched this much (it is primarily a relic of pre-fork Airtime), it is important that whoever rewrites it has a reasonable understanding of it.

Airtime_analyzer would probably not be too hard to convert to python 3, in some ways it is a stripped down version of the media_monitor that was useful in airtime 2.5.x since it doesn't provide a way to watch folders. I started on a python 3 module that watched folders and imported anything added to it directly but ran into issues using it as a primary import mechanism in that it if you just copied files directly it would run into some OS level limits on # of open files and just stop working. See https://github.com/LibreTime/libretime/pull/514 and also some watched folder code that never made it into production here - https://github.com/LibreTime/libretime/pull/111

For the API client, this would be a great thing to take on but porting the existing code to Python 3 wouldn't be that useful as we have never developed a proper API definition and I don't even know exactly if this code is even being used. 

It looks like the icecast2 module just installs icecast. 

So help with Python 3 porting is definitely welcome but there are probably also various improvements that could be made in the process that would be useful in addition to a straight conversion. 

Thanks for your interest @chaudum , are you involved in a project that is currently using LibreTime or that is planning on using it ?

**Comment by chaudum** [comment]
> _Airtime-celery_ should be pretty straightforward to convert and is minimal code it just connects
> 
> Pypo is the glue that handles communication between liquidsoap and the web interface and is highly critical and has some bugs or undefined behaviour that can occur and screw up the broadcast. I think if and when we rewrite this it would be good to try to build a proper test suite that confirms the messages sent to liquidsoap always make sense. Since none of the current developers have touched this much (it is primarily a relic of pre-fork Airtime), it is important that whoever rewrites it has a reasonable understanding of it.
> 
> Airtime_analyzer would probably not be too hard to convert to python 3, in some ways it is a stripped down version of the media_monitor that was useful in airtime 2.5.x since it doesn't provide a way to watch folders. I started on a python 3 module that watched folders and imported anything added to it directly but ran into issues using it as a primary import mechanism in that it if you just copied files directly it would run into some OS level limits on # of open files and just stop working. See #514 and also some watched folder code that never made it into production here - #111
> 
> For the API client, this would be a great thing to take on but porting the existing code to Python 3 wouldn't be that useful as we have never developed a proper API definition and I don't even know exactly if this code is even being used.
> 
> It looks like the icecast2 module just installs icecast.

Thanks for the quick summary of the packages!

> Thanks for your interest @chaudum , are you involved in a project that is currently using LibreTime or that is planning on using it ?

I've been playing around with Airtime back in the days, but was not very happy with the poor support.
Today, we at [Radio Proton](https://radioproton.at) (Austria) are looking for future proof alternatives for our current system, and Libretime looks like a promising option :)

**Comment by chaudum** [comment]
So I ran into the problem that [rgain](https://pypi.org/project/rgain/) - a dependency of airplay_analyzer is not compatible with Python3 and moreover unmaintained :(
The source is available on [Bitbucket](https://bitbucket.org/fk/rgain/src/default/), not sure how much effort it would be to make it Python 3 compatible.

**Comment by Robbt** [comment]
Ok, yeah I think this did get brought up in the past when we were analyzing packages for inclusion of LibreTime in Debian.

So the developer didn't think it would take too much effort on his request for a new maintainer - the question is does someone from LibreTime want to [take over maintenance of rgain](https://bitbucket.org/fk/rgain/issues/26/wanted-new-maintainer) ? 

I have never maintained a pip package and replaygain.org appears to have had their domain taken over due to lack of renewing it and someone replaced it with a link to random multimedia software - here is a link to the original [page](https://web.archive.org/web/20140209223202/http://www.replaygain.org/) also available [here](http://wiki.hydrogenaud.io/index.php?title=ReplayGain_specification) and there is a more general page [here](http://wiki.hydrogenaud.io/index.php?title=Replaygain). The replaygain.org site was just a link to the hydrogenaudio wiki anyways.

Maybe it would make sense to do a test port of replaygain to python3 and see if it is easy to do and whether you would want to help maintain it. If becoming the maintainer isn't something you'd be interested in doing we could attempt to do this as the libretime project but someone would still have to do the initial port to python3 and we should reach out to Felix Krull the current maintainer if we decide to go this route.

**Comment by chaudum** [comment]
> Maybe it would make sense to do a test port of replaygain to python3 and see if it is easy to do and whether you would want to help maintain it. If becoming the maintainer isn't something you'd be interested in doing we could attempt to do this as the libretime project but someone would still have to do the initial port to python3 and we should reach out to Felix Krull the current maintainer if we decide to go this route.

I've forked the repo to my Github account and spent some time to port to Python 3.5 (should be upward compatible).
The biggest problem for me was the setup of all the dependencies and having a clean test environment. Here is the draft: https://github.com/chaudum/rgain/pull/1

From a code complexity perspective, the package is more or less trivial, however I have no clue tbh, what the underlying analysis (the stuff performed by gstreamer) does.

**Comment by paddatrapper** [comment]
Replay Gain is essentially a normalisation algorithm to ensure multiple files played in succession are sound as equally loud. As I understand it the GStreamer analysis thus should be explained in [the spec](http://wiki.hydrogenaud.io/index.php?title=ReplayGain_specification), but I haven't read much about it yet

**Comment by hairmare** [comment]
A while back I was looking into replacing `python-rgain` with an alternative that does proper [EBU R128 loudness](https://en.wikipedia.org/wiki/EBU_R_128) based normalization. I never found an python implementation that doesn't depend on ffmpeg which kinda blocked my efforts (IMO somethig based on py-gst would have been preferable). At the time my plan was to allow choosing between rgain and r128 in config.

IMHO the differences between rgain and R128 aren't very audible. Switching to R128 would just mean that we use the same algorithm officially used to measure loudness by most regulatory bodies. As far as I understand R128 has also been adopted by non-EBU agencies (ie. ATSC A/85 in the US iirc).

One might still consider rgain more relevant for stream-only stations where R128 is aimed at the broadcast segment (ie. DAB+, DRM, ...).

If python-rgain gets maintained again, I'm sure lot's of folk that depend on it will be glad. Did you contact the ex-maintainer?

**Comment by chaudum** [comment]
> If python-rgain gets maintained again, I'm sure lot's of folk that depend on it will be glad. Did you contact the ex-maintainer?

The Python 3 port already works and [test suite passes](https://travis-ci.org/chaudum/rgain/builds/558632143?utm_source=github_status&utm_medium=notification). There is still room for improvement in the code, though.
If commented on both the original repo, as well as mentioned the ex-maintainer on the Python3 PR of my fork, but no response yet.
