### ISSUE TITLE
Locating all instances of a scheduled media file

### ISSUE THREAD

**Issue by charlesh3** [LibreTime/libretime#284]
We (KBFG-LP) have a lot of spots scheduled but expire on a certain date. In Airtime (RIP) there was no way to produce a list of all scheduled instances, delete the e3xpired content, and replace it with something else.

A quick look at LibreTime and I did not see any way to do this. Did I miss something?

If not, it wouldcertainly be a worthwhile new feature as all stations have content that expires.

Chuck
KBFG-LP

**Comment by hairmare** [comment]
Hi Charles

Welcome to the community 😃 

If legacy upstream didn't have it, it's probably not in LibreTime. The feature you describe certainly does sound worthwhile and we would absolutely welcome any pull requests that help managing show content.

How did you keeping track of the expiry dates in you existing solution? If you're not a coder, you can also help  by providing as much detail about the feature to aid anyone that wants to give implementing it a shot.

**Comment by charlesh3** [comment]
We're new so to date we have manualy (!) scanned the entire schedule to find certain promos.

We recently did a benefit show and had a promo for it every couple of hours, every day. The pain of finding and removing them is what led me to ask if the problem is solved.

I'm an electrical engineer so real coders would tell you I am not a coder. They would be right. I do have a good c backgreound and a few small programs in c# / c++. So my role could not be anything huge,

Is there a formal method for submitting new feature requests?

Chuck

**Comment by Robbt** [comment]
There is no formal method at this point. The best approach is to document it as best as possible inside of a comment. I had the idea of "archived content". Then you could hide content that is "archived" and have it archived automatically based upon some criteria. Perhaps we could add a new date/time field to track files called expires on. This would be useful for PSAs and could be added to smartblocks. 
There could also be an "archived field" that would be on the track and get set after the track "expires".

As far as manually scheduling and replacing/rescheduling automatically this seems like it would be tricky. My idea is that a lot of the scheduling would be done just in time via automatic playlists vs. scheduling a bunch of days ahead of time. 

If we implemented the "expire date" there could be a function that removes all expired scheduled content that would look for content that has its archived bit set and is on the schedule and removes it. Now the more challenging part would be automatically replacing it because track lengths could vary and it would probably be easier to do this via something like a self-updating smartblock anyways.

**Comment by JohnnyC1951** [comment]
I have to do it manually, else the server full of old news bulletins and the like. In 'Tracks' I pick a genre, sort by date and chop off the old ones. Any that are scheduled do not get deleted and it tells you so. I only want to cull certain genres whilst keeping the music library.
