### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by CGenie** [LibreTime/libretime#292]
Hello,
Thanks for a great product.
Is there any chance of getting Docker images for libretime? Currently, .deb files are a no-go for me, I deploy my servers only in Docker.
I tried to create a naive Dockerfile with just installing the libretime .deb but it seems there are systemd dependencies. I overcame these but still libretime hangs after setting the drive path.
I created a gist with the files I have so far: https://gist.github.com/CGenie/60693c4f4f9868d416617b330246925e
If you could comment on that and help me out, I'd much appreciate it.

P.

**Comment by hairmare** [comment]
Hi @CGenie 

Welcome to the community.

Currently we don't have any working .deb files (the installer does everything except use proper packages).

At some point @HaJoHe [wrote Dockerfiles](https://github.com/HaJoHe/docker-libretime) that might help getting you up and running (I didn't compare them to yours though they are probably similar). I'm not sure if they still work.

I've also been working on [Dockerfiles for CentOS](https://github.com/hairmare/centos-docker-libretime) that aim at making LibreTime deployable on OpenShift. Those are far from ready and they might not fit your use-case since you are asking about .deb files.

Cheers
Lucas

**Comment by CGenie** [comment]
I don't need .deb files, it's just that they were my starting point.
I just want to have Libretime dockerized, that's all :)
Thanks for the links will check them out.

**Comment by HaJoHe** [comment]
Hi,
it's a long time, I've never been here. Sorry...
Just for your information... this docker runs now for ~4 months. The docker image can be pulled via 
docker pull hajo/docker-libretime

@hairmare I've just a question about Openshift. How do you intend to offer the streaming?

**Comment by hairmare** [comment]
@HaJoHe I think Kubernetes isn't really in a state where running icecast on it makes sense. I'm hoping for Kubernetes to implement something like the TCP ingress described in https://github.com/kubernetes/kubernetes/issues/23291. Once implemented this will probably take a while to make it's way into OpenShift which is why my setup will most likely take a long time until it really make sense. A quick solution would be to deploy icecast manually without it being managed by OpenShift/Kubernetes.

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/docker-images/17
