### ISSUE TITLE
Liquidsoap complains about missing encoders

### ISSUE THREAD

**Issue by xabispacebiker** [LibreTime/libretime#305]
[dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
[dynamic.loader:3] Could not find dynamic module for aacplus encoder.

Possible Solution?:

> apt-get install liquidsoap-plugin-theora
> apt-get install liquidsoap-plugin-voaacenc

Maybe should be added on install

**Comment by hairmare** [comment]
Those plugin packages don't contain the fdkaac or aacplus. I think debian doesn't bundle the needed plugins anywhere due to patent reasons.

If you don't plan on using either of the encoders you can safely ignore the errors. If you need them you might have success by manually installing liqudisoap from opam as [per the docs](http://liquidsoap.fm/download.html).
