### ISSUE TITLE
[Feature request] Optional use of Silan

### ISSUE THREAD

**Issue by ahpl** [LibreTime/libretime#315]
While silan has its justification, in some cases it is not needed or simply destructive.

This is a request to make the use of silan optional and configurable.

**Comment by hairmare** [comment]
Makes sense. The best place to add this would probably be in the "Settings" >> "Streams" >> "Stream Settings" >> "Global" header.

All in all the whole silan situation is a bit sad because I believe silan deserves a better standing in the code. Due to it being broken and neglected far too long some features fell under the bus. One thing I miss is the wavetable editor thingy that helped users view and revise the silan info.

Given that the hacky workaround of removing silan and ignoring errors from analyzer exists (see this releasenotes for details), this hasn't made it high up the priority list.

I'm currently busy getting playout to AES67/Livewire up and running at my station and I'm not sure when that I can make time to revisit the silan situation. We would for sure welcome any pull requests that make this feature possible.
