### ISSUE TITLE
(Security) Please move 0.0.0.0 services to localhost only

### ISSUE THREAD

**Issue by amavarick** [libretime/libretime#316]
I've installed standalone icecast servers with liquidsoap as well as centovacast servers in the past and was surprised by the open port footprint by libretime.  To improve security, could we alter some of these services by default only to listen to loopback adapter 127.0.0.1?  I'm thinking the only services that should be open would be icecast2, apache2 and exim4?  I would think that airtime-liquids, beam.smp, and epmd should be altered from 0.0.0.0 to 127.0.0.1.  Thank you so much for your time.

netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      16210/apache2
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      14789/epmd
tcp        0      0 127.0.0.1:1234          0.0.0.0:*               LISTEN      16641/airtime-liqui
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      14338/postgres
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      15480/icecast2
tcp        0      0 0.0.0.0:8001            0.0.0.0:*               LISTEN      16641/airtime-liqui
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      16641/airtime-liqui
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      14869/beam.smp
tcp6       0      0 ::1:5432                :::*                    LISTEN      14338/postgres
tcp6       0      0 :::5672                 :::*                    LISTEN      14869/beam.smp

`# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.9 (jessie)
Release:        8.9
Codename:       jessie
`

This link may be helpful for some of the rabbitmq/ehrlang stuff:
https://serverfault.com/questions/235669/how-do-i-make-rabbitmq-listen-only-to-localhost

**Comment by hairmare** [comment]
Hi @amavarick 

Welcome to the community!

The installer is quite bad with regards to that, I fully concur with that. In a nutshell I think we should let the distros do their thing and for the most part have the installer do less. I'm hoping that these kind of issues stop being such a problem once we have proper packages for major distros.

Let me elaborate... Historically the install script was only meant as a simple and easy way to install legacy upstream for customers wanting to give a pre-release version a quick try to see if their issue is fixed. For all other use cases there where packages in repos and everything was running smoothly.  When we took over the build infrastructure was already crumbling and  given there was no real handover, most users have been using the install script for real production installs, in some cases on machines facing the internet without much of a firewall.

That said, yes we need to do something about security, about the ports you mention...

* Liquidsoap
  * 1234: is already running on localhost by default and needs to stay that way as it's only used by the `airtime-playout` script
  * 8001: is the master show input source and needs to be open so you can stream to LibreTime
  * 8002: is the show input source and need to be open for the same reasons as 8001
* RabbitMQ
  * The beam.smp and epmd processes certainly have no business on 0.0.0.0
* EXIM4
  * I'm not seeing exim anywhere in your netstat output, We certainly would not want to have a mail server running anywhere on 0.0.0.0 as part of LibreTime. 

Thanks for posting the link to the ejabberd stackoverflow post. We'll have to watch out when following its recommendations, current OS releases support a later version of RabbitMQ that comes with a major change: the config file format has  changed to yaml from being an erlang file so the installer needs to take that into account.

You can configure auth on the liquidsoap ports through the web-interface, but I'm not sure what the default is so that would need to be checked. We should also recommend using a firewall on 8001/8002 and to configure that fairly restrictive (ie. only allow the studios fixed ip on the master source).

We would happily welcome any pull requests to fix either the installer and/or the docs. I'm not sure when I'll get around to doing some serious security work on LibreTime (including heaps of docs work like letsencrypt, et al.). 

Anyway, thanks for giving LibreTime a go and for raising this important issue!

Cheers,
Lucas

**Comment by amavarick** [comment]
Thank you so much for your detailed and prompt response.

-**8001 8002** - Seeking clarification.  I only use libretime as a scheduler to play content on a reoccurring basis based on day of month.   I do not use any of the DJ live stream functionality or pulling content from anywhere other than this libretime box playlists, (libretime/liquidsoap) to icecast.  With that said, is there a need for 8001/8002 to 0.0.0.0 or could I alter this to loopback adapter?  If so, do you have particular file locations I could try to remediate in test?  If it is needed for my application, would denying any IP but itself from connecting on those ports suffice?

-**RabbitMQ** - You mention changes to yaml from the erlang file... could you provide some hints of file locations so I can research and try to remediate in test?

-**EXIM4** - Before starting libretime install, I apt remove and apt purge exim4.  After install of libretime some dependency re-installed it.  I used an earlier screenshot from testing and didn't capture exim4 on the list.  I probably wouldn't recommend people make this change unless they are sure they don't plan on sending mail outside of the box.  The following are steps I used to set it only to loopback adapter and remove ipv6.
#Remove IPv6 from exim4 and set to loopback adapter
nano /etc/exim4/update-exim4.conf.conf
dc_local_interfaces='127.0.0.1'

-**postgresql** - The listener for this was properly set to localhost but for some reason I wasn't able to remove ipv6 so I modified the postgresql.conf file to listen to loopback adapter IP thus removing ipv6 localhost.
#Remove IPv6 for postgresql
nano /etc/postgresql/9.4/main/postgresql.conf
listen_addresses = '127.0.0.1'

I'm not a programmer but have patience, time and can follow logic.  If I can get some of those helps for file locations, I can start testing.  May be able to post merge request or just respond back to this with my solution to help further the project.  I was able to implement https with my icecast streams and get let's encrypt working with cron to update my certificates for icecast.  I posted my let's encrypt scripts on github to help others.

**Comment by hairmare** [comment]
You can safely change the liquidsoap ports to only listen on localhost if you don't plan on using the master and show sources. As far as I can tell it's configuration is hardcoded at the moment:
https://github.com/LibreTime/libretime/blob/b5b24f34641490599851c7b5039bfc25cccd94ca/python_apps/pypo/liquidsoap/ls_script.liq#L16

Sorry about the RabbitMQ yml thing. It turns out I was confusing ejabberd with RabbitMQ, there aren't any changes in RabbitMQs config files so you link should be valid for that.

I think opening up exim to the world is a debian thing. It seems that this can be overridden using debconf as noted in [this stackoverflow answer](https://serverfault.com/a/544725).

Your PostgreSQL change looks sensible, I'm neither much of a PostgreSQL or Debian guy so I can't really tell if Debian has a simpler way to do this.

The letsencrypt scripts you mention sound interesting. Some of our less technically minded have had issues with getting TLS to work. AFAIK most of them where focused on apache rather than icecast.

Feel free to ask if you need any pointers. We're happy to help!

**Comment by amavarick** [comment]
I created a config file for RabbitMQ /etc/rabbitmq/rabbitmq-env.conf
and entered variables in there but now have...

127.0.0.1:5672          0.0.0.0:*               LISTEN      426/beam.smp
0.0.0.0:25672           0.0.0.0:*               LISTEN      426/beam.smp

So there is something else still conflicting?

Looking through the installer files it appears like this is the file that would determine the setting?
/root/libretime/airtime_mvc/build/airtime-setup/forms/rabbitmq-settings.php
or after install:
/usr/share/airtime/php/airtime_mvc/build/airtime-setup/forms/rabbitmq-settings.php

Should something be altered on these files to make it 127.0.0.1 instead of 0.0.0.0?

**Comment by hairmare** [comment]
The `rabbitmq-settings.php` seems to take it's defaults from the example conf here:

https://github.com/LibreTime/libretime/blob/b5b24f34641490599851c7b5039bfc25cccd94ca/airtime_mvc/build/airtime.example.conf#L114

It shouldn't be reconfiguring RabbitMQ as far as I can tell. The install scripts also relies on the distro to install RabbitMQ and only manages user permissions on the `/airtime` RabbitMQ vhost.

It looks like you've sucessfully removed the epmd listener on 0.0.0.0 but missed the beam part. Did you configure RabbitMQ using a config file as described in the Stackoverflow? Maybe the the [RabbitMQ docs](https://www.rabbitmq.com/networking.html) contain a way that works?

You should probably also consider running a local firewall that closes all incoming ports and only open what should actually be exposed. This adds an additional layer of protection for the whole system and is the recommended way to configure a system you expose to any open networks.

**Comment by amavarick** [comment]
SUCCESS!  So I figured out how to get the epmd and beam.smp services bound to localhost adapters only.  Developers please consider using these instructions as a starting point to bind to loopback instead of public IP.

It came with great travail because I had the settings correct BUT there apparently is a known bug with epmd and binding only to an IPv4 adapter for Ubuntu.   I run a rather comprehensive script to harden my OS before installing software.  This involves removing IPv6.  A specific sysctl setting disabling IPv6 apparently causes the epmd service not to start.  Details of the bug can be found:
https://bugs.launchpad.net/ubuntu/+source/erlang/+bug/1374109

Steps to bind epmd and beam.smp services only to IPv4 localhost.  epmd will be bound to both IPv4 and IPv6.  Modify the rabbitmq-env.conf file to match below.  Create the rabbit.config file matching the file below.

```
#cat /etc/rabbitmq/rabbitmq-env.conf
# Defaults to rabbit. This can be useful if you want to run more than one node
# per machine - RABBITMQ_NODENAME should be unique per erlang-node-and-machine
# combination. See the clustering on a single machine guide for details:
# http://www.rabbitmq.com/clustering.html#single-machine
#NODENAME=rabbit

# By default RabbitMQ will bind to all interfaces, on IPv4 and IPv6 if
# available. Set this if you only want to bind to one network interface or#
# address family.
NODE_IP_ADDRESS=127.0.0.1

# Defaults to 5672.
NODE_PORT=5672
export RABBITMQ_NODE_IP_ADDRESS=127.0.0.1
export ERL_EPMD_ADDRESS=127.0.0.1
export RABBITMQ_CONFIG_FILE="/etc/rabbitmq/rabbit"
```

```
#cat /etc/rabbitmq/rabbit.config
[
    {rabbitmq_management, [
        {listener, [{port, 25672}, {ip, "127.0.0.1"}]}
    ]},
    {kernel, [
        {inet_dist_use_interface,{127,0,0,1}}
    ]}
].
root@stream3:/etc/rabbitmq# cat /etc/rabbitmq/rabbit.config
[
    {rabbitmq_management, [
        {listener, [{port, 25672}, {ip, "127.0.0.1"}]}
    ]},
    {kernel, [
        {inet_dist_use_interface,{127,0,0,1}}
    ]}
].

```

```
# netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      839/apache2
tcp        0      0 127.0.0.1:4369          0.0.0.0:*               LISTEN      668/epmd
tcp        0      0 127.0.0.1:1234          0.0.0.0:*               LISTEN      368/airtime-liquids
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      560/sshd
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      389/postgres
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      701/icecast2
tcp        0      0 0.0.0.0:8001            0.0.0.0:*               LISTEN      368/airtime-liquids
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      368/airtime-liquids
tcp        0      0 127.0.0.1:5672          0.0.0.0:*               LISTEN      861/beam.smp
tcp        0      0 127.0.0.1:25672         0.0.0.0:*               LISTEN      861/beam.smp
tcp6       0      0 ::1:4369                :::*                    LISTEN      668/epmd

```

**Comment by hairmare** [comment]
In the meantime I started work on rewriting the [preparing the server](http://libretime.org/manual/preparing-the-server/) chapter of the manual. It now strongly recommends that you run a firewall and also has some initial pointers on RabbitMQ setup.

I believe it makes sense to update the docs with your setup as it's certainly a standard tasks given most admins won't run LibreTime against a full RabbitMQ cluster.

Please consider adding your example to the [relevant section](http://libretime.org/manual/preparing-the-server/#rabbitmq-hostname) on RabbitMQ hostnames. You can create pull requests to update the docs from any page in libretime.org using the "Edit on GitHub" link at the upper right corner of the page. There is a markdown editor with preview feature and you can do everything needed for such updates directly from the GitHub web interface.

Let me know if you need any help or if you would rather let someone else do the docs change. Thanks for contributing in any case.

**Comment by Robbt** [comment]
So I think the action item here is to lock down rabbitmq to by default only accept local connections, as the rest of the open ports are pretty much required. 

It probably makes sense to do this with the install script under the assumption that people will be running the install script as a primary means of installing libretime on a stand-alone box with limited sysadmin knowledge. I agree that packages and/or docker containers might also be good alternative solutions but we are still working on these.

@paddatrapper does the current deb package leave rabbitmq ports open to the internet or does it close them.

**Comment by paddatrapper** [comment]
The deb leaves RabbitMQ settings to the rabbit-mq ubuntu package, so it listens on localhost only by default

**Comment by Robbt** [comment]
Ok, I'm not 100% sure that we need to make rabbitmq only listen locally but it might be a good idea, especially if people don't follow the instructions to change the default rabbitmq password on the install screen.

**Comment by Robbt** [comment]
If we implemented this in the install script would it transfer automatically to the debian package based install, ie what is the relationship between the install script and the debian package ?

**Comment by paddatrapper** [comment]
I hand pick sections of the install script and put it in the deb installer's postinst script. I need to do some digging around why the RabbitMQ server listens on 0.0.0.0 by default in Debian. That seems to be a bug to me, so will file one against rabbitmq-server if I can't find explanation

**Comment by Robbt** [comment]
My suspicion is that rabbitmq is in general used for inter server communication of messages, but in our case we are using it exclusively for internal communication between processes.

**Comment by paddatrapper** [comment]
So you can set the interface that RabbitMQ listens on in /usr/share/rabbitmq/rabbitmq-env.conf

The debian packaging has [an example](https://sources.debian.org/src/rabbitmq-server/3.7.18-1/debian/rabbitmq-env.conf/)

**Comment by jooola** [comment]
The documentation recommends installing a firewall and lists the ports required by LibreTime. This should prevent having external access to services that might listen on 0.0.0.0.

I would not solve this other than with documentation or links to external documentation. Closing as resolved.
