### ISSUE TITLE
Feature: add shuffling smart blocks in Playlists 

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#319]
So the idea is in title.
add the button in playlist properties to shuffle smartblocks inside playlist, every time while it adding to the show.
Or make it simpler, make some timer to shuffle it every hour or so.
<img width="542" alt="2017-10-06 21 18 59" src="https://user-images.githubusercontent.com/25418594/31292468-3d759bb4-aadc-11e7-8600-fc4e03ffc655.png">

**Comment by Robbt** [comment]
Ok, are you talking about shuffling static smartblocks ? Or shuffling all of the contents of the playlist ? Or shuffling only the smartblocks inside of a playlist and leaving non smartblock content unshuffled ?

**Comment by frecuencialibre** [comment]
i'm closing this for now since it is a feature request that has received no response in more than a year, and  we're currently focusing on preparations for a beta release. _similar_ functionality can be achieved using autoloading playlists, which can shuffle smartblocks upon loading them into shows. however, dynamically shuffled smartblocks currently cannot be nested within other smartblocks.
