### ISSUE TITLE
We really need a forum

### ISSUE THREAD

**Issue by squiggleuk** [LibreTime/libretime#320]
Hi All,

I know this topic came up a while back, and some people maybe went the wrong way about trying to make it happen quickly, without proper planning and thought. I am now re-raising this issue with the LibreTime community, as I really feel that it will help us grow and continue to move the project forwards.

- There is currently nowhere for general questions directed at the project or community. This could be questions regarding usage or installation etc. I'm sure like myself many people do not feel comfortable asking a question by raising an issue, which I believe is the current recommended way. As such, we may never hear the voice of some people.

- Using issues to handle general questions from the LibreTime userbase is certainly not scaleable, and will only make it harder for developers to focus on actual outstanding issues. Also, with a question, it's much harder to determine when a question is resolved and the issue can be closed. As such, we're going to end up with a ever-increasing number of open issues, fogging this real ones that are open.

- I've seen many other Open Source projects using Google Groups as a forum. This way, we don't have a specific individual responsible for the financing and operations of a platform. It also reduces the risk of a person in that position terminating this service and its data out of the blue one day. Multiple LibreTime maintainers could act as admins for this. I'm not ruling out any other platforms however. Maybe if we decided it's something we'd like to move forward with, we have a another discussion on how/where.

I'd like to ask all members, developers, maintainers, users, potential-users, and those-too-shy-to-ask-questions-in-issues to let us know if you think this would be beneficial for the project/community going forwards?

I'm really struggling to see any negative points to this, providing it is implemented with the project as it's core focus.

**Comment by Robbt** [comment]
Previously I was in favour of the idea of creating a forum if created with enough support from the current community. I had suggested that we apply for free hosting from discourse. We could try that but I'd want to see at least a handful of people on here who would participate in a forum and think its a good idea. We could apply, even though our stars are far below their 2,000 recommended star count even if you add the almost 500 from Airtime. If there is a consensus on this I could apply or we could set-up our own discourse forum hosted.

 I'd prefer to stay away from google groups but I'm not totally opposed to the idea if other people think that is the best. We could also create a subreddit as another cheap way to facilitate an alternative venue for discussion.

**Comment by squiggleuk** [comment]
Not many people shouting here in agreement...  :/

Maybe we do try striking up a conversation with discourse to see if they will host for free though? We're new, but are moving forward with an awesome app.

I feel like self-hosting it wouldn't be a good idea, as it will mainly rely on a single person

**Comment by amavarick** [comment]
I love the idea of a forum.  I'm not a developer and would prefer having a separate place to submit user/operation type questions rather than posting a bug fix or feature request.  Developers here gladly have us post our questions under issues and I'm thankful but seeing so many active "issues" may detract people from using this product who could assume it is buggy because of all the open "issues."  I also agree with something like google groups where cost and management of the forum is mitigated.

**Comment by squiggleuk** [comment]
Linking #336 as @astrotumult mentions similar

**Comment by squiggleuk** [comment]
Linking  #148 as @ghost asked the same question

**Comment by squiggleuk** [comment]
@Robbt - Have you already engaged in conversation with discourse previously? Should we just try our luck and see if discourse are willing to take us on board?

**Comment by Robbt** [comment]
I have yet to engage them. I will fill out the form and link to this issue and we can see if they will accommodate us even though we don't quite meet their criteria.

**Comment by ronstep** [comment]
Dont we already have a website, why not just put a open source forum up on that

just a thought, I would really like a forum as well.

regards and respect to all

**Comment by Robbt** [comment]
The website is basically mkDocs fed via the docs section of our Github repo. I'm going to fill out the discourse request and see what happens. If they don't approve us we can consider hosting our own or choosing another means of providing a forum or forum-like functionality.

**Comment by Robbt** [comment]
I submitted a request to Discourse. I'll update everyone if and when I hear back from them regarding a decision.

**Comment by Robbt** [comment]
We have been approved for a free hosted forum by Discourse. Now we need to decide how to set it up and define how it will be used vs. Github. My idea is that basic troubleshooting of installs and what not could go into the forum and then turned into issues when the specific issues are discovered. Also obviously posts about loose ideas that aren't well formed into specific feature requests or implementation could go there as well.

We can import specific issues to Discourse as well through a tool. So does anyone want to go through and flag the issues we'd like to transition to the forum ? Also I'd like to hear from @hairmare on his thoughts on implementing this since it is kind of a new development and there wasn't a true consensus before on setting up a forum. The last thing I want to do is bifurcate our community into developers and users as I think that was an issue confronting the project when it was still Airtime. Arguably the bigger dynamic there was a  probably a disconnect between paid employees and community members. 

Anyways, I'll need to setup the discourse account with my personal info and then they will set it to be free etc and we can move in once we have the DNS pointed for discourse.libretime.org and some decisions made about how we set it up. 

Vue.js is another opensource project that uses Discourse for their forum and github for their bug tracking and feature request. Here are their guidelines "For questions and support please use the the official forum or community chat. The issue list of this repo is exclusively for bug reports and feature requests." They also have a form to submit for their bug requests - https://new-issue.vuejs.org/ Setting up something like that might be useful. I'll proceed with setup as we open this new chapter in LibreTime's history.

**Comment by squiggleuk** [comment]
This is fantastic news. Thanks for submitting the application @Robbt 

I guess troubleshooting & questions are the kind of issues we'll be moving there, then like you say, will potentially end up coming back to an issue/feature-request once clearly defined.

Shall we add a new label 'discourse' or similar so we can start marking issues to migrate?

**Comment by Robbt** [comment]
That sounds like a plan, discourse or just forum. 

Right now for categories I'm thinking we should setup.
Get Help - a place to get help regarding your libretime set-up or questions regarding usage.
Documentation - for sharing rough tutorials - how-tos before they get added to the official docs.
Community - talk about your station, the LibreTime community or anything else
Development - talk about the backend, programming and other ideas 
Radio Talk w/ Sub Categories - Music & Talk Radio - a place to share non software related radio stuff and just discuss various syndicated programs or what not (not sure maybe this could go under Community)
One thing I've seen setup is specific categories for speakers of other languages but I'm not that is necessary at this point.

Feel free to provide feedback those of you who are enthusiastic about the forum idea.

**Comment by hairmare** [comment]
@squiggleuk Thanks for pushing the agenda on this.

@Robbt I'll take some time to dump my thoughts/concerns later this week, my first priority is tagging 2.0.0-alpha.3. Apart from the bifurication issue you mentioned I don't see any problems.

**Comment by squiggleuk** [comment]
I feel like a fool...
 ...but, how to you add a label?

**Comment by Robbt** [comment]
I'm not sure if it is something that anyone can do w/o permissions. For me this functionality is available on the right sidebar and you click labels but it is probably because I'm an owner of the project that I have the ability to tag other peoples posts. 

The forum is setup on a temporary URL but will be changed to discourse.libretime.org when we are ready. I think the things we should do before transitioning are move over the posts and put something in the readme to let people know about the forum and direct them there to get help. If anyone wants to help moderate the new forum let me know. We should probably have some basic guidelines (anyone have suggestions) about code of conduct etc as well but maybe that is already covered by the C4.

**Comment by xabispacebiker** [comment]
@Robbt  Count on me, I can help in my spare time to moderate the forum.

**Comment by xabispacebiker** [comment]
Can discourse be installed on a dedicated server? If so, I can provide some space to install it on one of the servers I got online.. if not .. in my opinion we should use another open sourced forum.

**Comment by Robbt** [comment]
@xabispacebiker We already have free hosting as an open-source project from the creators of Discourse so no need to deal with the server admin/setup etc on our own. At this point we just need to ask them to point the DNS. I'm adding discourse label to the posts that I think are questions vs. identified bugs/features. I don't know how the import functionality works exactly yet but I'll test it. We will enable logging in via github.

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/we-really-need-a-forum/14

**Comment by Robbt** [comment]
Ok, so I tried the github import and it appears to have closed the issues automatically that I had marked with the discourse tag. The only issue remaining is that we are on a temporary URL because I wanted to get it setup without waiting for the DNS changes. The site URL will change to http://discourse.libretime.org and when it does I'll need to modify the comments that were posted when the issue got closed so they don't post to the old URL. Once the site URL change is made I'll also need to update the Github application URL to work with discourse.libretime.org but in the meantime everyone should be able to login and post on the forum. At some point we can have this conversation over there but I wanted to give everyone a heads up because I didn't realize importing the issues would close the issues automatically on github.

**Comment by Robbt** [comment]
They have moved faster than I thought to my e-mail so we are now live with our own Discourse forum - I'm going to close this again so we can follow up on http://discourse.libretime.org/t/we-really-need-a-forum/14 and discuss any specifics. I really want some other people to sign-up and start using the forum because the import script posted everything under my user name (with references to the original posters). So yeah this can be marked closed as we have a forum, so let's use it. If anyone disagrees with porting any of the issues ie they think they still needed to be open and on github then feel free to reopen them on here.

**Comment by squiggleuk** [comment]
Trying to login via github but get the following...

Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?

**Comment by Robbt** [comment]
Hmm, I was able to login with my github account. Did it pop up with the request for authorization from github screen ?

**Comment by squiggleuk** [comment]
No... maybe it’s because I’m trying via iOS... will have another bash in the morning!

Happy to moderate as well once I’m in!

**Comment by Robbt** [comment]
Cool yeah Safari could be blocking the pop-up window, that should show up when you click login with Github. Once you authorize it though it should be relatively simple and allow you to login if you are logged into github already.

**Comment by xabispacebiker** [comment]
I am a bit confused.. Arent we supposed to use the discourse forum for troubleshooting libretime ? I see many new issues open in github

**Comment by hairmare** [comment]
I answer them out of courtesy and try to point them to the discourse from time to time. Maybe we should create an issue for changing the "File a support ticket" link in UI to "Get more help" and pointing it to the discourse. I think the sad tape screen help button also points to the issues page.

**Comment by JohnnyC1951** [comment]
[Try this](http://web-radio-support.websitesinternational.net)

**Comment by squiggleuk** [comment]
Maybe the location of the forum isn’t that clear - maybe a clear link from the main readme page and website to direct folk there?

**Comment by hairmare** [comment]
We already have [this](https://github.com/LibreTime/libretime#support) but some prominent placement on libretime.org as well as in the ui itself will probably help a bit.

**Comment by Robbt** [comment]
Yeah, I think the sad tape linking to the forum would be a good step.
I also think coming up with a better set of guidelines for submitting a PR would make sense.
We could also close the issues once we provide a nice response and point them to the proper guidelines for submitting an issue and/or the forum. If people prefer to chat on the comments of a closed issue that would work too.

**Comment by JohnnyC1951** [comment]
I would also like to see an official live chat room or google group chat or something where folks that are actively developing/installing could hang out and help newbies/whatever. It can be very frustrating to wait for a day or so when one is stuck.

**Comment by Robbt** [comment]
I think the easiest thing to setup in terms of standard based is a #libretime channel on freenode.net IRC network but I'm not really a big IRC fan. I think Gus setup a Slack install but I personally would rather not create new diversions. I think the big challenge is that there wouldn't be anyone around even if we had a chat network, at least not from the people who would be able to answer a question.  So creating a chat network probably would add to the frustration vs. alleviate it. I know that was the case with airtime's IRC channel.

**Comment by jooola** [comment]
I wanted to get in touch with one of the Libretime maintainers, but I didn't found any IRC channel. Also discourse is a bit overkill for questions and ideas to discuss.

Is there any plans to create the IRC channel ? Another option could be to create a Matrix channel and bridge them together (IRC <-> Matrix).

If not how could I we get in touch ?

**Comment by gusaus** [comment]
Hi @jooola We should have chat.libretime.org (re)opened up shortly https://github.com/LibreTime/libretime/issues/538
