### ISSUE TITLE
Composer needs unzip on initial install

### ISSUE THREAD

**Issue by amavarick** [LibreTime/libretime#323]
Recommendation to install zip unzip php7.0-zip as re-requisites before attempting composer install.  

Composer (version 1.5.2) successfully installed to: /usr/local/bin/composer

When installing on Ubuntu and Debian recent versions, I noticed composer coughed with installing packages because I did not have unzip installed.  Rather than installing it from repo, it downloaded and performed a manual installation?  My concern with manual vs repo install is that it may not perform updates using apt in the future?

I was able to remove the errors by performing this before installation:
apt install -y zip unzip php7.0-zip

Suggest adding them as pre-reqs before installing libretime?

**Comment by Robbt** [comment]
Is the php7.0-zip required ? If not we could probably add unzip and zip to the apt install script. I'm not sure if we have version specific apt installs yet and I think 14.04 is still using Php 5 by default.

**Comment by amavarick** [comment]
When I performed the installation I believe unzip was the required and zip and php7.0-zip were dependencies of unzip for my install.

**Comment by amavarick** [comment]
I reinstalled... php7.0-zip was NOT needed.

**Comment by hairmare** [comment]
The composer packages are different from apt packages. Like most of the LibreTime install they can't be managed by apt for the time being.

Composer was installing the same packages it would have installed with unzip or php-zip installed. The message is just a warning that composer logs when it uses manual packages (ie. git repos) it's there because that they are rather slow compared to zip files.

This should only really affect source installs. The packaging script on vagrant uploads a tarball that contains all the needed composer dependencies. This means composer doesn't have to re-download any of them.

Maybe explaining this in the developer docs is the easy way out?

**Comment by amavarick** [comment]
How about just adding unzip to the libretime/installer/lib/ files?

**Comment by Robbt** [comment]
Yeah it should be fairly simple to add unzip and zip to the installer/lib/*.apt package lists if that solves the problem and simplifies the setup. Feel free to put in a PR.

**Comment by amavarick** [comment]
Created Pull request #332 
Added zip and unzip to the requirements files found in /installer/lib.

This is my first time creating a pull request with multiple commits.  I did it by creating a fork, making changes in fork and then creating pull request.  Hope I did it right!

**Comment by amavarick** [comment]
Merge was completed, I tested on Ubuntu 16.x, worked fine.  Closing issue.

**Comment by hairmare** [comment]
Awesome, Thanks!
