### ISSUE TITLE
Problem: There is no scrollbar for the new show dialog when it overflows the browser window.

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#338]
This has been driving one of our volunteers crazy because the functionality with Airtime.pro is different than LibreTime. 

Basically the New Show left dialog overflows without any obvious means of scrolling. (I've found if you scroll on the far right of the browser window it works after you scroll past the Calendar)

The Calendar has its own scroll bar as well which further complicates it.

Here are some screenshots displaying the problem.

![noscrollbarinnewshowwindow](https://user-images.githubusercontent.com/760739/31684995-8c7ce9c6-b34f-11e7-8754-0de649d6cf8e.png)

**Comment by hairmare** [comment]
Is this on all browsers? It might be OS/browser specific. That part of the frontend is in dire need of a cleanup from a dev POV as I remember from a more than one attempt to tackle the datatables/calendar integration in the actual js ui parts.

**Comment by Robbt** [comment]
This is on all browsers aka Firefox and Chrome. Haven't tested it on IE. My guess is that SourceFabric fixed it after the code we forked from as they did with numerous other small bugs.

As far as the front end goes. It is indeed a mess, aside from just the various libraries that have been hacked in numerous ways, the jQuery code is all over the place in more ways than one. It appears that when they started developing the Podcasts app they switched over to Angular 1 (just for that features functionality). The rest of the site is coded with jQuery. When I was coding the modification to the Smartblock the jQuery code I had to write was messy in comparison to using a modern javascript framework. 

I have been developing another project from scratch using Vue.js which is a very clean component driven framework, but rewriting the whole stack in another framework might be useful but would also best coincide with fixing the dependency on Zend 1 CMS as well. Part of the problem was I never bothered to learn jQuery and the haphazard way the libraries etc are organized doesn't make contributing new code very much fun.

Is there any way I can contribute to the code cleanup ? I know you had a branch but it is tricky to step into someone elses work in progress espcially on something like this. 

Also this is kind of a priority for me because the user is unable to move forward with LibreTime because they can't find any other way of scrolling. Every time I've tried scrolling the browser window on the far right works but evidently it isn't an option for them.

**Comment by hairmare** [comment]
My last try is [here](https://github.com/LibreTime/libretime/compare/master...radiorabe:dev/js-refactor) I never pushed the changes that really involved datatables as they where extremely explorative and very much in need of rebasing (ie. everything broke). If you think my change set might fix things or help as a starting point my toes wouldn't feel stepped upon. 

Currently I need to get #334 merged so I can do the alpha-3 release. I'd rather hold off on large changes to the frontend until after. 2.0.0-alpha.3 is at the stage where it only needs some release note polishing and it's good to go as far as I'm concerned (I also want to include #274, It's bascially LGTM, I just got distracted during testing). I also might have some vagrant/docs PRs that might make sense to include in the next tag.

Also, tagging @smlz since he also did some vue.js based stuff we are currently running. Maybe vue.js is the way to go for #2.

**Comment by Robbt** [comment]
Ok, so the user was able to find the 2nd scrollbar to the right as a workaround so this is not really as high a priority for me. I think where I'd want to start with untangling the javascript mess is just inventorying exactly what we are using, where and why. Then we could look at each of the specific hacks and see if there are workarounds that would allow us to use the bare library but still have the same functionality or at least not break anything. I might do this in a wiki page if I find the time/inspiration. 

In regards to Vue.js it could be a good front-end javascript framework for us. I might play around with mocking up some of our pages w/ Vue components.
