### ISSUE TITLE
Updating process

### ISSUE THREAD

**Issue by Zopokx** [LibreTime/libretime#341]
I'm just trying to update to avoid pypo issue.

I'm pretty new here and I don't know what  airtime-media-monitor is. It is still used in libretime?
![captura de pantalla de 2017-10-18 15-23-17](https://user-images.githubusercontent.com/1054576/31720988-67e7f3f2-b418-11e7-85b5-aef85ab39281.png)

PS: Why not make an auto-upgrade button?

**Comment by Robbt** [comment]
Airtime-media-monitor is from airtime. You can ignore the failure to stop, this is probably just because the script is trying to disable it completely.

Our goal as far as upgrades go is to ultimately create packages for the different distributions that will handle this. There are too many system level processes to integrate a secure upgrade path from the web interface as far as I know. Perhaps it could be done but it's not high on our priority until we get out of alpha.

**Comment by hairmare** [comment]
I can confirm that the failure to stop an airtime-media-monitor service isn't fatal and can be safely ignored. It's there to help users upgrading from a legacy install done with the scripts.

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/updating-process/16
