### ISSUE TITLE
nginx support

### ISSUE THREAD

**Issue by isAAAc** [LibreTime/libretime#345]
Hi, 
is someone working on the nginx support for libretime ?
i would run libretime in a yunohost server , but nginx is needed

thw for your answers ;)

**Comment by Robbt** [comment]
There is no reason why nginx shouldn't work with LibreTime if you copied the settings from the default Apache setup but there is no support with the installer at this point.

**Comment by isAAAc** [comment]
i need to check specificities of the nginx *.conf to go ahead on my request, 
as far libretime isn't packaged for yunohost, i need to use a my_webapp tool, 
the empty my_webapp.conf for nginx is like that (webapp name is called airtime, but it could be something else) : 

```
root@krashboyz:/etc/nginx/conf.d/stream.krashboyz.org.d# more my_webapp.conf
location /airtime {
    alias /var/www/my_webapp/www/;

    # Default indexes and catch-all
    index index.html index.php;
    try_files $uri $uri/ /airtime/index.php?$args;

    # Prevent useless logs
    location = /airtime/favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /airtime/robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    # Deny access to hidden files and directories
    location ~ ^/airtime/(.+/|)\.(?!well-known\/) {
        deny all;
    }

    # Execute and serve PHP files
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_pass unix:/var/run/php5-fpm-my_webapp.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param REMOTE_USER $remote_user;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $request_filename;
    }

    # Include SSOWAT user panel.
    include conf.d/yunohost_panel.conf.inc;
}

```

i tried the apache-to-nginx tool to convert the apache conf, but it doesn't work
, i'm not enough skilled in apache/nginx to find the good syntax by myself :/

**Comment by Robbt** [comment]
Hmm, this might be a tall order because LibreTime is much more than just a webapp, it also involves IceCast, Liquidsoap, RabbitMQ and several python based subroutines that all need to be installed and configured to work together. So you would basically need to rewrite the installer to work with the yuno host app packaging system - https://yunohost.org/#/packaging_apps and even then it probably wouldn't work out of the box without modifying some setting somewhere along the line. I'd suggest that this project is probably not feasible without a lot of time learning the syntax of YunoHost packaging.

Another cool self-hosted project SandStorm.io would probably suffer from the same problems and even more so as it doesn't really expose the ports to a project to the outside world.

If you are looking for a cheap way to host LibreTime it might make more sense to either pay for a VPS or setup a Linux server with some old x86 hardware. Although I do know that people have been semi-successful in running LibreTime on a Raspberry Pi.

**Comment by isAAAc** [comment]
yep you're right, 
resquest for a ynh package is on the way, 
i already have a running icecast (out of the sso) on this server https://stream.krashboyz.org:8001 , 
that's for what libretime could be great to work with, 
RabbitMQ looks running since my last night tries,
i think the real problem is the *conf file for nginx, 
i'll refer to this ticket in my request for yunohost, 

thx for your time ;)

**Comment by Robbt** [comment]
Ok, so I'm going to mark this as something we aren't planning on supporting at this time, that being nginx support. If someone wants to reopen it and/or work on this feel free to reopen this. But I'm going to close it for now as it doesn't refer to a particular issue and the request seems to be centered around a specific hosting environment yunohost that at the moment we don't have the resources to consider supporting.
