### ISSUE TITLE
Changing and adding the storage folder

### ISSUE THREAD

**Issue by tuktukvlad** [LibreTime/libretime#348]
Hi!

Tell me how to change or add a second media folder. 
In the Airtime was the function of adding folders, but here it is not present.
I have two sections on the server, how to make sure that both are at work?

Thanks

**Comment by xabispacebiker** [comment]
Watched folders functionality has been removed.
See issue https://github.com/LibreTime/libretime/issues/70

**Comment by hairmare** [comment]
Some initial work on restoring the feature has been done in #111. This is certainly on the roadmap so you can most likely expect it to drop once we reach beta releases. I can't promise an ETA though.

**Comment by leonardpg** [comment]
Is the location of the media folder in a config file somewhere and if so is it editable? I want to change the default media folder to a mounted volume.

**Comment by Robbt** [comment]
This isn't currently configurable via the web interface, although I think the web-based installer allows you to set it up. It could probably be added or modified via the database. Although we haven't tested network based mounted volumes, they should work. The latency might be an issue but most likely not as liquidsoap copies all files onto a local directory for playback. If there was a disruption in connectivity though it would likely result in dead air.

**Comment by Robbt** [comment]
I'm going to close this as it is basically a duplicate request for functionality that currently isn't implemented (import folder). Also with regards to changing the storage folder via the web interface. This seems like it would be a bad idea and should only be done initially during setup or by manually copying files as otherwise it would orphan a lot of files or require copying a potentially large number of files.

**Comment by hairmare** [comment]
> Although we haven't tested network based mounted volumes, they should work.

I'm using a GlusterFS backed volume since analyzer doesn't run on the same server as the web-UI in my enterprisy deploy. Robb was spot on with his analysis of how liquidsoap isn't affected.

> I'm going to close this as it is basically a duplicate request for functionality that currently isn't implemented (import folder). 

I'll try to put some work into this after the next release since it seems to be holding back quite a few users. The next release should be coming soon, I just haven't found the time to do some serious testing on all major distros yet.
