### ISSUE TITLE
Smart Blocks overfill hour

### ISSUE THREAD

**Issue by jerry924** [LibreTime/libretime#357]
I have a problem when using smart blocks in that they are not smart enough to find songs that fill hour exactly or close as possible.

The problem is when the next hour starts, whatever is oversubscribed just gets chopped and it is very annoying to listeners.

Here is how I manually work around this and I think we can improve smart blocks to do this automatically.

1) I have several tracks that are in an "Ambient Sound" genre. These are tracks that are just some ambient sounds that can easily be chopped without affecting the listeners.  Imagine noise of waves crashing on a beach, or city street noise, or even very light elevator-like/simple music which doesn't sound bad to get cut off randomly.

2) We have enough music that there is a variety in track lengths (over 1000 tracks).

3) If I create a smart block for 60 minutes, sometimes it is 56 minutes, sometimes it is 63 minutes, etc. The problem is the quiet time for 4 minutes or the chopped off song that had 3 minutes left to go in it.

4) The steps I follow manually to solve this:
      A) fill 60 minutes with a smart block
      B) if time remaining < 30 seconds, add ambient sound track - done
      C) if time remaining > 2:30, find a music track that is between (remainingtime-30s) and (remainingtime), but closest to (remainingtime) without going over and add it there and add ambient sound track to the end of that - done.
      D) if time remaining is > 30 seconds and < 2:30 then I delete last TWO tracks and repeat (B),(C)
      E) if time is oversubscribed, delete last track and check (B),(C),(D) above.

at step (C), 80% of the time I have a track that perfectly fits so all of my hours are +0.  The problem is when I use a smart block on a linked show and each link is derived with different content, it is very hard to go and manually fix them all. 

Given that I have a formula/process for this, seems like it could be coded into the smart block creation code just like this.

Smart block would need a new input which is a track or other smart block that spits out one ambient sound/choppable track. This setting would need to be stored in the smart block definition and used to fill in any < 30 second time at the end of a smart block.

**Comment by hairmare** [comment]
I like the idea of choppable tracks. I can see an additional use case for them in combination with the podcast download thing. The thirty second window would need to configurable for that case and step A might produce an empty playlist.

If I recall correctly the actual scheduling code gets triggered some time before the smart block needs to be evaluated by a request to the mvc which is usually done by the playout daemon on a regular base. This makes hacking on the scheduling code a bit inconvenient. I usually shunt some code in my working copy to make hacking easier.

**Comment by jerry924** [comment]
@hairmare  - my idea in working on hacking this was to modify **public function getListOfFilesUnderLimit()** and update the logic as described above.   This would give me a list back from my smartblock in generateSmartBlock() that already had packed file list fitting perfectly with the choppable track at the end.

Do you think this is the right place?  I assume every time generateSmartBlock is iterated over a linked show this getListOfFilesUnderLimit() is called again to get the new random list of files.

**Comment by Robbt** [comment]
Yeah that would most likely be the function to hack. With a little thought it might be possible to make something that is user configurable and could be added to the codebase. This kind of goes along with the modification I did to prevent the smartblock from adding tracks that went past the time limit. To go along with the automatic playlist I was thinking that there could be a smartblock entry that reads the time left in the show and then tries to fill that. This is a tricky problem that there isn't a super obvious answer too. I think that what you've proposed at least makes sense and solves the problem. We are doing something similar with musical bridges after our shows but our solution needs tweaking.

**Comment by Robbt** [comment]
So I have started work on this in relation to a grant we received at WCRS. I'm going to use this issue as the place to process some of my thoughts with regards to the solution I'm crafting. I started out putting up stuff in the [Wiki](https://github.com/LibreTime/libretime/wiki/Smart-Block-development) but I'm going to transpose the remaining time stuff here.


This is potentially a useful way to make a smartblock repeat until it fills a show thus enabling variable length primary shows without dead air.

The challenge is getting the this code https://github.com/LibreTime/libretime/blob/ecac7947477243bc92304307d5d7bdd26d0b47de/airtime_mvc/application/models/Scheduler.php#L791-L795 in Scheduler to interact with the show instance. It calls retrieveMediaFiles which branches and eventually calls getListOfFilesUnderLimit (for adding smartblocks) and it gets its time or item length from getListofFilesMeetCriteria: https://github.com/LibreTime/libretime/blob/ecac7947477243bc92304307d5d7bdd26d0b47de/airtime_mvc/application/models/Block.php#L1470) So the question is how can this code:https://github.com/LibreTime/libretime/blob/ecac7947477243bc92304307d5d7bdd26d0b47de/airtime_mvc/application/models/Block.php#L1604-L1614 be modified to access the show instance that it is scheduling inside of and set a limit based upon the time remaining in the show. It would be simple enough to add a new modifer that says something like remaining but it is a question of how this modifier would determine the amount of time remaining in a show when it is called. 

Here is the chain of functions to see if there is a way to add or determine context here. 
**showInstance::addPlaylistToShow** -> **scheduler::schedulerAfter** -> **scheduler::insertAfter** -> this iterates over foreach mediaItem and runs **scheduler::retrieveMediaFiles** ->  which branches on type and for dynamic smartblocks it runs **block::getListOfFilesUnderLimit** -> this iterates until it meets a item or time limit of items it receives from -> **block::getListOfFilesMeetCriteria**

**$scheduleItems** contains the instance_id as the 2nd item in an array and it exists in **insertAfter** but isn't passed to **retrieveMediaFiles** -- so something would need to be done to make that function aware of the **showInstance** context, perhaps by adding the showID as a 3rd parameter. And it also gets into Application_Model_Playlist - so yeah this is the place that needs to be modified to make this functionality work but it is already a pretty convoluted function so some thought needs to go into the best way to handle this.

My initial thinking is that we add another parameter showInstanceID to **retrieveMediaFiles** that is ignored except for the dynamic smartblocks and it in turn is passed down to getListOfFilesUnderLimit  and in turn also passed to getListofFilesMeetCriteria and then in there we can use it by having a new modifer set by the UI called "remaining" and the code above can include a new branch in the if limit modifer == "remaining" then it attempts to deduce how many minutes are remaining by creating a new show instance and calling these two functions. https://github.com/LibreTime/libretime/blob/ecac7947477243bc92304307d5d7bdd26d0b47de/airtime_mvc/application/models/ShowInstance.php#L464-L477

And in turn passing back whatever is remaining up as the time limit for the parent function. I think this will work. It seems kind of clunky to need to add parameters in like this but I think that is just where our codebase is right now. Without refactoring it I'm not aware of any greater context awareness built into the different php functions that could do this without passing the show_id as a param.

The other part that will need to be modified is the smartblock form to add the option here
https://github.com/LibreTime/libretime/blob/ecac7947477243bc92304307d5d7bdd26d0b47de/airtime_mvc/application/forms/SmartBlockCriteria.php#L156-L165
and here https://github.com/LibreTime/libretime/blob/ecac7947477243bc92304307d5d7bdd26d0b47de/airtime_mvc/application/forms/SmartBlockCriteria.php#L459-L466

But then we will also need to tweak the [jquery code](https://github.com/LibreTime/libretime/blob/master/airtime_mvc/public/js/airtime/playlist/smart_blockbuilder.js) and then in addition we should probably add some kind of form validation to the playlist edit screen that makes it so that it warns users if they add a smartblock with "fill remaining time" anywhere other than the end of the playlist that all tracks afterwards will not be played. But in actuality I could see an instance where you would want two "fill remaining smartblocks" - one that attempts to put PSAs, promos etc that are longer and then another that adds music tracks that can be cut off like @jerry924 mentions above. This way we could ensure that no PSAs are cut-off and the maximum number are scheduled in the "interstital time" between shows.

In addition we would need the "time remaining" criteria to only work for "dynamic" smartblocks even though static smartblocks are stupid and in an ideal world would not exist. So thats another validation issue.

We'd want to test this with dragging a smart block manually and also by autoplaylist. 

So anyone is welcome to point out flaws in my logic or cleaner ways of coding this but I think I'm going to start on a PR for adding just this functionality.

**Comment by Robbt** [comment]
This was fixed with #605.
