### ISSUE TITLE
"Springdale unsupported" package is not reachable

### ISSUE THREAD

**Issue by yarik2720** [LibreTime/libretime#368]
https://github.com/LibreTime/libretime/blob/f17a3cb5bb5415bf59d9535acceb62f75ff40ae8/installer/vagrant/centos.sh#L11

```
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0
  curl: (7) Failed connect to springdale.math.ias.edu:80; Connection timed out
  error: open of springdale-unsupported-6-2.sdl6.10.noarch.rpm failed: No such file or directory

```

**Comment by hairmare** [comment]
It's reachable from here right now. Maybe it was temporarily unavailable?

If you plan on going down the CentOS route I would highly recommend not to use the installer as there are already some ["unofficial" preliminary packages on OBS](https://build.opensuse.org/package/show/home:radiorabe:airtime/libretime). 

If you go down the tarball route you will need to repair silan and also patch LibreTime to work with liquidsoap 1.3.x as described in #192.

If you use the packages you get a more or less current liquidsoap install, a recent build of silan and the LibreTime install is prepatched for the included liquidsoap version.

Apart from that the only issue the packages have (that I know of) is that the celery parts don't really work due to a python-amqp bump in a recent CentOS release. The git/tarball install is probably also affected. This breaks podcast features among others, basic playout should work though.

**Comment by Robbt** [comment]
This was most likely a temporary internet problem, I'm trying to prune the issue queue so I'm going to close this for now. If it becomes reoccuring feel free to reopen it.
