### ISSUE TITLE
 Import files with airtime-import

### ISSUE THREAD

**Issue by freemanpolys** [LibreTime/libretime#372]
airtime-import script move FILE(s) into the storage directory but the are not imported.
Can anyone help please ?

**Comment by jerry924** [comment]
Any errors in your zendphp.log around the time of the import?

**Comment by Robbt** [comment]
airtime-import isn't supported by LibreTime due to changes in the way files were imported. The developers switched from media-import to airtime_analyzer and the command line tool wasn't updated. There is a work in progress python utility that should bring back this functionality but I'm not sure it was ever finished - see https://github.com/LibreTime/libretime/pull/111 

Feel free to test it and let us know if it works for you. I wasn't able to get it installed due to a permission error but I didn't spend too long on it.

Updating the airtime-import command line tool is another idea that isn't a bad one, but someone will have to spend the time to rewrite this. Sorry for any inconvenience, the decision to no longer support airtime-import happened before we forked the codebase.

**Comment by freemanpolys** [comment]
Thanks @Robbt . I have test successfully airtime_analyzer  with tools/test-hook-script.sh.

**Comment by Robbt** [comment]
Cool, if you want to put in a PR to get airtime-import working with airtime_analyzer I'm sure other people would appreciate it. I haven't tried yet.

**Comment by freemanpolys** [comment]
I don't use airtime-import. I've use the airtime_analyzer/tools/test-hook-script.sh script to upload the file.
It'll be cool  if airtime-import can work with  airtime_analyzer. I'll try to deal with it later.

**Comment by smilingpeanut** [comment]
@freemanpolys Can you post the exact steps you took to get `test-hook-script.sh` working? Thanks!
