### ISSUE TITLE
Streaming stops without active network gateway

### ISSUE THREAD

**Issue by rff6** [LibreTime/libretime#383]
Hi,

I have a stand alone Libretime server running.  i.e. the libretime server and all listeners are on same non public subnet.  If the internet gateway is unavailable Libretime stops scheduling shows.  Why is internet access required for shows to be scheduled?

I'm running Libretime  ￼f17a3cb5b on Debian 9.2

Thanks

**Comment by Robbt** [comment]
Yes, this is because LibreTime accesses the API via the hostname to perform operations. The easy fix is to edit /etc/hosts and add the domain name of your LibreTime install and point it at 127.0.0.1 or localhost and thus avoid accessing DNS to get to the API. We had to do this with our libretime install and it has solved the problem.

**Comment by rff6** [comment]
Thanks.  With host and fqdn in /etc/hosts everything seems fine.
