### ISSUE TITLE
Shoutcast install

### ISSUE THREAD

**Issue by jonikane** [LibreTime/libretime#388]
How i install shoutcast server?

**Comment by hairmare** [comment]
Hi @jonikane 

Welcome to the LibreTime community.

LibreTime's installer doesn't support installing SHOUTcast out of the box. [The official guide from Nullsoft](http://wiki.shoutcast.com/wiki/SHOUTcast_Getting_Started_Guide) or [this third party article](https://www.tecmint.com/install-shoutcast-in-linux/) should point you in the right direction.

Once you have a working SHOUTcast server LibreTime should support sending a stream to it with a correct configuration in the Settings Streams page.

I'm closing this since there are no plans on supporting SHOUTcast in the auto-installer. Maybe someone on our [Discourse Forum](https://discourse.libretime.org) is using SHOUTcast with LibreTime so you might want to consider asking for help with and discussing the install there.
