### ISSUE TITLE
Feature: Sound processing

### ISSUE THREAD

**Issue by benhartwich** [LibreTime/libretime#399]
Hi,

I think, one big advantage of libretime could be a sound processing tool / possibility. I´ve found [this thread](https://forum.sourcefabric.org/discussion/16125/sound-processing-in-airtime-audio-processing-with-liquidsoap/p1).

Till now I´ve to process all audio tracks before uploading. Goal should be to process the files on a virtual sound device using any dsp plugins. Does anyone have any ideas for realizing?

**Comment by squiggleuk** [comment]
If we had a safe place to add custom liquidsoap scripts (Safe in that it won;t get touched during upgrade etc).

We could pipe output to sound processor and handle it all there - Maybe could supply a few example custom scripts for popular options.

A popular option would probably be sending output via command-line version of stereotool, then back in again?

I posted comments in the forum @ https://discourse.libretime.org/t/custom-liquidsoap/40

**Comment by hairmare** [comment]
For the most part this is being tracked at #229. One of the use-cases that came up is using stereotool for processing. At my station we recently switched to using off the shelf professional grade processing since we where getting nowhere fast with DIY. What we learnt is that using properly pre-processed files is important even with that set-up.

There is quite some potential for automating parts of this during ingest/upload. What's available needs  work for it to cover some likely scenarios, for instance, I'd like to see the ability to use EBU-R128/LUFS instead of replaygain. Fingerprinting and metadata validation/completion with MusicBrainz can also help get cleaner files ingested for later playout.

The idea behind #229 would be to add enough integration points to the core liquidsoap streaming engine that an enterprising user could plugin in his or her own processing chain. Modern liquidsoap versions have pipe operator that is very handy  but that would mean looking into getting over the 1.3.x hump as per #192.

**Comment by benhartwich** [comment]
Hi,

thanks for feedback. I´m also interested in stereotool possibilities. I think the liquidsoap realization would be great - with a little gui. How can we go further?
