### ISSUE TITLE
Name of the song

### ISSUE THREAD

**Issue by jonikane** [LibreTime/libretime#400]
Hello,

Does anyone know of any script to show the name of the song that is playing on the radio?

Thank you

**Comment by Robbt** [comment]
If you are talking about audio fingerprinting, ie identifying the name of a song based upon what is playing. I did a quick google search and found this stack overflow question which included a few answers. 

https://stackoverflow.com/questions/6269167/open-source-audio-pattern-recognition-finger-printing

Echoprint appears to work off of a webiste called echoprint.me that as of me trying to access it was down.

There other one with a still active website is **https://acoustid.org/** - at this point there are no scripts to integrate these services with LibreTime.

Since this is just a general question with no bug of feature proposal I'm going to close it.
