### ISSUE TITLE
Upgraded to Alpha3 and importing stopped.

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#407]
Previously this was working but after upgrade, it 'looks' like they have been imported (green tick), but tracks do not appear in the Tracks List.

The files have been downloaded and seem 'stuck' in the organise folder.

Any ideas?

**Comment by JohnnyC1951** [comment]
I just noticed that in the 'Upload' screen the files are listed as 'Import Failed' with the 'Creator' and 'Title' fields being blank and the time of ALL files shows the current date and time :\

A standard upload of file also fails, so I guess its a general import issue somewhere.

I don't want to lose 3 days of scheduling by going to a clean install. Any ideas?

**Comment by JohnnyC1951** [comment]
PS. System status shows no issues and a reboot does not help.

**Comment by hairmare** [comment]
If podcasts don't import properly this is most likely something in the airtime_analyzer component. 

What distro are you on? If you're on Stretch or CentOS running `sudo journalctl -u airtime_analyzer` should dump analyzers log. Maybe it contains info on what's going on?

If nothing shows up in the analyzer logs you should check if the celery component isn't logging any errors `sudo journalctl -u airtime-celery`.

Please post your log files if you don't find any obvious errors in them.

**Comment by JohnnyC1951** [comment]
I am now doing a reinstall. Using trusty. Nothing of note was in analyser log.
I just saw that, using your silan  instructions, it installed silan 0.3.2 not 0.3.3.

**Comment by JohnnyC1951** [comment]
Starting again on Xenial

**Comment by Robbt** [comment]
Another quick question, how did you upgrade ? Did you just run the install again with the alpha.3 download ?

In theory this should work but evidently it didn't work perfectly for you. Is your fresh install working ? We have had some problems with mp3 imports and liquidsoap w/ Stretch that I think are related to the version of Liquidsoap included,

**Comment by JohnnyC1951** [comment]
Ran the install as you said. But I found something else! It seems the server provider used a v2.6 core (Precise) on Trusty and Xenial Ubuntu. It seems this is common on OpenVZ virtualization. I think this may be related.

**Comment by hairmare** [comment]
We won't really be able to help you if you don't post log files.

When I tried checking if silan installs the proper verson on trusty I wasn't able to reproduce you findings. Can you tell us which silan repo you are using and the exact commands you used to end up with the wrong version of silan?  Up to date instructions may be found [in the release notes](https://github.com/LibreTime/libretime/releases/tag/3.0.0-alpha.3#issues-silan-3.0.0-alpha.3).

I'm not quite sure if there are any reasons why a modern container couldn't be run on a OpenVZ host. The bundled RHEL6 kernel fork OpenVZ is based on might explain some of the issues you are seeing. This should get better with OpenVZv7/Virtuozzo7 but I  probably wouldn't hold my breath waiting for that as an OpenVZ customer. OpenVZv7/Virtuozzo7 will be based on the RHEL7 kernel which is the same kernel the tested CentOS installation uses.

If you are on Virtuozzo rather than the open-source upstream OpenVZ you might wan't to ask your provider if they can run you workload on a VM rather than in a container. AFAIK VMs are only supported on Virtuozzo and not on OpenVZ.

If you have issues with logging in after a clean install you will probably find more info in `/var/log/airtime/zendphp.log`. Please post any log files (even if they seem unreadable and large) so we can help debug your issue.

I'm closing this since we need log files to further debug the issue at hand. Please post the exact steps you took that lead to an error, the output from those steps and, complete logs if you need us to reopen this issue.

**Comment by JohnnyC1951** [comment]
Just some notes & jottings. I have reinstalled on a native trusty, opam compiled liquid soap 1.2.0, and installed a later silan, as you suggested in the install notes. It all seems working. Good.
It does not seem to like running the install job on an Ubuntu 12.06 core (2.6) inside a container that is expecting a 14.04 core (4.x). From a quick Google seems many others are having similar problems with other projects. My provider said to use a KVM vitualized system and the problem would disappear. Having lost a day on this, I converted it to a Trusty native system and it is working after adding a few missing dependancies, under an hour. The docker-libretime image works great also now. I had thought that a simple core version warning might have saved some others from going down this path.

**Comment by hairmare** [comment]
Ubuntu 12.04 LTS Precise Pangolin has been EOL since August 7, 2014. It would be rather surprising if it worked on a modern container platform given it still has an old kernel. Due to it's lack of support it also won't get any security patch leaving remaining installations very vulnerable to all kinds of attacks.

I'm not sure what upstream the docker-libretime image is based on but I would assume that it also has better performance on a modern OS.

Running on a dedicated VM (KVM or other) is probably still your best bet at this time. If your provider lets you choose you would want to use virtio drivers where possible.

**Comment by JohnnyC1951** [comment]
Quite. Based on my dealings with my provider, KVM is preferable (for our needs) over OpenGZ as Open GZ uses a common core for all instances and KVM doesn't. Suitability for our needs is a simple core version check.
