### ISSUE TITLE
Installing on Linux Mint 18.3

### ISSUE THREAD

**Issue by KyleRickards** [LibreTime/libretime#415]
Hi

I am trying to install the program but can't see which instructions I need to follow from the main page?

This looks like an amazing project by the way!

Could somebody signpost me to any easy install instructions please?

Thanks
Kyle

**Comment by hairmare** [comment]
Hi @KyleRickards 

First of all, welcome to the LibreTime community!

You should read the [Release Notes](https://github.com/LibreTime/libretime/releases) for up to date information.

If you just want to take LibreTime for a test drive, the fastest way is to install VirtualBox and run [LibreTime in a vagrant box](http://libretime.org/vagrant/). I'd probably recommend going with a debian-stretch virtual machine for now:

```bash
git clone https://github.com/libretime/libretime.git
cd libretime
vagrant up debian-stretch
```

If you want to do a native install on mint our install script installer might work. You can just run it in a shell and it should prompt you for some input and then install. 

```bash
./install
```

If you want to do a production install on mint there are infos on [preparing your server](http://libretime.org/manual/preparing-the-server/). The firewall, PostgreSQL and, RabbitMQ parts are currently up to spec and the installer can take over once they are configured.

Cheers
Lucas

**Comment by KyleRickards** [comment]
Hi Lucas

Many thanks for the reply, I will try in virtual box. I did try an install using /.install in my main setup, but it wouldn’t install.

I have had Airtime working before successfully but I would rather use LibreTime if possible. I’m not too good with trickier installations but will give it a go.

Kyle

**Comment by Robbt** [comment]
I've found that ./install -fiap works better too because some of the dialog prompts are a little wonky ie case sensitive for Y or N vs y or n. What was the failure you ran into during your install ?

**Comment by KyleRickards** [comment]
Hi 

This is what I get when I try and install:

Detecting distribution and release ...
Detected distribution id: linuxmint
Detected distribution release id: 18.3
Detected distribution description: Linux Mint 18.3
ERROR: Distribution "Linux Mint 18.3" is not supported with "linuxmint-18.3"!

**Comment by Robbt** [comment]
Ok, so if you are installing it on your desktop this isn't really ideal because it will install and enable a bunch of unnecessary services. In this case using vagrant and a virtualbox are better alternatives. - see http://libretime.org/vagrant/

If you are building a box for deployment/testing then you are probably better off using Debian or Ubuntu as mint is primarily a desktop OS (as far as I know).

On the other hand if you are intent on using mint it could probably be added by figuring out which version of Ubuntu your version of mint is based on and then modifying the install script. I'm not sure we want to add support for Mint though because it is unlikely to be in use for many servers.

**Comment by KyleRickards** [comment]
Hi

I have created a virtual machine and have installed Vagrant on my host pc, but then I am confused - I don't know how to run things in the virtual set up?

**Comment by Robbt** [comment]
From the page I linked to have you tried running```

git clone https://github.com/libretime/libretime.git
cd libretime
vagrant up ubuntu-trusty
```

If that works it should be good. Now you can modify the code and it will affect your live install which you can access via http://localhost:8080

Hope that helps. If not share any specific issues you are running into running the above.

**Comment by KyleRickards** [comment]
Hi

I tried using the git clone command from within Ubuntu in VM - was that right or should it have been the host machine?

I did install Vagrant on the home system. This is a new environment for me so I am little confused as to how to get t running?

**Comment by Robbt** [comment]
So vagrant is a little confusing at first but pretty awesome once you get used to it.

You do the git clone libretime in your home environment.

Then vagrant is basically a means of automating the starting and stopping and provisioning of your virtual boxes all the while tying the local git repo to the one actually used by LibreTime. So you don't have to rerun the install etc.

Once you get used to it it will save a ton of time, especially for something with as complex an environment as LibreTime. You can even deploy virtual machines of different distros to test it, but not running at the same time due to them using the same ports.

Hope this helps.

**Comment by KyleRickards** [comment]
Ah ok, thank you. So I use the vagrant command along with the stuff I already have and that will fire up my virtual machine and I play in that environment?

**Comment by Robbt** [comment]
Yeah.
  
  

  
  
  
  
  
>

**Comment by Robbt** [comment]
So I'm going to close this because we aren't going to be adding support for Linux Mint anytime soon.
