### ISSUE TITLE
Discourse Dark Theme Broken

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#424]
Discourse forum:

If the dark theme is selected from Preferences->Interface->Theme, the site does not render correctly. It appears as if there is no CSS loaded for that theme.

https://discourse.libretime.org/t/dark-theme-broken/90

**Comment by Robbt** [comment]
I didn't realize you were talking about the discourse forum (for some reason I thought there was a theme option on LT that I was unaware of). I tested the dark theme on discourse and it worked for me. Either way since we are being hosted by discourse we'd need to follow up with them to fix any issues. So I'm going to close this as it isn't related to the LT code itself.

**Comment by hairmare** [comment]
AFAIK https://meta.discourse.org is the place to file discourse issues.
