### ISSUE TITLE
A Dev Question or two, but important.

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#445]
I remember back in the days of Albert S. when I had access to the sharp-end dev fork, they had a 'plugin' scheme where you could code stuff, put it in some 'utils' folder and it appeared in the back-end on a button. I remember that I made a bulk local file and or folder uploader and a direct server to watched folder plupload plugin for it. When Albert S. left, so did my access, although I still talk to him from time to time. Does this 'utils' facility still exist? Where is it? How does it work? I slept since then and can't remember.

Would the team welcome 3rd party or community contributions for this? I have noticed, to my cost, that contribs are not always welcome here.

I can imagine some useful contribs like:

1. Advert inserters (using masterdj channel from a generated ffmpeg stream) (trivial-ish)
2. text to speech news item 'readers' and robot announcers (intermediate)
3. 'cloud bulk importers' (can be simple - depends on host)
4.  Stream video to Youtube with a 'postcard' for video (I already have done this) (trivial)
5. System utils like a novice mode: 'restart the whole caboodle' button (trivial)
6. and the killer: have you the host's LiquidSoap (Ubuntu/Centos/Whatever) running AND AIRTIME/LIBRETIME's LiquidSoap - the cause of so many issues - hint - its just a grep :( 

So, how do we get started? I would rather make tools that are distributable than just make stuff 'in a vacuum', but its not my loss if they are not because I need them
.
.

**Comment by Robbt** [comment]
There is a utils folder.It was referenced in #324 I don't know of any integration to the website or UI. I also didn't know about this existing in AT or any plugin setup. Was this ever a part of the public github ?

I've always been more in favor of integrating fixes directly into the system rather than relying upon scripts and hacks. We talked about how we could do this with liquidsoap #229 but haven't made much headway. 

I'm certainly open to the idea of making it possible to integrate modular tools that don't alter the UI directly. Perhaps we can come up with some kind of guidelines and/or README for the folder to explain the tools are contribs.

**Comment by JohnnyC1951** [comment]
Yep
Look in AT Hacks for my plupload stuff
it showed up on the menu bar

**Comment by JohnnyC1951** [comment]
I made a sheaf of stuff that ran CLI. One other admin was NOT happy at all. Even slightly. I was Ghosted.

**Comment by JohnnyC1951** [comment]
I will ask Daniel James. He worked on this (and also compiled & maintained the LS for AT)
