### ISSUE TITLE
[Suggestion/Request] to have liquidsoap's default feature on LT

### ISSUE THREAD

**Issue by tarkank** [LibreTime/libretime#448]
I was using plain liq to manage my radio stream before and it was treating separate folders with mp3's in them as whole playlists by default. AT haven't implemented it and I think having this option on LT would be a nice addition.

**Comment by Robbt** [comment]
That is an interesting idea, the creation of automatic playlist based upon the folders containing them during import. This would be different than the way liquidsoap does it automatically by say pointing to a folder. This would require hacking the core liquidsoap configuration and is probably outside of the workflow of a typical libretime install at this point.

**Comment by tarkank** [comment]
@hairmare watched folders are similar yes, but not as LS is treating folder contents as playlist in default. It sorta scanned the contents and made the playlists by itself (that's what it had in their documents, then).  As I said I was using LS only much before and this kinda was the simplest approach on quickly handling playlists for a radio stream that needed only to play certain types of genres in between certain times of a day. It's just a suggestion and personally would wish to have this default feature on LT too. Because right now without having AT's watched folders in LT it's pretty hard to create playlists by adding tracks from the dashboard. The filter isn't very useful.

@Robbt thanks. not sure if we are on the same page here but to clear my point out I'll attach my old radio's liq file.


![play-liq](https://user-images.githubusercontent.com/5131028/36380282-bf0fcc96-1592-11e8-8286-0215551bc9e5.png)

**Comment by Robbt** [comment]
@tarkank 
Yeah basically LibreTime and Liquidsoap script modifications aren't really compatible at this point because LibreTime using Liquidsoap as a specific tool to output the streams (and also handle webstreams and remoteDJ logins). The scheduler airtime-playout does all of the pushing of tracks to liquidsoap from the calendar. There is no place in our current UI to circumvent the calendar and just say play random tracks. 

One way people did it in the past with Airtime was insert jingles or whatever when silence was detected. Something like this could work but it wouldn't be easy to administer via the web interface. One of the goals of LibreTime is to make everything configurable by a user with the web-site w/o requiring shell access or tweaking scripts. At the same time we have considered ways to empower the hacking of Liquidsoap for people more comfortable with the lower-level operations. At this point though it's not configured that way.

**Comment by tarkank** [comment]
@Robbt Never used the jingle feature of LiquidSoap, even when I switched to Airtime. From what you wrote I understood that it wouldn't be an easy integration even though it would be a good option to have in LibreTime. Thanks!
