### ISSUE TITLE
[Suggestion] Streaming video files on LT

### ISSUE THREAD

**Issue by tarkank** [LibreTime/libretime#449]
Another idea/suggestion which in my opinion would be a very good feature and maybe a first(?) for a streaming software to include the ability to stream separate video files with the same manner. Liq was or is supporting some video formats as far as I am aware of.

**Comment by techbp** [comment]
This is a good idea indeed! Can we have this functionality please? Anyone?

**Comment by hairmare** [comment]
Liquidsoap supports this as long as it's compile with the right libraries in place, managing video libraries in addition to the audio libraries needed is quite a chore as there are even more standards and container formats than with audio. Realtime video might also have some performance issues on "regular" LibreTime-sized hardware.

Icecast also supports video but I haven't found any real-world examples of anyone using the feature so far.

As far as I can tell this setup would not (yet?) support MPEG-DASH (ie. what Youtube and Twitch) use so it would be of limited use.

I've been looking at [OBS Studio](https://obsproject.com/) and [nginx-rtmp](http://nginx-rtmp.blogspot.ch/) to generate video alongside LibreTime but haven't gotten to the PoC stage yet. The idea is that OBS Studio will make it easier to to switch between cameras and add lower thirds without having to completely refactor the liquidsoap script in LibreTime.

I'm going to close this issue since it has no immediately actionable task and our current focus is on stabilizing LibreTime for a future 3.0.0 release. Pull requests to help get video support underway are always welcome.

**Comment by tarkank** [comment]
@hairmare true. there are a bunch of video containers compared to audio. but it could start with a limited, perhaps only 1 video format (mp4 is pretty much the main standard for some time now) and live streaming isn't necessary at all in my opinion. what i suggested is streaming a bunch of video files (mp4) in the same way as audio tracks (mp3). not that i know the technical struggle but can't that be achieved through adding mime types?

**Comment by Robbt** [comment]
@tarkank This would not be a simple modification because it would require a lot of fundamental additions to the project. I don't see the possibility of doing both video and audio streaming through the whole interface. Now if someone wanted to fork and hack together a test to see how this might work  with a single file format that could be a interesting experiment, but I don't think it'd be easy.

**Comment by tarkank** [comment]
@Robbt I see, thanks for explaining it.

**Comment by JohnnyC1951** [comment]
Icecast has been able to do a few video formats for years, but it never really caught on. Along came youtube live and that was that.

**Comment by JohnnyC1951** [comment]
I do it the other way around, and stream to Youtube Live from the Icecast output. I can attach the Station's Image or the Show's Image (still images) as slow bps but high res video. It's just a few lines of bash and ffmpeg. You can easily find code for this, I just did a 'restart on fail' line or two..

**Comment by hairmare** [comment]
@bjjayk Icecast has inofficially supported streaming non-mp3 content for a while. If we where to support this in LibreTime we would also need to ensure that the upload feature and the library support non-audio content as well. This isn't really trivial since we currently use the python mutagen library (which is audio specific) to analyze uploaded files. Out liquidsoap script would also need some changes to support this (basically our liquidsoap script would need to do what the icewebm.sh script in the link does).

As @Robbt previously explained this would not be simple and require quite some fundamental changes.

We sure would be interested in any experiments to make this possible and gladly accept any pull requests getting such an effort underway.

**Comment by JohnnyC1951** [comment]
Icecast **offficially** has supported WebM (VP8/VP9) format for years. Xiph make Icecast and the Theodora VP8/9 codecs, so that should not come as a surprise.

**Comment by bjjayk** [comment]
@JohnnyC1951  So I have been testing it and it seems to work. I just means to find the best settings. and yes I realized this feature when looking into the xiph directory where someone was streaming movies with his icecast.

@hairmare I also could upload a music video to the server and it played out as music perfectly. It was a youtube video in MP4.

Unfortunately I am no programmer, more like a experienced power user. So I can follow guides and use linux and dig into those technical things but programming is out of scope for me.

**Comment by JohnnyC1951** [comment]
This is a GREAT way to burn bandwidth :D
