### ISSUE TITLE
https/ssl connection to libretime and icecast

### ISSUE THREAD

**Issue by dddrey** [LibreTime/libretime#466]
can't figure out how to run libretime and icecast on same server over https 
i need ssl connection because my main site is running over https and i got "mixed content https to http" problem

what figured out:
– https connection only available over DNS server (so i need to connect domain to the server)
– but domain is only available for ip address without mentioning the port (it connects to 443 itself)
libretime server works over https, i tried to use vhost but got stuck on it

i tried to set up icecast over https adding this to /etc/icecast2/icecast.xml
```
<ssl>1</ssl>
<ssl-certificate>/etc/ssl/certs/icecast.pem</ssl-certificate>
```
but nothing is working

icecast.pem made with this command:
`openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout icecast.pem -out icecast.pem 
`

what requests needed:
– libretime/api/live-info-v2 json
– icecast/_a live audio

any ideas or hacks on it?

**Comment by Power2All** [comment]
I did some hard-coded fixes.
I'm actually using NGINX as proxy, that makes HTTPS accessible for icecast, did some little template changes, and all is now SSL.

If you need help with it, you can also contact me on discord:
Power2All#1482

I could help you fix it, since not every setup is the same :)

**Comment by dddrey** [comment]
@Power2All thank you for replying
i've sent you a friend request on discord as gigabud

**Comment by Power2All** [comment]
And his problem is fixed.
You can close the issue.

**Comment by dddrey** [comment]
yep, solved.
Big thanks, @Power2All

**Comment by hairmare** [comment]
@Power2All Thanks for helping out with triaging issues! I sent you a Contributor invite so you can label, assign and, close issues should you want to.

> I'm actually using NGINX as proxy, that makes HTTPS accessible for icecast, did some little template changes, and all is now SSL.

Where any of the template changes TLS related? I though I'd caught them all with my last TLS-only cleanup patch (but I don't use the public facing parts of LibreTime in production so I might have missed some TLS-only support bugs). If you could point me in the right direction I'd be happy to fix them at the source.

BTW, I'm currently waiting for xiph to tag a new icecast version since the next version will support reloading certs without kicking connected listeners. Once that drops, writing Lets Encrypt docs will make sense. Personally, I'm in the "icecast does not belong behind a reverse proxy" camp but using a non blocking proxy implementation (like nginx) should work fine.

As you pointed out not every setup is the same, this is absolutely fine as different stations have different requirements. I.e. at my station the iccast master is on an internal network and we have a listener facing relay in the cloud to save on-prem bandwidth.

**Comment by Power2All** [comment]
@hairmare I actually kept Icecast as it is, and using NGINX as proxy to handle the SSL part.
From there on, I could simply apply a new SSL cert from either LetsEncrypt or CloudFlare.
This way I do not need to worry about Icecast itself.

**Comment by tgd1973** [comment]
The document to put SSL on Libretime is wrong ...
`https://libretime.org/manual/secure-login-with-ssl/`
I pray that someone will correct it because the correct path is not:  DocumentRoot **/usr/share/airtime/public**  but  DocumentRoot  **/usr/share/airtime/php/airtime_mvc/public/**
problem is that even if you put the other path you can not surf anyway ...

**Comment by Ark74** [comment]
Hi guys, I'm testing the installer of LT, but I'm using some other applications already using Apache and I'm bumping whit the same questions.
So, is it recommended to use nginx above apache?
Is there a default nginx configuration already on the installer?

Cheers!

**Comment by Ark74** [comment]
I'm fairly new to airtable, but reading the comments from @dddrey and recommendations from @Power2All I've come with a standard SSL apache configuration.

I'm recycling the default config install also I'm not using redirection to https (for now) since I'd like to hear suggestions or ideas about it tests seem right, maybe we could split http and https on different files, so http is only enabled by default and https needs to be done manually so people can setup Let'sEncrypt.

Anyhow, here the configuration that I have working so far,

Suggested apache modules, 
`a2enmod proxy proxy_http proxy_ajp rewrite deflate headers proxy_balancer proxy_connect proxy_html xml2enc`

AllinOne conf file:
```
<VirtualHost *:443>
   SSLEngine on
   SSLProtocol All -SSLv2 -SSLv3
   SSLCompression off
   SSLCertificateFile /etc/letsencrypt/live/airtime.example.com/fullchain.pem
   SSLCertificateKeyFile /etc/letsencrypt/live/airtime.example.com/privkey.pem
## Enable this when your configuration is complete and definitive.
#   Header always set Strict-Transport-Security "max-age=31536000"

   ServerName airtime.example.com
   ServerAdmin admin@example.com
   DocumentRoot /usr/share/airtime/php/airtime_mvc/public/
   php_admin_value upload_tmp_dir /tmp
   php_value post_max_size 500M
   php_value upload_max_filesize 500M
   php_value request_order "GPC"
   php_value session.gc_probability 0
   php_value session.auto_start 0

## Proxy requires several modules enabled, please check: 
## http://libretime.org/manual/secure-login-with-ssl/ or 
## https://github.com/LibreTime/libretime/issues/376
  # ProxyPreserveHost On
  # ProxyRequests Off
## Icecast Streams
  # ProxyPass "/icecast" http://127.0.0.1:8000/
  # ProxyPassReverse "/icecast" http://127.0.0.1:8000/
  # ProxyPass "/admin" http://127.0.0.1:8000/admin
  # ProxyPassReverse "/admin" http://127.0.0.1:8000/admin
## Stream 1  
  # ProxyPass "/your_path_name"  "http://localhost:8000/_a"
  # ProxyPassReverse "/your_path_name"  "http://localhost:8000/_a"
## Stream 2
  # ProxyPass "/your_path_name"  "http://localhost:8000/_b"
  # ProxyPassReverse "/your_path_name"  "http://localhost:8000/_b"
## Stream 3
  # ProxyPass "/your_path_name"  "http://localhost:8000/_c"
  # ProxyPassReverse "/your_path_name"  "http://localhost:8000/_c"

   AddOutputFilterByType DEFLATE text/plain
   AddOutputFilterByType DEFLATE text/html
   AddOutputFilterByType DEFLATE text/xml
   AddOutputFilterByType DEFLATE text/css
   AddOutputFilterByType DEFLATE application/xml
   AddOutputFilterByType DEFLATE application/xhtml+xml
   AddOutputFilterByType DEFLATE application/rss+xml
   AddOutputFilterByType DEFLATE application/javascript
   AddOutputFilterByType DEFLATE application/x-javascript
   AddOutputFilterByType DEFLATE application/json

  <Directory /usr/share/airtime/php/airtime_mvc/public/>
      RewriteEngine On
      RewriteCond %{REQUEST_FILENAME} -s [OR]
      RewriteCond %{REQUEST_FILENAME} -l [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^.*$ - [NC,L]
      RewriteRule ^.*$ index.php [NC,L]

      DirectoryIndex index.php
      AllowOverride all
      Order allow,deny
      Allow from all

      Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:80>
   ServerName airtime.example.com
   ServerAdmin admin@example.com
   DocumentRoot /usr/share/airtime/php/airtime_mvc/public/
   php_admin_value upload_tmp_dir /tmp
   php_value post_max_size 500M
   php_value upload_max_filesize 500M
   php_value request_order "GPC"
   php_value session.gc_probability 0
   php_value session.auto_start 0

   AddOutputFilterByType DEFLATE text/plain
   AddOutputFilterByType DEFLATE text/html
   AddOutputFilterByType DEFLATE text/xml
   AddOutputFilterByType DEFLATE text/css
   AddOutputFilterByType DEFLATE application/xml
   AddOutputFilterByType DEFLATE application/xhtml+xml
   AddOutputFilterByType DEFLATE application/rss+xml
   AddOutputFilterByType DEFLATE application/javascript
   AddOutputFilterByType DEFLATE application/x-javascript
   AddOutputFilterByType DEFLATE application/json


  <Directory /usr/share/airtime/php/airtime_mvc/public/>
      RewriteEngine On
      RewriteCond %{REQUEST_FILENAME} -s [OR]
      RewriteCond %{REQUEST_FILENAME} -l [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^.*$ - [NC,L]
      RewriteRule ^.*$ index.php [NC,L]

      DirectoryIndex index.php
      AllowOverride all
      Order allow,deny
      Allow from all

      Require all granted
  </Directory>
</VirtualHost>
```

Suggestions and corrections are pretty welcome, If it fits basic requirements we could update the documentation about SSL.

Cheers!

**Comment by Ark74** [comment]
I've being testing mainly proxy settings in order to simplify the configuration of SSL also going some steps further, into making some patches to the issues that I've seen as a separate file.

It makes possible to access Icecast from the reverse proxy, for more info look the PR https://github.com/LibreTime/libretime/pull/501.

Cheers!

**Comment by JohnnyC1951** [comment]
Care must be taken else you always get the same IP for listeners in your stats

**Comment by joaoherberto** [comment]
@Ark74 I am trying to set up my server with SSL and I have a question, ok three... 

> " ProxyPass "/your_path_name"  "http://localhost:8000/_a"
 
What does "/your_path_name" refer to?
should localhost be changed to the FQDN?
Also,  are quotes required or no?

**Comment by Power2All** [comment]
> @Ark74 I am trying to set up my server with SSL and I have a question, ok three...
> 
> > " ProxyPass "/your_path_name"  "http://localhost:8000/_a"
> 
> What does "/your_path_name" refer to?
> should localhost be changed to the FQDN?
> Also, are quotes required or no?

Not sure if you already solved it.
But it's basically the location forwarding.
In this case, you could technically forward "https://my.domain.com/playme" to "http://localhost:8000/_a" which would be running locally a icecast server, listening to localhost.
If you set icecast to listen to 0.0.0.0 it would be accessible on all IP's on that server.
If you want icecast only be accessible by NGINX forward, you make it bind to 127.0.0.1, hence the forwarding to 127.0.0.1 on port 8000.
