### ISSUE TITLE
Ubuntu 16 audio problem (and solution)

### ISSUE THREAD

**Issue by greenjon** [LibreTime/libretime#473]
Hardware audio output will not work until:
adduser www-data audio
(as root.)

Ubuntu 16.04.4LTS
Libretime Alpha 4 (also Alpha 3)

**Comment by Robbt** [comment]
Hmm, we should definitely add this to our install script but the big question is whether it needs to be done on all distros or just debian based ones.

**Comment by hairmare** [comment]
In my CentOS liquidsoap packages I decided against automatically doing this due to the fact that everything works well without it and it's only needed in cases where you are actually using the alsa output. In the case of my liquidsoap packages I want the admin to be aware of the additional privileges that allow direct access to some pretty low-level parts of the kernel and the underlying hardware.

While it probably makes sense on `./install` based installation I might be that we won't want to have this be done automatically in package based installs.

**Comment by Robbt** [comment]
Yeah it could be put behind a yes / no question in the install script. We could also do that in an interactive install script for the Debian package. Or we could just mention this in the docs and/or during the web based install portion of the installation process.

**Comment by frecuencialibre** [comment]
my vote is that the ./install script do this by default in ubuntu, and that it simply print out a message notifying that this has happened. if low-level access is necessary in order to do what the UI claims it can do, and if this isn't a security concern, than so be it. i for one never understood why audio playback didn't work, and we didn't correctly troubleshoot it. also IMO stopping the install process with a question that a low percentage of people will even understand isn't ideal.

**Comment by Robbt** [comment]
Well in terms of the install script I think that we should encourage people to do ./install -fiap and thus take the default values for everything and say yes to all prompts because there are almost no cases where on a fresh install with default settings you would want to say no. So we might want to change the documentation in my opinion or even change the script to require --interactive to bring up the prompts and otherwise just install. It's tricky because we'd probably be better of with a debian package but I've yet to investigate how to build them. Either way I tend to agree that this option should be included at least for the debian and ubuntu systems.

**Comment by greenjon** [comment]
I don't know much about code, but I noticed that \installer\vagrant\debian.sh includes:
`usermod -a -G audio www-data` so does that fix this issue?

**Comment by Robbt** [comment]
Yeah I think that solves the problem as well. I'm not sure why we don't do it in the base installer as a debian distro specific fix.

**Comment by greenjon** [comment]
Great! Closing this issue. Feel free to reopen it if you want to use this Issue as the place to push for this to be changed in the base installer.

**Comment by Robbt** [comment]
I think I will just push a PR to add this as an option for the installer.

**Comment by zklosko** [comment]
I added documentation regarding this to #1050
