### ISSUE TITLE
Request: Importing Music and playlists from airtime to libretime

### ISSUE THREAD

**Issue by twosdai** [LibreTime/libretime#482]
Currently I have purchased some new hardware and downloaded Ubuntu 16.04 onto it and installed libretime successfully. Meanwhile our station is running airtime 2.5 on some old hardware with terabytes of music and playlists which have been uploaded over the years. I've looked into some options into porting over the music from Airtime to libretime but wanted input on any other ideas I've probably missed and overlooked. My current idea is to create a shared network drive and then copy the relevant folders from the old airtime install and then script out the following functionality:  
`php tools/message_sender.php '{ "tmp_file_path" : "foo.mp3", "final_directory" : ".", "callback_url" : "http://airtime.localhost/rest/media/1", "api_key" : "YOUR_API_KEY" }'`

`$ php tools/message_sender.php '{"tmp_file_path":"foo.mp3", "import_directory":"/srv/airtime/stor/imported/1","original_filename":"foo.mp3","callback_url": "http://airtime.localhost/rest/media/1", "api_key":"YOUR_API_KEY"}'`

So that the script would run the following tool to just drop the songs in as if they were uploaded to the server normally. However I am unsure if this is the correct path as I believe it wont work for the playlists. I was also looking into running: `airtime_analyzer/tools/test-hook-script.sh` to see if that could work but I haven't given it a good look yet. Let me know if any of this sounds wrong, or there is a better way I haven't seen anything for this in the manual or in the forums here.

**Comment by Robbt** [comment]
The easiest thing to be would be to copy the Airtime 2.5 system database and music storage file folders onto the new system and then just run the install script for LibreTime and it should perform an upgrade. This will keep all of the existing playlists and tracks etc. 

The importing of tracks isn't really fully implemented right now.

**Comment by Robbt** [comment]
Ok, so once #514 is merged you will be able to copy files into a directory '''/srv/airtime/stor/uploads''' and have them automatically imported. 

But if you are trying to copy over your playlists and calendar from 2.5.x it really makes more sense to just duplicate the database and filesystem in your new computer and then run a upgrade to LibreTime. Since this is more of a support request I'm going to close it but if you are still having issues or have further questions feel free to respond to one of the issues related to upgrading to 2.5 such as #71 and we will do our best to help you address them.
