### ISSUE TITLE
What is the best config for icecast ?

### ISSUE THREAD

**Issue by AEK-BKF** [LibreTime/libretime#540]
Hi,

What is the best config for icecast to allow more than 2000 listeners hearing a song without any issue ?
I'm on Ubunt 16.04 Server, is there any config on it ?

Thanks

**Comment by Robbt** [comment]
This is heavily dependent upon your bandwidth and then also on the processor etc. So without knowing how thebnetoekr

**Comment by Robbt** [comment]
A question related to this, but not about listeners is can we optimize streaming clients connecting to libretime to have enough buffer that slight disconnects for a second or two don't result in dead air or a resumption of whatever is programmed underneath. Is this possible ? This occurs to one of our broadcasters who does a live show, he loses connection for a second and it creates a disruption because we have a backup program airing in case he isn't able to do his love show.

**Comment by JohnnyC1951** [comment]
I kinda fixed this in my player. I made mine drop tolerant and it recovers from such things. The main trick was clearing the local buffer before retrying, which stopped the old local buffer from replaying. You can see it here: [https://www.deprogrammedradio.com/player/](https://www.deprogrammedradio.com/player/)

**Comment by JohnnyC1951** [comment]
Source code for the player. Just pop it in any public folder [https://www.deprogrammedradio.com/downloads/JohnnyC_Player.zip](https://www.deprogrammedradio.com/downloads/JohnnyC_Player.zip)

**Comment by Robbt** [comment]
So I managed to mostly solve the issue our broadcaster was having by modifying the liquidsoap config at /usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_script.liq and i added buffer=10., to the input.harbor parameters and it resolved the many short disconnects. I guess the buffer defaults to 2.

It might be helpful to see if there is a way to either document this or provide a way to modify configurations like this in such a way that they don't get overridden by installing new versions of airtime-playout

**Comment by JohnnyC1951** [comment]
Adding that tip to the release notes, at least, sounds like a good idea ('cos I will forget it).

**Comment by hairmare** [comment]
Y'all can we keep this on topic? 

I did some off the cuff calculations about the needed bandwidth for 2000 listeners.

| Stream bitrate | needed Bandwidth |
| --- | --- |
| 128 kbps | 32 MBps |
| 256  kbps | 64 MBps |

You can calculate this on you own by plugging something like "128 kbps * 2000" into google.

As you can see, a 100 MBps uplink would be almost full if you have a 128 kbps and 256 kbps stream with 2000 listeners each (32 MBps + 64 MBps = 96 MBps). Keep in mind that chances are slim that all the listeners will be connected 24x7 so the link won't be saturated all the time.

This only approximates things since it depends on the exact specifics of your uplink. Most providers only guarantee the advertised speed as best-effort traffic, during peak times this might mean you can't use the full 100 MBps. Some (mostly business) network providers might also offer you the possibility of burst transmissions (ie. you can go over the nominal bandwidth you are paying for if the bursts only affect less than 10% of your monthly bandwidth).

At our station we used to overbook a 10 MBps uplink by a couple of % and still managed to serve our listeners without noticeable drops in the stream. This was on our own leased line so we had all the bandwidth to ourselves and didn't have to worry about bursting or best-effort.

2000 listeners sounds like a lot to me, maybe you are a large enough customer that you can go over this with your provider and have their network engineers help with right-sizing the connection you need.

**Comment by JohnnyC1951** [comment]
One of my guys using the Icecast test from here: [https://icecast.org/loadtest/1/](https://icecast.org/loadtest/1/) found that one of our dedicated servers on a 100mb (unlimited) network running 128k topped out at only 144 listeners! We scratched our heads, how could that be? After a lot of digging, it  transpired that the maximum handles that the primary network card could handle was... 144. Bingo! So there can be other limiting factors. My dead cheap cloud VPS can easily do 10x this.

**Comment by Robbt** [comment]
Cool. Yeah this is all good information and would be useful to add to the docs somewhere under the heading "How many listeners can LibreTime

**Comment by Robbt** [comment]
There is already a issue opened for the butt issue #160 - but we are already off-topic. If there is a specific handshake we should implement then this should be added as a new issue so we can document and try to fix it.

**Comment by AEK-BKF** [comment]
Thanks all for help :)
