### ISSUE TITLE
Problem: How Automatic Playlists work is not intuitive with the current UI

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#560]
The Automatic Playlist as currently set-up in the show configuration isn't easily understood by people just starting with LibreTime.

The problem is that one if a automatic playlist is added to a currently airing show (ie when someone is testing a new LT install) it won't do anything.

Additionally it isn't clear to users that an automatic playlist is scheduled an hour before the show airs or what a good example configuration for a "show based" automatic playlist is.

This was brought up in #544 

There are a few possible solutions, one simple one would be adding a tool tip that can further explain automatic playlists or modifying the code to have them schedule for new shows that are just created. In addition some of this could be handled in the documentation by providing more examples.

Another option is to add parameters to automatic playlists to allow the user to set at what time "before the show airs" they run and the possibilty to have multiple automatic playlists such as those that pre-pend the content rather than always appending the scheduled content if any. But it isn't clear whether complicating the setup would make it more usable or just confusing to end users.

**Comment by JohnnyC1951** [comment]
Yet another option is simply add a paragraph in the Automatic Playlist section of the LT manual.

**Comment by frecuencialibre** [comment]
Thanks @Robbt for sprinting yesterday. got a lot of balls rolling!!! 

Seems like we need a solution that is both feasible to code within our (as yet undefined) beta release timeframe, and also packs a decent user experience. 

I followed the steps in [the wiki](https://github.com/LibreTime/libretime/wiki/Automatic-Playlists,-Smartblocks-and-Podcasts), nice work! very cool. 

from my total ignorance, i'm guessing that background task scheduling is necessary for podcast downloading rather than anything specific to auto-playlists, correct? if so, would it be possible for automatic playlists and podcast downloading to be more independent from each other? Could you point me to code, or help me understand this point?

again, ignorant questions since i haven't looked at the code, but from just looking at the UI, i'd guess that i could add a podcast smartblocks to a show, and then click the "link" checkbox upon creating with all repeating instances. also ideally auto-playlists could also survive despite failure to download podcasts. just further reasons why IMO it'd be great for auto-playlist and podcast functionalities to be well separated.

hopefully this is at all helpful. 

also a sidenote: 
>  If this didn't happen go to Settings -> General table and ensure these options are both checked Podcast Album Override and Podcast Automatic Smartblock and Playlist.
i'd say these should just be enabled by default.

**Comment by Robbt** [comment]
They are enabled by default I believe.
The automatic playlist is currently just a check to see if a new automatic playlist needs to be spun up. It relies upon the background task scheduling because that was the easiest way I could see to do something without spinning up a system cron job. To fix the issue we just need to create something akin to a cron job as a python service that runs.

The functionality is separate, a playlist will be scheduled when the code says there is a new auto playlist to schedule. If a podcast fails to download and you have a smartblock in an auto playlist to play the newest podcast this would just play the previous one. I've had auto playlists work and keep running our station when we've lost connectivity to our transmitter before. The only thing is the mechanism is tied to track playout as the bug described in #129 - and so if you have a 2+ hour long track it can result in a auto playlist failing to schedule as well. 

I guess the autoplaylist could be written to be triggered another way but I don't know what the benefit would be. Automating the task scheduler to happen even when there aren't tracks scheduled should fix the issue.

**Comment by frecuencialibre** [comment]
> They are enabled by default I believe.

Both of the instances I've tested on have these two settings disabled by default. I'm also going to look at improving translation
![captura de pantalla de 2018-10-16 09-52-06](https://user-images.githubusercontent.com/36803137/47025541-508bbe80-d129-11e8-8112-6d9de89d0eaf.png)

more in a sec...

**Comment by Robbt** [comment]
Yeah maybe we should change the name to scheduled playlist. It is still compatible with manually scheduling.

**Comment by frecuencialibre** [comment]
> There are a few possible solutions, one simple one would be adding a tool tip that can further explain automatic playlists or modifying the code to have them schedule for new shows that are just created. In addition some of this could be handled in the documentation by providing more examples.

I could help with this. I'd say this will need to happen regardless of whether we (you hehe) implement functionality changes.

> Another option is to add parameters to automatic playlists to allow the user to set at what time "before the show airs" they run and the possibilty to have multiple automatic playlists such as those that pre-pend the content rather than always appending the scheduled content if any. But it isn't clear whether complicating the setup would make it more usable or just confusing to end users.

i think the most efficient way to advance this conversation would be able to talk by phone or schedule a realtime chat. any interest/availability? (including others here too, not just Robbt, bueler?). 
there are things i'm not understanding and have trouble testing since i have to wait an hour between making changes and seeing effects. for example related to the last paragraph i quote, if conventionally scheduled programming is present, then it will take precedence over automatic playlists. right? 

...and then regarding the settings, can anyone else confirm whether or not auto-creation of the smartblock and playlist are being enabled by default? if they aren't then we have another feature request.

**Comment by frecuencialibre** [comment]
I see this commit: https://github.com/LibreTime/libretime/commit/32a1a66378919a96e02c8fc1a18d75a02032c1ee

but it's mega and i've run out of time righ t now. i'd like to understand the scheduling an hour ahead of time, and also why it doesn't just work like dynamic smartblocks, which seem to be able to just query the database on the fly, no?

take care and thank you!!!

**Comment by Robbt** [comment]
The reason it waits until an hour before is that is the arbitrary time I chose to try to program an auto playlists.

The reason it doesn't just automatically schedule things when they are created is because it is designed to accommodate repeating shows where the content will be updated periodically most likely between the two shows. For instance democracy now puts out a new show every weekday. So the smart block for Tuesday will be different than the smartblock for Monday if they see based upon the newest item. 

Also the way it works now is that the playlist is added to the end of the show playlist. So if you manually scheduled something then it would just add it to the end. If the whole show was already full it would still overbook it but the automatic playlist stuff would never air.

**Comment by Robbt** [comment]
I had thought of perhaps having the option of multiple automatic playlists for instance one that prepends content before whatever is scheduled or even multiple playlists at the end but this would be more complicated to build and I wasn't sure that it wouldn't just make it even more confusing to the end user. 

In addition I thought we could make the time before flexible or set in the admin screen. But wasn't sure this was something that people would need to change.

**Comment by xabispacebiker** [comment]
I wouldnt add the option of multiple automatic playlist. From my point of view, one playlist is enough and adding more would make it more complex to mantain. In all cases I would add the ability to use smarblocks instead of playlists because it's a bit annoying to have to create a new list just to contain a smartblock in order to attach it to the automatic-playlist, but I do not know if this would be difficult to implement.

**Comment by Robbt** [comment]
Ok, yeah I suspected that multiple playlists would just add more confusion, although I am not sure that the solution I came up with is ideal.

So far there are a few ideas that are being floated here.

- Allow the selection of a smartblock for the automatic playlist
- Rename the automatic playlist to auto scheduled playlist (or something along those lines)
- Add a tool tip to better explain the auto playlist
- Improve the docs to contain better examples of how it is intended to be used

Ideas I came up with that aren't specifically mentioned and would require more work

- Modifying smart blocks to be able to choose their length based upon time remaining in a show instance 
- Setting up a separate auto DJ that can be configured to fill in any unscheduled time on specific shows or on all shows
- Making the smart blocks more intuitive to people such that they represent categories of tracks and are easier to build and manage akin to directories or "smart playlists"
- The creation of playlists that prepend to the front of scheduled tracks (useful for top of the hour IDs) 
- The ability to analyze tracks for silence or specific times and cut them up and insert "x" smartblock inbetween the two tracks
- a easy to setup template that says X of this type then X of this type (can be done with smart blocks but clunky to configure)  - see #335

I don't know where in the issue queue I mentioned it but in an ideal world we would break up smart blocks into different parts - one part being the filter criteria - the second part being the sort criteria and the third part being the length or items. Maybe I was riffing on this in Slack but I did mention a similar idea in #90

So you could create a filter called "Station ID" make it match tracks based upon criteria defined by the user. Then it would be easy to reuse this in a template and say X numbers of station ID or the newest "Station ID" without needing to recreate the criteria for these smart blocks. I think this would represent a major rewrite of the smart block functionality and might be better accomplished after we do a overhaul of the frameworks etc. 
I don't know for sure as I haven't tried to write it. The actual smart block code is kind of a nightmare to navigate and I think introducing this feature would require a substantial rewrite. So perhaps it can be on hold until we get what we have working as best we can.

**Comment by frecuencialibre** [comment]
Thanks for the thorough reflection. My personal opinion is that we should focus here on on small changes that could be feasibly included in the upcoming v.3 beta release (ie. without a framework update).

I agree that multiple auto playlists could get confusing. 

Regarding specific implementable suggestions: 

> Allow the selection of a smartblock for the automatic playlist

Our use-case is that we need an ability to replay a _playlist_ as many times as is necessary until the end of the show. This seems to currently be the best way to loop content eg. X songs from a smartblock, then a random station id from a different smartblock, rinse and repeat. If the auto-playlist function starts to enable use of  smartblocks, i'd request that playlists continue to be supported.

>  Rename the automatic playlist to auto scheduled playlist (or something along those lines)

i agree that a re-name could be useful. once we finalize functionality then we'll need to cross this bridge.

>  Add a tool tip to better explain the auto playlist
    Improve the docs to contain better examples of how it is intended to be used

definitely. possibly the tooltip could include a link to a specific page in the documentation. again, this content is dependent on finalizing functionality.

To this list of specific suggestions, I'm wondering how complicated it would be to trigger playlist creation multiple times. The call we currently have an hour beforehand definitely makes sense in order to give time to download the newest podcast. In addition i'd consider triggering playlist creation AGAIN, 1. when the show starts, and 2. if the show's auto playlist is changed. Is this at all feasible pre-beta? Would there a risk here of overwriting schedules?

I'm seeing a few needs here that perhaps should not _all_ be resolved by auto-playlists. 

1. podcast scheduling
2. dead-air prevention
3. repeating playlists until the show finishes

I'll keep thinking about this. thanks!

**Comment by Robbt** [comment]
3 is already supported to a degree. There is a checkbox under the automatic playlist that says, repeat until the show is full. There are some drawbacks to this approach though. It will always overbook (it checks and sees if a show is full if not it schedules the entire playlist again) and thus will result in something getting cut off midway through. If used for non-music shows it can result in the repetition of the beginning of a program at the end of a program and then just cutting off. This is less than ideal. 

I'm not sure how we would accomplish repeating a smartblock playlist such as without "3 of x 1 of x" without cutting off unless we modified the scheduler to always check and see if it goes over the remaining time and to not schedule a track that does. This could result in a lot of really short tracks at the end or dead air because it is randomly pulling tracks rather than performing a optimized selection that best fits the time allocated. 

I think there is probably a compromise in here that we can figure out. My idea was you have a special smartblock that has an adaptive length "until end of show" which will treat this as a time length and schedule until it gets as close to that time as possible. But this isn't always ideal because it would mean that you'd need to end your playlist with a "filler" style of smartblock that fits one criteria and repeats until it can't schedule any more tracks. It would also preclude the option of repeating "X of this smartblock, X of this smartblock" because it would only do it once and then fill in the end. This is discussed in #335 

Another idea would be an autoDJ style playlist that finds the time remaining and repeats a playlist to fill in any missing space. This could be set systemwide or on specific shows.

I think there are 2 different problem spaces.

Talk style shows that have 1 episode but vary in length and thus require some kind of "interstitial audio" to tied over the listener until the next show. Ideally done without cutting off a track partway through unless it is a musicial bridge style track that can get cut-off without leaving the listener feeling jarred. 

Automatically programmed music or short tracks that fit a criteria and are scheduled until the show is full. Still ideally performed without cutting off the listener midway through a song unless it is designated a bridge track. For these autoDJ style shows the usage of station ID/advert/PSA as segways between different music tracks is useful. 

Repeating until a show is filled for case 1 is a disaster resulting in angry listeners annoyed that either the beginning of a show is repeating or something they are listening too is cut-off. A smart filler inserted at the end would solve this.

For problem 2 repeating until full would work but ideally it wouldn't schedule a track past the threshold unless it was a musical bridge. 

One question that arises is, do other stations recognize the notion of a musical bridge and do we want to designate some kind of marker that is integrated into the UI to specially label certain tracks. My station has been using MB at the beginning of the track title but we've also had to merge PSAs and other tracks that aren't musicial bridges into this to liven up the 6 minutes of filler we put at the end of our prescheduled shows. If someone doesn't manicure it by hand though this can result in a crappy listening experience and so my goal would be to improve this. This problem is identified in #357 and one solution. They designate them ambient sounds. In theory we could even bundle a list of creative commons licensed ambient sounds as an optional add-in for LibreTime.

Now to re-touch on the 3 items above.
- 1. podcast scheduling is handled through the playlist that is automatically created that includes the smartblock that is set for the latest new show - the biggest issue with this is that the solution is convoluted because of the usage of pre-existing abstractions. But it works and I don't see a easy fix unless we redo/replace the way smartblocks and playlists work together.

- 2. dead-air prevention could be handled on a couple of different levels, on the scheduled playout level where LT ensures that in theory something gets scheduled to play when it thinks there is dead air. This could be set system-wide or on a per show or even based upon time of day (can't find the issue where this was suggested). This is a good way of handling situations where the scheduler just isn't filled, but there can be other causes of dead air and they would need to be addressed on the liquidsoap or pypo level. For instance if you have scheduled the streaming of a webstream but the internet is down or the webstream is down. Or if there is an error with the track and it is shorter than expected etc. Using Jack for playout with silence detection as @ned-kelly is working on for the docker setup is another good redundancy approach. This low-level dead air along with the bugs that cause it are probably the biggest challenge towards adoption of LibreTime by bigger radio stations with more to lose than a smaller community station.

- 3. I started this comment referencing this see so see-above, it works but the solution leaves somethings to be desired.

**Comment by frecuencialibre** [comment]
cool, thanks again for the well thought-out response. We've both raised a lot of issues here, so I'll try to focus as much as i can in order to extract a reasonably-scoped task. 

1. Podcast scheduling: Let's focus this issue on this one. See below.

2. Dead air: as you mentioned there is conversation on this front by both @xabispacebiker https://github.com/LibreTime/libretime/issues/229 and @ned-kelly https://github.com/LibreTime/libretime/issues/515#issuecomment-427714637 . Despite the fact that what are currently called "auto playlists" appear to be the only working "crutch" available, I propose that they not be the recommended solution to dead air for the reasons you describe above.

3. Repeating smartblock content until show finishes. As you know, this is the one that has been requested of me. I think I need to accept that for now we do not have an automatic solution. We will be manually creating playlists of multiple smartblocks that exceed the duration of the shows they inhabit. 

===========

So now putting my UX hat on, I have two proposals for your consideration. 

1. Delete the Automatic playlist section of the edit show modal. Podcasts should be added to shows via the standard content creation workflow -- ie. just as one would add any smartblock. Podcast downloading should be scheduled in some other way, in the background without the need for a user to set it up. This option would sacrifice the "repeat until full" functionality, but as you say this pisses off listeners anyway. 
2. "Scheduled playlist" 
- Change section name to "Scheduled playlist" 
- Add a tooltip that contains a link for "more info."
- A working button right there in the "edit show" box that would generate the playlist. this has two objectives: first that it would be useful. I also know from experience that no matter how prominent you make messages that "this doesn't work as you might expect!!!" non-developer users won't read it and then will conclude that the product is broken. 
![screenshot from 2018-10-22 13-23-25](https://user-images.githubusercontent.com/36803137/47310814-c9918700-d5fd-11e8-8832-e3af70335076.png)

I personally have found big UX change suggestions that come AFTER having spent many hours in the code to be frustrating as %$@%&. hope this makes sense and is remotely useful. 


also ps. we still need confirmation on whether the settings are enabled by default.

**Comment by Robbt** [comment]
I'm not sure I understand the podcast aspect of proposal 1. 
Podcast downloading happens independent of the automatic playlist - but the API event is used to trigger both the automatic playlist scheduling and podcast downloading - this is the bug highlighted in #129 and fixing it will make both of these independent of either someone going to the website or a track being played. 

For proposal 2 - I think the addition of add playlist content to show now makes sense, but we run into the issue that shows and show instances are different things and each show can have many show instances (if they are repeating). So do we want this to just schedule the next show instance ? There was a request to enable the scheduling of playlists for a whole time range for a certain show here -  #382 but it wasn't really fleshed out.

It certainly makes sense for this button to exist when someone is creating a show that is going to air within the next hour and thus wouldn't be automatically scheduled. But it might cause confusion if they are editing a show that won't air for a week and choose to add the playlist contents. Also would it still schedule the playlist for that show or would we want to mark it as "already scheduled" and thus try to avoid having it scheduled again. I'm not looking at the code but I did use a simple flag to check whether a show should have a playlist added. I guess the question is what is the intended use case for this "add playlist contents to show now" ? What problem are we trying to solve, is it solving anything beyond providing the user with feedback that the playlist scheduling does do something ? I'm not against it, but I want to make sure that it is needed before I go through the trouble of coding it as I'm not sure how it would work in the code and the UI has a bunch of janky jquery. So I'm  just trying to think high level here and then wade in and see what is easily doable.

**Comment by frecuencialibre** [comment]
> I'm not sure I understand the podcast aspect of proposal 1.
Podcast downloading happens independent of the automatic playlist - but the API event is used to trigger both the automatic playlist scheduling and podcast downloading - this is the bug highlighted in #129 and fixing it will make both of these independent of either someone going to the website or a track being played.

right. proposal 1 is dependent on first closing #129.

>  we run into the issue that shows and show instances are different things and each show can have many show instances

Perhaps the button text could change based on whether you are editing the show or the show instance? if you add playlist content to the entire repeating show we should also somehow communicate that for now the contents added would be identical. would they then update later upon the the API event? i don't like this complexity... 

> There was a request to enable the scheduling of playlists for a whole time range for a certain show

the use case described in #382 to me seems like an example of how people are trying to use automatic playlists as a kind of catch all, which is a clear symptom of the lack of clarity in the UI that we're addressing here. if he already has the tracks weeks ahead of time, then he's not needing to download them programmatically. i'd guess that @freemanpolys, like me, probably just needed to be able to repeat the playlist untill the show was full. however i'm proposing that we address that need (if possible pre-beta) via enhancements to playlists or smartblocks. basicly to try to get "scheduled playlists" to promise via the UI to a single specific something, and then do it well.

> So I'm just trying to think high level here and then wade in and see what is easily doable.

fabulousness. laser focus on beta ftw!!! I intentionally didn't state this in my last comment but honestly, my vote is for proposal 1: 
- simplification almost always improves non-dev user experiences
- we'd be sticking with the single, main, well-established content adding workflow
- we'd probably have fewer support/feature requests coming in from folks using this as a catch all.

but since i'm not in the code i'm deferring to you man! (or anybody else who can chime in asap!)

bonito día, hasta pronto

**Comment by Robbt** [comment]
Ahh. I see proposal 1 is to remove the functionality all together. As this is critical for my station and the only option we have for automated scheduling I'd argue that it doesn't make sense to remove it. I do think that we could refine it further along the lines of changing the name. We also need to make it clear when the scheduling happens to a new user. I'll look at the code and see what modifications can be done.

I know that for stations that do any syndicated programming this feature is useful as it is.

**Comment by frecuencialibre** [comment]
now that i'm thinking of it, i've never actually tested.

I proposed number 1 assuming that adding a smartblock set to play the most
recent podcast right into the show would work as well. would it? hopefully
I'm stating this clearly. downloaded podcasts then become available as
conventional tracks, right?

**Comment by Robbt** [comment]
Yeah, well what you were proposing was replacing the playlist with the smartblock only option ?
That would simplify things but it still wouldn't on its own provide enough flexibility to be able to say have a station ID at the beginning and PSAs after the smart block is over. If we moved these into their own section than that might work. But I'm not sure how that would work without drafting it. I think the biggest challenge for the current workflow is showing people how it could work and also testing the more complicated arrangements of smartblocks as people have ran into bugs such as #458 - I have a PR that I started working on to add smartblocks but I didn't spend enough time writing the more complicated tests because I had to figure out how to use the database in the test. Anyways, there is more to work on. 

I was thinking about it earlier and one idea I had was to make the time it explicitly schedules before an option defaulting to 1 hour. Then we could have an option called "now" or a check-mark that says automatically schedule all shows. This wouldn't actually populate the database forever but we could program it so that whenever a show instance is created for this show it "adds the scheduled playlist" and for all future existing shows. This would mean that if someone were to browse to a future event on the calendar it would in theory then populate the tracks. 

In addition we could limit it to say "only schedule X(dropdown) or time period input) into the future, which could keep it from getting to far ahead.

That is my way of trying to provide what is probably a too complicated layout but I will maybe mock up some prototypes and see what actually looks best.

**Comment by frecuencialibre** [comment]
ok so Robb and I talked by phone and i finally got it my proposal 1 wouldn't work. basically smartblock contents are determined in the moment they are added to shows. hence it wouldn't work to add a smartblock that plays the most recent podcast to a show, since LibreTime won't continue to query the database for the most recent episode. 

updated mockups for review:

First, the entire "edit show" modal. i'm including this here to show an updated order of sections, and also that they appear closed by default. section order and open/closed state is a separate issue, but is relevant here since i've removed the first "Auto-schedule playlist?" checkbox entirely.
![screenshot from 2018-10-24 15-46-20](https://user-images.githubusercontent.com/36803137/47461073-85d98180-d7a5-11e8-9439-bea4caca8353.png)

And second: my updated draft of this functionality section: 
![screenshot from 2018-10-24 15-47-18](https://user-images.githubusercontent.com/36803137/47461308-1a43e400-d7a6-11e8-995a-aee432e286b3.png)

**Comment by frecuencialibre** [comment]
several candidates:
- "Auto-updating Playlist"
- "Auto-refreshing Playlist"
- "Scheduled Playlist"
- others?

anybody want to chime in  here?

**Comment by Robbt** [comment]
What about 
- autoloading playlist
- automatically scheduled playlist
- automated playlist

**Comment by frecuencialibre** [comment]
iḿ cool with whatever the majority says. haha majority in a conversation between two.

**Comment by Robbt** [comment]
So in order to change the behavior to schedule more than an hour in advance this code would need to be refactored - https://github.com/LibreTime/libretime/blob/7beadd05b004024d2513408391ac9f336a5ee7fe/airtime_mvc/application/common/AutoPlaylistManager.php#L65-L80 

I'll have to think about the best way to do this. Also above the interval that it checks is set to every 60 which I would assume to be minutes and the comment might just be wrong - https://github.com/LibreTime/libretime/blob/7beadd05b004024d2513408391ac9f336a5ee7fe/airtime_mvc/application/common/AutoPlaylistManager.php#L7

**Comment by JohnnyC1951** [comment]
>>Also above the interval that it checks is set to every 60...
It doesn't seem to fire if the the playing track is very long. IE if a 3 hour show track is playing, followed by a news autoplaylist which should have been updated :\ It seems to fire if its closer than 60mins AND a track changes.

**Comment by Robbt** [comment]
So I'm thinking of making the $future variable in the _upcomingAutoPlaylistShows function either be a predetermined variable or else removing it completely and just looking at all future show instances.

Then adding the customized DateInterval into this function. https://github.com/LibreTime/libretime/blob/7beadd05b004024d2513408391ac9f336a5ee7fe/airtime_mvc/application/common/AutoPlaylistManager.php#L25-L36 

In order to do this we need to modify airtime_mvc/application/forms/AddShowAutoPlaylist.php I'm looking at my previous [PR](https://github.com/LibreTime/libretime/pull/55/) to see all of the stuff I changed when I wrote this in the first place.

**Comment by hairmare** [comment]
> just looking at all future show instances.

Would shows without the "End Time" settings need special consideration here?

**Comment by Robbt** [comment]
In regards to the shows without End Time, I think the show instances are only created when triggered either by time progressing(not sure the specific mechanism) or when someone browses in the calendar. So if someone browsed like a year into the future, show instances would be created for any parts of the calendar viewed. 

So keeping that in consideration we would just iterate over all of the show instances that have been created through this mechanism thus far. Then the buildAutoPlaylist code would have to iterate over each of these instances and check and see if the specific timeframe for each of them has been passed. For instance you could have shows that you want to schedule "now" and you could have show instances that you only schedule within 30 minutes of their airing. 

The only issue I see with this is that the number of instances that we are iterating over could grow quite a bit. For instance if for some reason a user had browsed a couple of years into the future every weekly show would have 52 show instances, multiply this by 24 * 7 and we still have around 8736 show instances a year. I don't think this would be too processor intensive since each only has the playlist built once. But iterating over thousands of entries is more than iterating over less than 10 entries. 

So the question is should we leave this open ended or set up an arbitrary cut-off like the autoPlaylist won't schedule more than a year in the future.

The other decision that needs to be made is for the drop down that allows users to select X unit of time into the future. I'm going to look into the work I did with the smartblock and probably just reuse that where you can use a number and unit of time.

**Comment by frecuencialibre** [comment]
awesome that you've been able to make some progress on this one. 

luckily we're able to make changes to the UI design based on your evaluations of the complexity of implementing different options. And now we've had a few weeks to be able to come back to this with fresh eyes. 
- The select field UI option successfully communicates to the user that a task needs to happen in the background in order for the show to have content, BUT the feature of being able to decide 5min vs. 7 hours isn't actually that critical IMO.
- Would it be any simpler to code the button that fills the show now than the select field? If so, perhaps we should reconsider that initial option, possibly with help text in addition to the tooltip. In these two weeks I've also seen that it's possible to visualize, using the existing UI, exactly what is being scheduled: 1. create a playlist that contains smartblocks, they appear within the playlist with the smartblock name and details ONLY, no specific tracks. 2. add that playlist containing smartblocks to a show. now you'll see that the smartblocks are converted to specific tracks. This could be easily shown in a screencast.
 

And then loose ends: 
1. i think i saw a PR with some sql. did that fix the settings by default issue mentioned in this thread?
2. regarding naming. we have the following:
- autoloading playlist
- automatically scheduled playlist
- automated playlist
- "Auto-updating Playlist"
- "Auto-refreshing Playlist"
- "Scheduled Playlist"
The screencast i describe above made me think about "autofilled" too. keep chewing on this one....

**Comment by hairmare** [comment]
> So if someone browsed like a year into the future, show instances would be created for any parts of the calendar viewed.

That reflects my experience as well... In the case of smart block based shows I'd probably rather have them scheduled close to when the actual show airs rather than scheduling them as soon as a new instance is created. 

Maybe the scheduling thing could happen on all shows but only schedule the first instance for any given show?

**Comment by hairmare** [comment]
> 1. i think i saw a PR with some sql. did that fix the settings by default issue mentioned in this thread?

The last one I remember was #581 but that only changed stuff related to podcast ingesting.

**Comment by Robbt** [comment]
I think that this change is probably unneeded at this point since it will require a bit of refactoring and probably make the UI more confusing.

Since nobody seems to need it I'd suggest that the following changes instead.

- [ ] Make the time that a autoplaylist is scheduled before displayed in the UI w/o an option to change it
- [ ] Add the tool tips that provide a more detailed description of how automatic playlists work
- [ ] Write documentation explaining this in even more detail ( ie copy the stuff from the wiki to the docs)
- [ ] (optional) Modify what happens when you right click on a show w/ an auto playlist in the calendar to have a build autoplaylist now action
- [ ] (optional) Make the time a autoplaylist scheduled globally configurable via the settings vs. on a per show basis - this will change what is displayed in the text under auto playlist
- [ ] Fix #129 - so that there isn't a big bug waiting to bite people for no good reason

**Comment by JohnnyC1951** [comment]
Perfect

**Comment by frecuencialibre** [comment]
glad this is getting clearer. i could help with tasks 1 to 3.

wouldn't 5 require a similar level of refactoring?

any thoughts on keeping the button?

**Comment by Robbt** [comment]
I think that the refactoring for 5 would simply involve replacing the date interval here https://github.com/LibreTime/libretime/blob/7beadd05b004024d2513408391ac9f336a5ee7fe/airtime_mvc/application/common/AutoPlaylistManager.php#L70 with a datetime unit from the database that can be changed via the admin settings. Since this is global we don't need to iterate over each of the fields. 

It still might be an unnecessary customization and it is unclear how far into the future it would make sense for people to automatically schedule all of their shows.

**Comment by JohnnyC1951** [comment]
Does editing a show instance affect this?

**Comment by frecuencialibre** [comment]
here goes another round of subjective opinion :)

**Finalists:**
- autoloading playlist
- automatically scheduled playlist

**Candidates i'm leaning against:**

- automated playlist
- "Scheduled Playlist"

Neither of these are terribly meaningful. automated also sounds like an autoDJ kind of feature, which this is not.

- "Auto-updating Playlist"
- "Auto-refreshing Playlist"

> suggest that there is something already scheduled that will be reloaded or updated when the show will be empty and/or its contents will not be changed, just new contents loaded.

**Comment by JohnnyC1951** [comment]
Show Auto-Loader
SAL for short (on labels)
