### ISSUE TITLE
All done here and I cleaned up behind me too.

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#564]
SLATFATF

**Comment by JohnnyC1951** [comment]
Please delete. Gone anyway.

**Comment by hairmare** [comment]
I just blocked this user on a personal level (as in from my account's setting) as described in https://help.github.com/articles/blocking-a-user-from-your-personal-account/.

If this has any side effects to him interacting here, those where not intended but welcome anyway.

Now that we can delete things: his last statement in this issue was deleted, as per his request:

> Please delete. Gone anyway.
