### ISSUE TITLE
ShoutCast 2.X

### ISSUE THREAD

**Issue by teris** [LibreTime/libretime#568]
I found that I could not connect to a SHOUTcast server v2.5.5.733.

Would it be possible to install an option to choose between IceCast, SoutCast & ShoutCast2?

Likewise, would it be possible either to choose during installation or even to install both systems in parallel? (Icecast & ShoutCast)

That would be nice!

Error: Facebook API still does not work yet. That's too bad!

**Comment by Robbt** [comment]
The connection with shoutcast is handled by liquidsoap. Can you post any errors from that log.

**Comment by teris** [comment]
Thank you for the fast reaction.

As for shoutcast I know a little bit. The official developer wiki is still online and well maintained.

Nullsoft is working on Winamp again after only 5 years and thus also on SC_Tran and SC_Serv

Concerning the installation of SC_Serv (Shoutcastserver) I can gladly provide you with a SHELL.

The real problem with the connection is that a selection option must be created to distinguish between Shoutcast 1.X and 2.X.

I can also send you further explanations by e-mail.

Nevertheless, I will respond to # 456 and analyze the problem again.

Sincerely Teris

**Comment by Robbt** [comment]
Ok, creating alternative selections for shoutcast 1 vs 2 sounds like the way to go. I suspect that this would actually require a modification to the liquidsoap script (in addition to the UI tweaks in PHP and the connecting glue). Since as I mentioned above liquidsoap is what handles the actual connections to streams etc. I don't know if this is on the top of anyones agenda but it is probably doable if someone is willing to wade in and discover the proper config. You could also look at the liquidsoap project to see if they already have done any work here. Since LibreTime provides a icecast server that is used by default this won't affect most people unless they are using an external shoutcast host or set it up themselves.

**Comment by hairmare** [comment]
I can't seem to find anything regarding differences between [SHOUTcast 1 vs 2 in the liquidsoap docs](https://github.com/savonet/liquidsoap/blob/387d7634c6ab563bdada857f97b0b430a53d15ef/doc/content/shoutcast.txt) for `output.shoutcast`. It does seems possible to stream to icecast and relay that to SHOUTcast as an alternative.

**Comment by hairmare** [comment]
If anyone wants to try out stuff with SHOUTcast and not touch closed code... I recently stumbled upon some open source servers.

* https://github.com/StreamMachine/StreamMachine
* https://github.com/innovate-technologies/Cast

In this case that the SHOUTcast server is installed on an external server shouldn't make a difference. In some cases connection issues can be worked around by connecting LibreTime to a local instance of something like the servers above (or icecast) and relaying that to actual SHOUTcast (or a SHOUTcast SaaS provider).

A "did you try it on liquidsoap 1.3.x?" also applies to this issue. There were some changes to parts of liquidsoap that should have a positive impact on SHOUTcast. #192 has details on how to get onto 1.3.x. 1.3 has TLS support and possibly fixes for the streaming parts (although I'm not sure about SHOUTcast v2 protocol support).
