### ISSUE TITLE
Re-analyze library

### ISSUE THREAD

**Issue by matejb123** [LibreTime/libretime#592]
I'm sorry if this is already possible but haven't figured out how to do it...
Let's say I upload some files and later find out ID3 are missing and replaygain could not do the processing because of this.
How to re-run analysis and update of database of songs already in the library?
Thanks
Matej

**Comment by hairmare** [comment]
These is an untested script that does silan re-analysis in `utils/airtime-silan`. Sadly a similar script for replaygain re-analysis doesn't exist (yet). Personally I have a need for EBU R128 analysis instead of replaygain, if I get to coding something in this area it will be that (and I'll also need to implement some way to do re-analysis for my case).

**Comment by JohnnyC1951** [comment]
I had it working. But I used the airtime version on silan (Daniel James Version)..
