### ISSUE TITLE
 Automated installation

### ISSUE THREAD

**Issue by Dr-Satan** [LibreTime/libretime#596]
Hi, excuse me but the automated installation page is missing 
https://libretime.org/manual/automated-installation/

How to install Libretime easily on a ubuntu server ?

**Comment by Robbt** [comment]
It is installable via the install script. It's best installed on a dedicated server and Ubuntu 16.04 is the best right now.

**Comment by frecuencialibre** [comment]
instructions here: http://libretime.org/install/

the automated installation page was intentionally deleted because it contained out of date info.

todo: remove references to deleted pages in documentation

**Comment by Dr-Satan** [comment]
Thank for your answer but how to download and extract the LibreTime repository ? From which source and in which server directory?

**Comment by Robbt** [comment]
I just added the instructions to install.md here they are - 

You can download LibreTime from our [github repo](https://github.com/LibreTime/libretime) In order to run the latest codebase you can click the green Clone or download button. It is recommended to type ``` git clone https://github.com/LibreTime/libretime.git ``` (if you Debian based system lacks git then you can type ``` sudo apt-get install git ```) and this will download the source code to your repository. You can also click Releases and download a tarball of our latest releases. You will then need to extract this archive into a directory on your server. It is not recommended that you install LibreTime on the same computer you are using as a desktop. So you will probably need to use wget for instance ```wget https://github.com/LibreTime/libretime/releases/download/3.0.0-alpha.6/libretime-3.0.0-alpha.6.tar.gz``` and then extract it by typing ```tar -xvzf libretime-3.0.0-alpha.6.tar.gz``` in the directory you downloaded it into. 

Let me know if this makes sense, if not I can clarify and also update our docs to make it easy to understand.

**Comment by Dr-Satan** [comment]
Thank you very much for your explanation, I will opt for a git clone. I want to install it on a remote server ubuntu 16.04. In which directory would you advise me to clone Libretime ?  (home ? root ? etc ? bin ?)

**Comment by Robbt** [comment]
I'd put in a /home/user directory of whatever login you use to ssh into it but it doesn't really matter. Although you do need to run the install with sudo but I think that is in the docs.

**Comment by frecuencialibre** [comment]
i'm closing this since it is more of a support request that appears to have been answered. @Dr-Satan note that for support requests you can also post in the [forum](https://discourse.libretime.org/). thanks all!

**Comment by hairmare** [comment]
There are still some links that now point to 404 since our recent cleanup

https://github.com/LibreTime/libretime/blob/aa2c12600aacdc105e7872ad81cfb71417bea50c/docs/manual/using-the-airtime-import-script/index.md#L44
https://github.com/LibreTime/libretime/blob/5b822afe14046157a8d9fbdff103eb383673e6be/docs/manual/upgrading/index.md#L22

I didn't find the time to clean them up since they have quite some context...

**Comment by Dr-Satan** [comment]
Thank you very much. I created according to your instructions a user and cloned the repo in. The whole installation went very well only there I'm stuck on the login page, what are the default login/mdp please?

**Comment by Dr-Satan** [comment]
I was never asked for a password at the web installation (I set everything by default)

**Comment by Dr-Satan** [comment]
I find the problem : Chrome. It work fine on Firefox

**Comment by Robbt** [comment]
Ok, what was the problem with Chrome vs. Firefox ?

**Comment by Dr-Satan** [comment]
After the web installation, at login (admin/admin), on Chrome we are redirected to the index without having been connected

**Comment by hairmare** [comment]
> I find the problem : Chrome

This is rather weird, I have been using Chrome as my main browser with regards to anything related to LibreTime. Maybe a Chrome extension is interfering with the login page. You might want to try disabling extensions to get Chrome to work.

**Comment by Dr-Satan** [comment]
I found the extension guilty, it's the google data saver :/
https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac?hl=en
When it is activated, it is impossible to connect

**Comment by frecuencialibre** [comment]
@hairmare in response to your comment and re-open, i already see both of the lines you mention fixed in https://github.com/LibreTime/libretime/commit/954713763a5df2026e7adf292623e4ccccd4492c

unless you're referring to other broken links, i'd just assume close this.

also, do you know of a way to check for 404s in the docs programmatically?

**Comment by hairmare** [comment]
Yupp, I always get distracted trying to figure out what's up with `docs/manual/using-the-airtime-import-script/` when I look at this again. Closing it now.

Re the link checking, we could use something like [blc](https://www.npmjs.com/package/broken-link-checker) in the CI pipeline. That wouldn't help us find unreachable pages though.
