### ISSUE TITLE
Problem: Include phing in vendor when building for release

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#642]
When the release tarball is built, it includes all php dependencies from composer under `vendor/`. The `composer.lock` references the `phing` dependency, which is missing from `composer.json`. Because of this it is downloaded when running composer installer. Bundling it in with all the other dependencies would allow me to build Debian/Ubuntu packages without requiring the build container having access to the Internet.

**Comment by hairmare** [comment]
phing gets removed from the full tarball because it's huge and we don't even use it...

https://github.com/LibreTime/libretime/blob/0ccf4da1e6aa9e9803501466c8e38ab01f5b66d0/dev_tools/release/release.sh#L75

The `vendor/` parts of the tarball should be good to go as is, no need to run composer install as that has already been done. Can you skip calling composer? Would that work?

**Comment by paddatrapper** [comment]
I'll try and see. As far as I can gather, composer only installs phing and doesn't do anything else, so it should work

**Comment by Robbt** [comment]
Cool. This makes sense. Let me know and I will delete the PR I put together.

**Comment by paddatrapper** [comment]
I'll need to wait for after alpha.6, as I'm having issues with the DOS line endings again... For some reason the patch I was using to fix it is no longer applying correctly. I have managed to build it correctly, but need to test it now

**Comment by paddatrapper** [comment]
After testing, I have been able to remove the composer call with no issues. I'll now close this
