### ISSUE TITLE
Problem: Default media store permissions are wrong

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#663]
**Describe the bug**
When the setup creates the default media store (`/srv/airtime/stor`), it gives it the default 755 permissions to www-data:www-data. This causes airtime_analyzer to fail to import files due to permission errors. It should rather create the media store with 775 permissions so that airtime analyzer (libretime-playout:www-data) can write to the directory correctly.

**To Reproduce**
1. Step through the installer
2. `ls -l /srv/airtime/`

**Expected behavior**
The directory (and all below it) should be owned by www-data:www-data and have 775 permissions.

**LibreTime version:**
3.0.0-alpha.6

**Installation method:**
 - OS: Ubuntu
 - OS Version 16.04.5 LTS (Xenial Xerus)
 - Method: [deb](https://cloud.paddatrapper.com/s/id2opdGcs5jGde9)

**Comment by Robbt** [comment]
Ok, so I was wondering why we weren't having this issue for other releases and the reason is that we have the owner of the airtime_analyzer process as www-data not airtime-playout. 

So the question is should we change the owner of airtime_analyzer to airtime_playout and change the permissions or vice versa. I think we should go for consistency where it makes sense between the two install processes. Thanks again for putting all of the work into the deb, this is awesome to finally have something that people can install.

**Comment by paddatrapper** [comment]
I can change it pretty easily in the Deb. Not sure why I thought it was owned by airtime-playout...

**Comment by paddatrapper** [comment]
Fixed in packaging git. It will in included in the next package release
