### ISSUE TITLE
Problem: Vagrant base boxes lacks libvirt support for ubuntu xenial

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#674]
The Bento base Ubuntu Xenial box does not support libvirt. This causes issues with Debian vagrant boxes, as this is the default provider. This could also affect the other base boxes, but I still need to check...

Documentation of how to use Vagrant for LT also needs updating:

http://libretime.org/vagrant/

https://github.com/LibreTime/libretime/wiki/Vagrant-Developer-Setup (to be merged into the website docs)

**Comment by hairmare** [comment]
I've been using the [generic roboxes](https://app.vagrantup.com/generic) for all my libvirt based testing (both the bionic and xenial boxes) so if we want to switch to boxes that work for everyone those might be a good idea. I usually prefer to use libvirt based boxes on Linux since VirtualBox can be quite a resource hog compared to libvirt. Using boxes that support both providers would make sense since we could use the same boxes on MacOS with VirtualBox as well (I use both platforms for LibreTime development).

**Comment by paddatrapper** [comment]
By the looks of things, those boxes support both libvirt and virtualbox, so they should work perfectly for our use cases. I'll see about opening a MR later today changing the Vagrant file
