### ISSUE TITLE
Clarify podcast settings and workflow

### ISSUE THREAD

**Issue by frecuencialibre** [LibreTime/libretime#690]
Podcast track metadata override settings currently exist in two places: station-wide general settings, and on the edit screen of individual podcasts. 

Currently "The individual override is only used if the global setting is turned off." - https://github.com/LibreTime/libretime/pull/659#issuecomment-453847011 

I personally find this confusing since i think a user would have no way of expecting that behavior, but wanted to hear other opinions.

I'd like to propose that 
1. we actually remove the "Podcast Album Override" setting from station-wide general settings. 
2. the individual podcast metadata overwrite checkbox be enabled by default.
3. the individual podcast metadata overwrite checkbox do what it says on the tin. ;) 
possible label: "Overwrite episode metadata tags", and tooltip: "Overwrite downloaded podcast episodes' "Artist" metadata tag with the Podcast Name specified above. This tag can then be used as a search criteria by a smartblock. [More information](http://libretime.org/???)"  The docs could then cover that the album is also overwritten for backwards compatibility, and that the metadata will be overwritten if empty even if this checkbox is unchecked.

**Comment by Robbt** [comment]
Yeah this is tricky, basically right now we have a always override and always create smartblocks option turned on by default due to a previous change.

Now that the podcasts include the generate smartblock and playlists button and we could simply enable the override by default it might make sense to remove the global setting or just disable it by default.

Or we could just always override the metadata and not provide an option to disable it.

Or we could make it so that if the global setting is enabled the checkbox for the individual podcast is always checked thus removing some of the confusion.

My suggestion as a compromise that doesn't remove functionality (ie we'd need to remove the automatic smartblock creation if we removed the always override option) is as follows.
1.  Enable the individual override by default for newly created podcasts 
2.  Disable the global settings for both override and playlist creation by default.
3. If global settings override is enabled then make the individual override option always enabled and add an explanation to the tool-tip.

The other option in terms of simplifying the UI and removing choices is to just always override the track metadata and remove both the global and individual podcast override option. This seems like it'd be a good idea but there might be some times this would need to be disabled.

I am not sure about whether we should enable or disable the global setting by default but I agree that we should have the two settings sync up to avoid confusion at the very least.

**Comment by frecuencialibre** [comment]
> The other option in terms of simplifying the UI and removing choices is to just always override the track metadata and remove both the global and individual podcast override option. This seems like it'd be a good idea but there might be some times this would need to be disabled.

what would be that use-case for which one would _not_ want to overwrite podcast track metadata? i can't really think of what it might be given that the whole point of this podcast content type is to _automate_ recently published episode downloading and scheduling. ...i guess if you wanted to be able to search your library for podcasts that did have meaningful metadata then you'd want to not have had it nuked. would it be possible to _append_ the podcast name to the artist tag rather than overwriting it and then query using the "contains" modifier?

if we did append-to rather than replace metadata, then i think we should axe both settings, and i think that would be best.

**Comment by Robbt** [comment]
We are still using Album for the metadata and I'm pretty much thinking the only reason we are matching the Artist field is so that the stream metadata can have it and we will still be using Album for the pre-generated smartblocks etc. We could possibly append on Artist, and rewrite/override on Album & Title.

But one reason I could see it being a good idea to provide an option to not override is if you were using RSS to distribute files and not for an episodic podcast show or for a podcast that aggregates different shows that each would have their own metadata. It's not immediately clear but we should make a decision on it.

**Comment by frecuencialibre** [comment]
> We could possibly append on Artist, and rewrite/override on Album & Title.

sounds good. 

> using RSS to distribute files

interesting. ok sure, let's keep the setting. so then we're back to figuring out site-wide vs. individual podcast.

**Comment by Robbt** [comment]
I think it'd be cleaner if all of this was done in a separate PR especially since #659 got gummed up with all of the other commits due to me pausing and resuming development on a fresh branch vs. the initial one.
