### ISSUE TITLE
Include global intro and outro autoloading playlist

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#693]
**Is your feature request related to a problem? Please describe.**
The basic idea here is that you may want to have a set of station-wide intros such as station IDs that always air at the beginning of a show and you can't rely upon your DJs to always include these. In addition you may want to change your intro playlist for all of your shows say to promo a certain event but don't want to manually edit each of the auto-loading playlists for every show to implement the change. In addition you might want to have a track fill in at the end of every show especially if there wasn't anything scheduled in the track list. An outro playlist would allow for a universal scheduled playlist that could include a time remaining smartblock and so it would always fill in if a show isn't scheduled manually or by the playlist for some reason. 

**Describe the solution you'd like**
Add an intro and outro playlist select from the general setting page. If an autoloading playlist is enabled for a show then the intro would be scheduled before the content of the show. If an outro playlist is selected it would attempt to be added after the content of the shows playlist.

This workflow would allow for a flexible interplay between individual DJ scheduled shows and a stationwide identity and the insertion of sponsorships or underwriting at the beginning or end of shows. 

**Describe alternatives you've considered**
Another alternative would be to enable playlists to contain other playlists so you could have a station wide "intro playlist" that contains different smartblocks of PSAs, events etc. But this would require refactoring the playlist code to allow playlists to be embedded in playlists and this isn't allowed because of potential recursion loops of playlists containing playlists that had the first playlist. 

Another idea was to have a intro playlist and outro playlist for each show that could be selected. This would be more flexible but also more complicated for users to set up and not as straightforward to conceive. Further complicating this idea was to replace the single show autoloading playlist with a playlist of playlists that could be ordered for each show but while this would be powerful it would also be complicated.

Another more complex idea would be to have the intro playlist tracks mixed and play simultaneously with the scheduled content via liquidsoap input mixing, so that an individual shows schedule wouldn't be changed but this would require to much modification to the current setup and could result in some goofy situations.

**Additional context**
The current decision that would need to be made on this would be what options there are to override this intro and outro on individual shows. The simple way of doing this would be to have it only apply to shows that have autoloading playlist enabled on them. That way you could disable it on shows that you didn't want to have something inserted in the beginning. In addition if you wanted to use it just to fill in a station ID and an outro but planned on manually scheduling the content you would enable the autoloading playlist but not select a playlist in the dropdown.

**Comment by Robbt** [comment]
So just in terms of how I am thinking how this will be done. The autoloading playlist for the specific show will be added first and then the intro will be inserted in front of it. This should allow any time remaining blocks to attempt to fill up the time in the front of the show from their playlist instead of preventing the actual content from being loaded. Then the outro will be added onto the playlist.

In addition I am thinking that program managers should be able to access the setting for this and so it might make sense to create a new section aside from general that program managers can access in the settings.

**Comment by Robbt** [comment]
Another thought/question is whether intro and outro playlists should be added to shows without autoloading playlists turned on. 

My initial thought is that they would only be applied to shows with an autoloading playlist but you might want to have a way of turning them on or off for specific shows. And you might want to add a station ID w/ intro playlist to even shows that were manually scheduled by DJs. I was thinking that if a show didn't have a autoloading playlist but you wanted to opt-in to the global intro & outro you could enable autoloading DJ and not select a playlist. The issue with this is that it would show the autoloading DJ clock and no longer show whether a show was completely scheduled or not. This could be fixed by showing the red ! or orange ! arrow on autoloading playlists that were in the past or didn't have a autoloading playlist selected for them but this would require tweaking the jquery some more and could be time consuming for a minor fix.

**Comment by frecuencialibre** [comment]
Some way of "sprinkling" "jingles" across an entire schedule would be extremely valuable at our station, and is something that is expected by users who have used other radio automatization software. There's also some overlap here with #335, for example. 

In order to accomplish such "sprinkling", I personally would like to be able to add this to _all_ shows, not just those with autoloading playlists. frankly so far i've had limited success explaining to radio collective members what autoloading playlists even are and how they work. :( hopefully this will change with time as folks become more comfortable, but for now I'd like to avoid that this feature depend on another feature that is i think is considered by many to be an "advanced" technique.

when we talked by phone, i remember we agreed that being able add a playlist to the start/end of every scheduled show was a possible compromise between LibreTime's strict scheduling model, and this need to inject content. I'm guessing that the main alternative approach would be make modifications directly with liquidsoap as is suggested in order to prevent dead air: https://github.com/LibreTime/libretime/issues/229 https://github.com/LibreTime/libretime/issues/462 . my concerns with the _bare metal_ liquidsoap approach that would inject tracks amongst scheduled programming are that
-  it would either require modifying code (which nobody at my station is gonna do), or building a [UI](https://github.com/LibreTime/libretime/issues/229#issuecomment-431522247), and 
- it would be potentially confusing and disruptive since it breaks entirely with LibreTime's strict scheduling model

> Describe alternatives you've considered
from a user's perspective, i can imagine another section of the add/edit show dialogue that contains select elements that allow you to choose playlists to play at the start and end of the show. the default value of these select elements would then be configurable on a site-wide level. this would be useful in multiple scenarios beyond just jingle/ad placement, such as scheduling tracks at the end of shows that can be chopped off midway when the show ends. if checking "Repeat Playlist Until Show is Full ?" didn't overshoot the end of the show, this would be ideal.

my main concern here is how to communicate an accurate calculation of how much time is free within the "Schedule Tracks" modal and "Scheduled Shows" tab pane. ideally users would see some indication of the presence of the intro/outro playlists within the list of scheduled content, with updated time remaining calculations. however this wouldn't always be possible since intro/outro playlists are to be autoloaded and can contain smartblocks that return varying lengths of content. gotta think a little more about this one. 

in general i think the need to schedule jingles/ads/etc. addressed here, and also the need to prevent dead air, are the features most needed by production radios. thanks everybody!

**Comment by Robbt** [comment]
Yeah, the liquidsoap bare-metal liquidsoap approach would undermine both the log of tracks played (if we are using LibreTime as a source of truth) and building a UI for it would be very tricky in my opinion. I do think there could be some potential there that we might want to investigate.

I think the problem with autoloading playlists as we are calling them is that the they way they work with smartblocks and playlists is just a bit complex for people and requires multiple concepts that are somewhat novel to be understood before you can use them. The fact that smartblocks provide nearly unlimited flexibility is also way more complicated than say if we just had them match on a single term like genre. But that is getting away from here and I'll finish that thought on #657.

I'm not sure how we could refactor repeat playlist until show is full but that might be possible by revisiting it with the technique I used for the fill until remaining time smartblock.

**Comment by Robbt** [comment]
##alternative crazy idea## 
Another option would be to build a "sprinkling" UI that would be completely separate from the concept of INTRO & OUTRO but would intervene into the schedule at different points throughout the hour.
For instance you could have a show override template UI that would allow you to set cuepoints for instance. If you set one for 00 that would mean every hour it would insert this playlist. Then you could set a 23 cuepoint and the algorithm would look for the next track that ended as close to the 23 point as possible and insert a track from the playlist.

Another option would be to say "sprinkle 5 promos into this show", the algorithm when then crawl the show and spaced by tracks sprinkle promos in between tracks spaced accordingly. This would also happen along with the autoplaylist functionality.

Building the UI for this would be tricky and in reality we are probably thinking about a next gen instance of LibreTime and this is more or less just me brainstorming and capturing ideas that could be helpful then. It wouldn't be that impossible to imagine implementing it with the current setup though as the algorithm isn't horribly complicated stuff.
##even crazier idea##
Another option would be to have an algorithm that sliced and diced longer shows into shorter tracks in order to create cuepoints. This would require an algorithmic analysis to discover silence or breaks and if done by an algorithm could result in some awkward interruptions based upon false positives. But it could also be useful. When a really long track was identified in a show where there are no cuepoints it could be then analyzed, separated into smaller files and the promos added at these points. Ideally this could be verified by a human and incorrect cuepoints annealed back into a track. Like I said this is me more or less brainstorming at this point for what will probably be a future version of LibreTime.
