### ISSUE TITLE
Just stream music playlist 24/7

### ISSUE THREAD

**Issue by carloshs94** [LibreTime/libretime#714]
Im really sorry to ask this like that, but i dont really know where to ask for this.

I just want to have 10-20Gb of music in my folder and play the music in the playlist everyday. 

just repeating the playlist when its over. 

Is there any way to do it? i tried to make a show "forever" but the max time is 24h and i dont think that making everyday show is the way to go.

**Comment by Robbt** [comment]
This is outside of the scope of the current design of LibreTime. In fact I think what you are trying to do would be more easily accomplished by Liquidsoap in and of itself and/or perhaps another open-source tool like https://www.azuracast.com/ itself would help you meet your goal of a neverending broadcast from a pile of music.

But yeah LibreTime is designed for at most 24 hour shows. In theory you could setup a 24 hour show and a autoloading smartblock that was filtered to select any track with a length greater than 1 second in a playlist only containing that and the limit set to fill remaining time. And then you could assign it to each day and the station would populate itself with random music from your library but it wouldn't be a continuous playlist where each track is only played once and every song is played. It would be a different random selection for each day and that seems different than what you described.

So yeah I'm going to close this since it is more of a support request than a feature request and we encourage these type of posts to take place at the forum at discourse.libretime.org, but in general we don't make a big deal and will respond if you post them as issues. Feel free to either post on discourse or follow up on here with further questions if you think the idea I proposed sounds like something you'd want to implement with LibreTime vs. another piece of software.

**Comment by carloshs94** [comment]
Ohh, im really sorry, i didnt find the discourse forum.

Thanks for the azuracast recommendation. is just what i need. <3

**Comment by Robbt** [comment]
No problem, we don't mind, glad you found something that will work for you.
