### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by maydo** [LibreTime/libretime#759]
**Describe the bug**
A non well formed numeric value encountered

while moving tracks in scheduled shows (schedule track)
see img

<img width="434" alt="screenshot 2019-03-03 at 00 18 18" src="https://user-images.githubusercontent.com/27486434/53688828-54238900-3d4a-11e9-934b-7143ee2570f2.png">

**LibreTime version:**
a1c2d7b69

**Installation method:**
 - OS: [e.g. Ubuntu] Ubuntu 18.04

**Screenshots**

**Client (please complete the following information if applicable):**
 - OS: [e.g. Fedora] mac & win
 - Browser [e.g. chrome, safari] firefox, chrome

**Comment by Robbt** [comment]
Good catch. This is a 7.1 incompatibility. I have traced it down to this call.

https://github.com/LibreTime/libretime/blob/a1c2d7b69567ff55fdb1f33940e3018e3c04ec8b/airtime_mvc/application/models/Scheduler.php#L859-L862

which when I'm testing it is an unnecessary call because the $file['fadein'] and $file['fadeout'] are already in the expected format.

The reason it fails is that the code it calls doesn't play well with 7.1's new restriction on arithmetic with invalid strings - https://secure.php.net/manual/en/migration71.other-changes.php

https://github.com/LibreTime/libretime/blob/a1c2d7b69567ff55fdb1f33940e3018e3c04ec8b/airtime_mvc/application/common/DateHelper.php#L422-L445

It's not obvious what the best way to fix this is, but it probably doesn't involve altering the DateHelper because that could have unintended consequences. I'm thinking it might make sense to check and see if the fadeout and fadein are numeric and to only run the conversion if they are.

**Comment by maydo** [comment]
nice, thank you

**Comment by Robbt** [comment]
Thanks for testing and bringing this to our attention. This was a pretty big bug in terms of interfering with the software, glad the fix was relatively simple.
