### ISSUE TITLE
timezone variable is override in getWeekInfo($timezone)

### ISSUE THREAD

**Issue by nixhol** [LibreTime/libretime#785]
In the function `getWeekInfo($timezone)` it seems the `$timezone` variable is written before it is checked :  https://github.com/LibreTime/libretime/blob/adb8d8c01d7a392512ded62f1a282dbebd6df3cf/airtime_mvc/application/common/WidgetHelper.php#L18-L24

therefore it cannot work.
Expected behavior would be to check if it is passed to the function, and if absent to default to `Application_Model_Preference::GetDefaultTimezone()` : 
```
// Check if passed 
if ($timezone) { 
    $userDefinedTimezone = strtolower($timezone); 
    // if the timezone defined by the user exists, use that 
    if (array_key_exists($userDefinedTimezone, timezone_abbreviations_list())) { 
        $timezone = $userDefinedTimezone; 
    } else {
        // default to the station timezone 
        $timezone = Application_Model_Preference::GetDefaultTimezone(); 
    }
} else {
    // default to the station timezone 
    $timezone = Application_Model_Preference::GetDefaultTimezone(); 
}
```
(Code not tested and a bit messy...)

**Comment by Robbt** [comment]
Yep this does look like a bug. Do you know how to do a fork and pull request so that you can get credit for the fix ? I haven't written developer tutorials or compiled appropriate ones but it is pretty much a git standard thing.

Fork LibreTime, create a branch, push your commit to that branch on your fork and a PR will pop-up and you can submit it to the project and we can test and merge it.

**Comment by nixhol** [comment]
Sorry I don't have much time these days to do a clean PR. I don't care about the credit so if you want correct it yourself.
