### ISSUE TITLE
Proposal: Create a LibreTime Open Collective

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#796]
**Is your feature request related to a problem? Please describe.**
A community run project is often difficult for companies and individuals to support financially due to the nature of how the project is set up. There are also always fears about the sustainability of a project, as very few actually last a long time without some sort of funding.

**Describe the solution you'd like**
As described by @gusaus on [discourse](https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/), an Open Collective would allow us to collect money from anyone willing to pay for the continued development of LibreTime and distribute it to developers, pay for hosting and other on-going costs. I don't see that there will be much coming in, especially at the beginning, but it should be able to cover hosting at least with maybe some left for incentivising specific bugs and issues in line with our [development goals](https://discourse.libretime.org/t/libretime-development-priorities/51). More suggestions are listed [here](https://github.com/LibreTime/libretime/issues/782#issuecomment-479150383)

**Describe alternatives you've considered**
Another alternative is Patreon, but this is a proprietary system that is not business friendly (Open Collective is a 501c6 Non-Profit). Patreon also leaves the distribution of funds up to us, which would require much more setup on our part.

I would like to know what the thoughts are around this and if there are any queries or objections?

**Comment by Robbt** [comment]
I am interested in this concept, but perhaps as referenced in your previous suggestion that we move more open source radio projects under the auspices of LibreTime it makes more sense to build a free software radio project that can receive money to dedicate to developing free software. The challenge here is governance and determining a way to share decision making and responsibilities. As someone who has started a development cooperative and currently runs a 501c3 non profit in the US I understand that these sort of things take careful planning and consideration. So yeah I don't want to jump into getting money until we decide how we want to structure things since unlike a lot of free software projects we already have a community and are building off of the collaboration of a lot of people vs. the efforts of an any one individual.

**Comment by paddatrapper** [comment]
Yeah we definitely need some sort of set structure before this can happen. The main things I see us needing are a governing body that can approve invoice payment requests and a set way that it is answerable to the community. Perhaps that is a set number of people nominated and voted for by the community with each having a set term on the body. Perhaps that is people that the maintainers appoint. Either way the process needs to be clearly defined and documented.

I quite like the Debian way of doing things where the DPL is elected yearly and delegates responsibility to various committees. There are some restrictions about responsibilities that the DPL must delegate, but cannot manage himself. The full description of the structure and procedure is listed in the [Debian Constitution](https://www.debian.org/devel/constitution)

**Comment by gusaus** [comment]
To cut down duplication, we should reference contributor input from the Discourse post -https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84

@frecuencialibre https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84/17
> so, i’d vote yes to opencollective if we have clarity and transparency as to:
> 
> * a process for entering into the group of devs who are getting paid. eg. if you’re contributing a minimum of insert criteria here, then email gusaus and he’ll get you set up.
> * we can agree from the start that this money is merely a symbolic token of appreciation, and that our main shared goals are the health of the community and quality of the software.

@hairmare https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84/19
> I think we would need to set up some kind of foundation with a board of directors that has at the very least regular calls and maybe office hours to garner input and discuss allocation of funds. IMO right now of focus should be on growing the pool of Maintainers so the bus factor of the project isn’t just me and Robb.

@paddatrapper https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84/23?u=gusaus
> I think an Open Collective is an attractive idea. Being able to give key developers even a token amount would be useful. I am not sure there are many companies and organisations willing to contribute to LibreTime’s on-going development (this may well change after 3.0.0 though). It would be useful to have some sort of support structure set up before then though so that when potential backers to come, we have somewhere to point them to.

> We would need guidelines around who gets paid, etc. (Maybe some sort of bug bounty?) The project maintainers or project admins should probably be the ones managing the collective too, but we need solid guidelines around their selection and delegation too.

https://discourse.libretime.org/search?q=opencollective also brings up quite a bit of related discussion (mainly between myself and @Robbt) 

My views can still probably be summarized in the following comments:

https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84/18?u=gusaus
> The reasons for having an Open Collective on the top of this post are still valid… the concerns laid out by @robbt absolutely valid, not unique in OSS, and addressable.

> As mentioned in the tail end of [LibreTime Development Priorities](https://discourse.libretime.org/t/libretime-development-priorities/51/10?u=gusaus), I don’t think [a continuously updated and maintained version of AirTime broadcasters can depend on](https://forum.sourcefabric.org/discussion/18302/libretime-a-fork-of-airtime-due-to-stalled-development/p1) is achievable without a mechanism to directly collect and distribute funds.

> How we’d use Open Collective would be the next step, but I’m hoping (as someone who would like to use, provide, and contribute to community) we can at least make a decision and set it up.

..and further followup in the thread - https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84/24?u=gusaus 

> Many OSS projects on Open Collective are still trying to sort out a process. We’re already setting ourselves up to not only share ideas, but collaborate with complementary projects and communities. https://github.com/LibreTime/libretime/issues/782#issuecomment-479150383

> One such project, Open Broadcaster Software (OBS), provides some inspiration for how to incorporate Open Collective as a way to sustain. https://obsproject.com/blog/new-ways-to-support-obs-development

It would be ideal to get input from others regarding transparent financial incentive _as an option_ to sustain the project and enable contributor time.

**Comment by gusaus** [comment]
Quick followup wearing my Open Collective community member hat - 

* By default, LibreTime would join over [1000 OSS projects](https://opencollective.com/opensource#members) currently hosted by [Open Source Collective 501c6 (Non Profit)](https://opencollective.com/opensourcecollective). This includes hundreds of projects and communites with overlapping goals/needs from large CMS like [Wordpress, Drupal, and GravCMS](https://github.com/opencollective/opencollective/issues/1864#issuecomment-479364335) to complintary projects and orgs in the [radio, podcasting, community/public media space](https://github.com/opencollective/opencollective/issues/1864#issuecomment-477392802).
* Many of these projects and communites have/had similar concerns about governance/decision making/process for providing incentives while also ensuring that contributors could volunteer. 
* Helping alliviate these concerns and providing a support structure is one of the primary roles of the [non profit (501c6) we'd be part of](https://opencollective.com/opensourcecollective#about) as soon as we joined. 

Many of the questions regarding how to set up, admin, approve payments can be found in this section - https://docs.opencollective.com/help/collectives

It also looks like @alannallama, the ED of Open Source Collective, might have also reached out to have a conversation regarding any questions or concerns. https://github.com/opencollective/opencollective/issues/1864#issuecomment-477393846 

Might not be a bad idea to follow up with Alanna - we're also forming a #communitymedia collaboration space within the 1000+ member Open Collective Slack community https://slack.opencollective.com/

**Comment by Robbt** [comment]
Thanks for the summary @gusaus, this is the first mention of @alannallama attempting to reach out, but I think there is enough interest that we can research it further but I'd also like to have a real time conversation on this at some point with the stakeholders.

**Comment by paddatrapper** [comment]
@gusaus the issue isn't how to physically set the collective up and pay people out. The decision we need to make before this can go ahead is the processes around it - who decides which invoices get approved, how the admins are appointed, etc.

So I think we need to decide the following to have any hope of this happening:

* Leadership structure - appointment, decision making
* Hosting costs - approval, type
* Developer contributions - appointment, amount of reimbursement

# Proposal
## Terms

* Contributor - a member of the Contributors team of the Github LibreTime organisation
* Maintainer - a member of the Maintainers team of the Github LibreTime organisation
* Administrator - a member of the Administrator team of the Github LibreTime organisation

## Leadership structure

The project is lead by a board of Administrators. This board answers to the Contributors. It decides on the group of Maintainers (with the help of the existing maintainers) and administers the Open Collective. This means that members of the board have administrator accounts on the LibreTime Open Collective.

The maintainers are appointed by the board and are responsible for reviewing and merging patches as described in [C4](https://rfc.zeromq.org/spec:42/C4/). They identify and recommend members of the community who should be made Contributors to the board. The board then considers the recommendation before making the final decision.

Contributors can override any decision by the Administrators or Maintainers by means of a General Resolution. This involves creating a bug report against the [CoC repo](https://github.com/LibreTime/code-of-conduct) with the proposal. This proposal then goes through a period of review and discussion before being voted on by the Contributors.

## Hosting Costs

Any Contributor, Maintainer or Administrator can propose a project related to LibreTime (demo, website, documentation, etc) that will be funded by the LibreTime Open Collective. These proposals are considered by the board and if approved, the Contributor, Maintainer or Administrator can request refunds from the Open Collective by uploading the original hosting provider's invoice to be approved by the Administrators.

## Developer Reimbursements

Any Contributor, Maintainer or Administrator can request reimbursement for costs incurred relating to LibreTime (travel, conference entrance, etc). These requests must occur before the event. The board then considers the request and either approves or denies it. After the event, the Contributor, Maintainer or Administrator must submit an invoice to the Open Collective to be approved by the Administrators.

# Need to refine

* The General Resolution procedure - email, Github issue?
* Voting/Election procedure - email, [devotee](https://www.debian.org/vote/)?
* Reimbursement request procedure - email, issue on a Github repo?

**Comment by alannallama** [comment]
Hi! Alanna from the Open Collective team here. If you have any questions about how the platform works or how other groups have approached these questions, I'm here to help.

Social.coop uses Open Collective in conjunction with [Loomio](https://loomio.org) to make decision-making and governance easier. [Here's a case study](https://medium.com/open-collective/social-coop-a-cooperative-decentralized-social-network-c10980c9ed91) where they discuss how it works for them. Loomio is an open source tool purpose-built for this kind of distributed decision-making. Although it can also make sense to stick with the tools you already use (Github issues for example) instead of having to add another.

It's great that this discussion is surfacing important questions about who makes decisions and internal governance processes. On the other hand, I'd like to offer that you can make a start without having it all figured out. You could allow money to start building up in the Collective and begin funding small, totally uncontroversial things first, and work up to larger budget decisions that need a more robust governance structure in the future. Because Open Collective is fully transparent, there's automatically accountability and nothing is hidden from the community. This creates a trust margin that gives you some flexibility. Like with software, iteratively building governance processes usually works better than waterfall planning everything ahead of time.

All the best for this next phase of LibreTime as a project! Let me know if there's anything I can do to help.

**Comment by gusaus** [comment]
Thanks for unexpectedly chiming in here @alanna!

As Alanna suggested, we could begin by funding small, totally uncontroversial things first such as -

- Hosting cost for marketing and/or demo site(s)
- Sponsoring/participating/attending meetups, sprints, or hackathons that enables contributions and/or promotes LibreTime
- Contributor time for project management, community, outreach, marketing, or fundraising

Similarly, there are several benefits LibreTime can provide backers and sponsors ranging from website credits, radio/podcast spots, to community based barnraisers and hackathons. 

With Open Collective providing ways to transfer funds between projects and orgs, there are all sorts of ways both LibreTime and contributors can collaborate on projects, events, to providing services. 

Again, the best way to really get it would be to read over some of the [Open Collective docs](https://docs.opencollective.com/help/about),  [join the community](https://slack.opencollective.com/), and [apply to create a collective](https://docs.opencollective.com/help/collectives/create-collective) for LibreTime if everything seems cool.

**Comment by Robbt** [comment]
I'm ok with the proposal that @paddatrapper has put together. Currently the only 2 admins of the project/github repo are @hairmare, myself and @jmtrivial . We haven't heard from Lucas for a few months and Jean-Marie Favreau was added when we first launched the project because he was one of the co-signers of our letter to SourceFabric regarding the fork. I don't think he has really contributed or participated much since the inception. 

I think that we explicitly don't want to pay contributor's for any of the things that you mention @gusaus until we have a fair amount of surplus. I'd imagine that we are going to primarily be a volunteer project as LibreTime. If someone wanted to launch a business and do a SaaS competitor to all of the other tunekey radio automation systems using the LibreTime than that would be fine as long as they contributed all of their code and/or maintained a repo where they shared it as per the AGPLv3. I don't see this as being the role that LibreTime as a project would want to play. 

We also don't really have any hosting costs aside from DNS registration. The discourse forum is provided free hosting via discourse. If we wanted to replace Slack with the more open Zulipchat they would give us an unlimited messages and free hosting as an opensource project. We have a free travisCI project as an opensource project.

I think the biggest challenge I foresee is maintaining whatever organizational infrastructure we create and keeping it flexible and resilient enough that it can continue without becoming a burden on whomever chooses or is chosen to facilitate it. We have been doing pretty well with the C4 thus far which focuses exclusively on the code. The original contributor suggested that you did indeed need money for a project ZeroMQ brought in money through a separate company that paid for the marketing etc of the project and also did consulting.

NextCloud is another open-source project and they have a successful company that provides service and support to large companies seeking to install the software. They have stayed away from software as a service and don't provide any kind of hosting and allow end providers to do this.

I also think we should be rather open about our goals and visions and personal reasons for wanting this to happen. 

I personally am not against the idea but I don't necessarily see $ being an obstacle for the project right I have had some discussions with Ryan about the idea of seeking grants to fund a new overhaul of Libretime to get the UI modernized and mobile friendly and to finally deal with some of the underlying technical debt while refreshing what it is that we are trying to do.

I have been funded in part from work-trade with my Dad who also helps run the radio station I'm part of and via a grant from the Greater Columbus Arts Council through my station's non-profit. I would be happy to continue receiving funds but I don't know that they need to go through the project itself. 

As far as community governance goes, what I learned at Libreplanet was that you kind of have to boot the process by building something. Python built a governance model to deal with Guido stepping away as project lead. This project has always been made from the contributions of many and I think that the maintainers are a good stand-in for a governing council at this point. I don't know that we should necessarily bootstrap the C4 into our governing cycle.

I also don't know about how we would handle the idea that "Contributors can override any decision by the Administrators or Maintainers by means of a General Resolution. This involves creating a bug report against the CoC repo with the proposal. This proposal then goes through a period of review and discussion before being voted on by the Contributors."

This would also create a situation where we are equating stake in terms of contributions which makes sense from a code perspective but end-users could also be stakeholders in terms of the larger goals of the project.

I also am curious about Loomio.org, I think that it could be a useful tool to experiment with.

I guess my biggest hesitation in terms of creating an open collective is that it will just be a distraction from the goals of the project because there won't be sufficient funds for it to be worthwhile. I think we should have a pretty good idea that there are people who want to donate on a regular basis and also a list of specific goals we would spent the money on so as to encourage them to contribute.

Another thought on paying contributors is that it makes sense to fund things as an organization that we think are needed but nobody has taken the self initiative to actually do. We could also possibly integrate into something like https://www.bountysource.com/ to allow people to contribute to specific features.

I'm ok with the idea of starting an open collective but I would like there to be a consensus from the current participating maintainers that this is what we want to do. I'd also like to know who is planning on participating in the organization building and decision making process. If someone wants to setup an account on loomio.org to explore as a way to discuss this and other ideas to see if it helps guide us to consensus faster that might be a worthy endeavour.

**Comment by gusaus** [comment]
Ideally, we can solidify what @Robbt brought up in the last paragraph and set up subsequent issues to solidify the process.

> I'm ok with the idea of starting an open collective but I would like there to be a consensus from the current participating maintainers that this is what we want to do.

So it sounds like the only current participating maintainers we'd like to get consensus from would be @hairmare? I'd also take into consideration any other views from folks who previously chimed-in https://github.com/LibreTime/libretime/issues/796#issuecomment-482310972

Would be great if @frecuencialibre @hairmare could skim over and at least provide a 👍 , knowing that the next steps would be to work out the details regarding governance and decision making. 

> I'd also like to know who is planning on participating in the organization building and decision making process.

I'm assuming the current participating maintainers? Again it would be great to have folks chime in regarding what roles they could play in addition to what they're already contributing. 

> If someone wants to setup an account on loomio.org to explore as a way to discuss this and other ideas to see if it helps guide us to consensus faster that might be a worthy endeavor.

Seems like we just need 👍 from one or two folks to create the collective? I'd be happy to help setup.

**Comment by paddatrapper** [comment]
> Currently the only 2 admins of the project/github repo are @hairmare, myself and @jmtrivial . We haven't heard from Lucas for a few months and Jean-Marie Favreau was added when we first launched the project because he was one of the co-signers of our letter to SourceFabric regarding the fork. I don't think he has really contributed or participated much since the inception.

Perhaps we should look at appointing new/more admins?

> I think that we explicitly don't want to pay contributor's for any of the things that you mention @gusaus until we have a fair amount of surplus.

I agree with this, my suggestion would be focus on hosting fees for the moment. I would like to see us host a demo site that gets wiped periodically and allows potential users to test LibreTime out. I am happy to spend time working on the mechanics of how that happens, but I'll probably only get a chance in a couple weeks (probably closer to in a month's time). DNS hosting fees will probably require much if not all of what we would receive from the Open Collective initially anyway, as I doubt we would see much money coming in, especially before 3.0.0 ships.

> If we wanted to replace Slack with the more open Zulipchat they would give us an unlimited messages and free hosting as an opensource project.

Ooh, Zulipchat looks cool! I definitely support moving off Slack to an open source alternative

> I personally am not against the idea but I don't necessarily see $ being an obstacle for the project right [now]

I think it isn't an obstacle at the moment, but I also don't want to try iron out an entire governance structure under the pressure of getting money in.

> I also don't know about how we would handle the idea that "Contributors can override any decision by the Administrators or Maintainers by means of a General Resolution. This involves creating a bug report against the CoC repo with the proposal. This proposal then goes through a period of review and discussion before being voted on by the Contributors."
>
> This would also create a situation where we are equating stake in terms of contributions which makes sense from a code perspective but end-users could also be stakeholders in terms of the larger goals of the project.

Good point. I included it to ensure that Admins or Maintainers could not unilaterally dictate what was happening with the project. I modelled it off the Debian way of doing things, but it does not quite match up to how a software project like us do things. I am not sure how we ensure this works for us, or even if it is necessary... Perhaps if we do setup an Open Collective, certain tiers of contribution include voting rights in the project? Essentially users can contribute code or money and have a right to influence the direction of the project.

> I also am curious about Loomio.org

I am reluctant to add yet another platform to what we use at the moment. I think GitHub issues could work - use reactions for voting: :+1: or :-1: with comments to discuss and tags to denote active, decided, etc. I don't think it would work if our community grows drastically, but it should work for the moment. Also Loomio looks like GitHub issues with a little more flair...

> I guess my biggest hesitation in terms of creating an open collective is that it will just be a distraction from the goals of the project because there won't be sufficient funds for it to be worthwhile

Well if it does not make money, then there is not much maintenance required to manage it. If it does make money, that can be used to further the goals. I definitely think our main focus should be on getting 3.0.0 out the door

> I'm ok with the idea of starting an open collective but I would like there to be a consensus from the current participating maintainers that this is what we want to do. I'd also like to know who is planning on participating in the organization building and decision making process. 

I am happy to continue helping with this in whatever capacity needed.

**Comment by gusaus** [comment]
> I think that we explicitly don't want to pay contributor's for any of the things that you mention @gusaus until we have a fair amount of surplus.

Assuming you're referencing budgeting for project management, community, outreach, marketing, or fundraising? I was specifically mentioning those tasks/roles as, to @alannallama's point, they are usually uncontroversial (you're budgeting x amt of time as opposed to meeting a certain set of criteria when delivering code) and are usually necessary for developing, maintaining and growing an OSS project. I'm not saying budget should be allocated to these roles first... but many projects, like LibreTime, consist of contributors who would rather/need to focus on development priorities and [milestones](https://github.com/LibreTime/libretime/milestone/9). 

Open Collective is actively developing tools and a support structure for projects like LibreTime. As a pretty active member of the Open Collective community, I should be able to help make connections that will enable LibreTime to grow.

**Comment by frecuencialibre** [comment]
wow just now seeing this entire thread. as another of the maintainers i'll report in, but just to voice my support for whatever y'all decide. awesome that folks are putting energy into libretime surviving. perhaps set some future date before which the @LibreTime/administrators should also chime in before moving forward with whatever has been decided?

i'll say here cuz i know @Robbt won't, that him paying off some of his student debt would be sweet. many of us are grateful for all the time he's put in.

...also, making @paddatrapper an admin would simplify stuff like moving projects under the umbrella. i remember repo creation permissions were tough to give to maintainers. this could be another question for @hairmare 

i didn't at all expect to have had to suddenly step back from libretime, but do plan on returning at some unknown time haha. i'd love to get time for a few more things under the umbrella:
- a Debian 10 docker install option, and 
- i have some pencil and paper sketches of phone-first, "next-gen" libretime UI, but gotta run now :)

take care everybody!

**Comment by paddatrapper** [comment]
Would it be useful to hold an IRC/Slack/Platform of choice meeting to work on this in real time? If so what platform? As much as I dislike it, I think Slack would probably be best as some people involved are already there

**Comment by gusaus** [comment]
> Would it be useful to hold an IRC/Slack/Platform of choice meeting to work on this in real time?

Assuming you're talking more about the decision making/governance model, I'd recommend having those discussions in [Open Collective Slack](https://slack.opencollective.com/) where we can converse/collaborate with members of Open Collective and other projects and communities working towards similar goals.  

The Slack is open for anyone who wants to join (even if you don't yet have a collective) and all the conversations are logged and easy to reference. 

If we're still having a discussion about the merits and personal motivations for having a collective, I'd recommend everybody read through this issue, the [related discourse thread](https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84/24), and either 👍 👎 https://github.com/LibreTime/libretime/issues/796#issue-430919271 and/or leave a follow-up comment.

**Comment by Robbt** [comment]
I think the purpose here is to have an internal conversation, ideally with more than a few people. My preference would be for at least 3 out of the 5 maintainers set up time to meet and discuss this and make meaningful plans. As of late @paddatrapper and myself have been the people with the time to participate in LibreTime development and we haven't heard from @hairmare, @ned-kelly or @frecuencialibre much. If we want to just move forward with open collective and create a random donation point that in theory people could give money to I'm ok with that but I'd rather wait until we have a real plan to push for donations and make the project sustainable rather than adopting a philosophy of join it and they will come. 

I'm going to be working on finishing up my paid LibreTime work for my station this month. So that is where my effort is going to be going for now.

**Comment by paddatrapper** [comment]
Yeah, I think an internal discussion first would be good. I think lets rest this for a bit and let @Robbt wrap up his paid work. Can pick it up again in early June.

**Comment by gusaus** [comment]
Has there been any input from other maintainers outside of the discussion here? It seems like there's been more folks filing [bugs](https://github.com/LibreTime/libretime/issues?q=is%3Aissue+is%3Aopen+label%3Abug), [feature requests](https://github.com/LibreTime/libretime/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-request) and [inquiring about integrations](https://discourse.libretime.org/t/question-about-user-api-uploading-from-wordpress-and-podcast-function/298). All of which could be furthered along with a budget. 

There's also been some recent developments in the [Open Collective / OSS fundraising space](https://medium.com/open-collective/on-github-sponsors-5450b63caf7d) and interest in [community based collaboration](https://twitter.com/gusaus/status/1136374964276195328). 

All of which should provide for additional sources for maintaining, sustaining, and growing the project. Even if LibreTime is not yet set up with a collective https://opencollective.com/pledges/new

It would be ideal to have LibreTime on Open Collective and more contributors directly involved with the collaborations we’re ramping up. Myself, @alanna, and many folks in the Open Collective community are ready to help!

**Comment by Robbt** [comment]
No other feedback that I'm aware of. It is June though, so perhaps we should arrange a meeting to discuss next steps here.

**Comment by paddatrapper** [comment]
I agree. How about a meeting on Slack on 25 June at 17:00 UTC? We would probably need to create a "meetings" channel in Slack for it. Anyone who is interested is welcome to join

**Comment by gusaus** [comment]
Based on the input here, the related thread in Discourse (summarized in https://github.com/LibreTime/libretime/issues/796#issuecomment-482310972), and individual conversations, I don't think there are any of the [5 maintainers](https://github.com/orgs/LibreTime/teams/maintainers) against having Open Collective as a tool to sustain.

Assuming the meeting would be about what @Robbt proposed in https://github.com/LibreTime/libretime/issues/796#issuecomment-487960502, I'm not sure
3 out of the 5 maintainers are interested/available to discuss and spend time refining what @paddatrapper drafted https://github.com/LibreTime/libretime/issues/796#issuecomment-483845707. 

We already have 3 from the [contributor team](https://github.com/orgs/LibreTime/teams/contributors/members) + the Open Collective team https://github.com/LibreTime/libretime/issues/796#issuecomment-483864766 able to drive this.

Most Slacks I'm part of have meetings within channels set up for a specific topic. Possibly we could create #sustain and direct anyone interested in participating or lurking there.

For reasons described in https://github.com/LibreTime/libretime/issues/796#issuecomment-487804862 and https://github.com/LibreTime/libretime/issues/796#issuecomment-500078416, I'm going to continue pushing forward these cross-project collaborations primarily in Open Collective Slack. 

If you take a look at whose hanging in the #communitymedia channel, there's already 2 LibreTime maintainers in a room with leads from some complimentary orgs and projects (https://github.com/opencollective/opencollective/issues/1864).

![Slack - OpenCollective 2019-06-08 15-28-27](https://user-images.githubusercontent.com/113996/59152878-121d7980-8a02-11e9-953b-86092db68867.png)

If one more LibreTime maintainer joins, we'd have 3 able to drive this forward in the open!

**Comment by Robbt** [comment]
I'm good with the idea of meeting on June 25th.

**Comment by frecuencialibre** [comment]
i haven't read this whole thread, and continue to be very busy, but would
like to be looped into a meeting. the 25th would be difficult as we'll be
traveling that day. perhaps any day between the 26th and 3rd?

**Comment by Robbt** [comment]
I'd be happy to delay the meeting, does the 26th work for you @paddatrapper or would another one of those days work better ? That weekend I will be busy with a community festival my station has a booth at.

**Comment by paddatrapper** [comment]
26th works for me

**Comment by Robbt** [comment]
Are we still on for meeting tomorrow Wed the 26th at 17:00 UTC on https://libretime.slack.com - I plan on being there it is 12:00PM EST - @frecuencialibre & @paddatrapper & @gusaus will any of you be able to make it ?

**Comment by paddatrapper** [comment]
I'll be there

**Comment by paddatrapper** [comment]
Can we move the meeting 30 minutes later (so 17:30 UTC)? Sorry, but I just go t told I need to work late tomorrow, so will only be available then. If not, it is fine, I'll just be late

**Comment by Robbt** [comment]
Yeah 30 minutes later is fine by me. Not sure who else can make it.

**Comment by gusaus** [comment]
Think I should be able to make it - 9:30 Portlandia time? What's the format? Just a Slack chat thing?

**Comment by paddatrapper** [comment]
> What's the format? Just a Slack chat thing?

Yup. I'll convert the log into minutes and add them to the wiki afterwards

**Comment by frecuencialibre** [comment]
confirmed. 12.30 mexico city time. do we have an agenda? how much time are
we thinking?

**Comment by paddatrapper** [comment]
> Do we have an agenda

I've written one [here](https://github.com/LibreTime/libretime/wiki/LibreTime-Open-Collective-Meeting---26-June-2019-17:00-UTC), please update as people see fit

> How much time are we thinking?

I would like to keep it under an hour, we can schedule a follow up meeting if necessary

**Comment by ryanrain** [comment]
hey all, my apologies for not making it. we were still on the road. glad you were able to make progress. hopefully some day soon my life will be less hectic. adelante!

**Comment by gusaus** [comment]
Guess we should be able to close this out?!?
https://opencollective.com/libretime

I'd like to suggest we rename #meetings to #sustain (channel in LibreTime Slack) and invite anyone who missed the meeting to chime into the threads? 

We could then continue to use the #sustain channel to discuss Open Collective and other platforms/partnerships/etc. that would help us sustain and grow LibreTime.

That would also free up #general to focus on onboarding and collaborating with contributors. Focusing on hitting development milestones and keeping money and other biz discussions on the side.

I think I have the powers to make the name change if that seems like a good idea.

**Comment by paddatrapper** [comment]
I have changed the name, and can close this :tada:

**Comment by hairmare** [comment]
Thanks for all of your initiative on this. I really hope that the opencollective thingy spearheaded by @gusaus helps the project become sustainable in it's own right!

I'm currently preparing the release notes for 3.0.0-alpha.8 and would like to mention the open collective in them. Has anyone prepared a writeup I can just copy paste into the readme? Some kind of mission statement or teaser of sorts? If not I'll try to come up with something on my own.

I expect the release to be ready soonish and will open a thread on the GitHub Maintainers discussion once I feel that I have enough testing and writing of release notes for the release to make sense.

**Comment by paddatrapper** [comment]
It has been on my to do list, but I haven't had a chance to rustle something up yet. I am currently travelling, but will be able to work on it in about 2 days time

**Comment by gusaus** [comment]
@hairmare Creating the collective was the easy part! 

I'm not sure providing an overview of Open Collective the release notes is really necessary (if that's what you mean). We could link out to Open Collective but probably would want to hold off until we can provide a bit more info regarding how we're using. [Open Broadcaster Studio](https://obsproject.com/) provides some really good examples to follow - 
- https://github.com/obsproject/obs-studio/releases/tag/23.0.1 
- https://opencollective.com/obsproject/updates/obs-studio-23-0-2-hotfix-released
- https://obsproject.com/blog/new-ways-to-support-obs-development

Also keep in mind Open Collective is OSS. If/when we're at a point to do so, we could
even [integrate Open Collective into the README](https://docs.opencollective.com/help/developers/readme-integration
).

With this task complete, maybe we should follow up in [#sustain](https://libretime.slack.com/messages/CKKFA9YN7) and possibly subsequent issues in this github (maybe we could create a 'sustain' label).

**Comment by hairmare** [comment]
I was thinking of adding one sentence & a link to somewhere Open Collective to the start of the release notes (where the discourse link is, similar to what obs-studio has in the 23.0.1 release notes). I'll wait until things are more concrete with doing so.

I also created a sustain label here on GitHub.

**Comment by kaya-karaca** [comment]
Hello, unfortunately only credit card is an available option to donate via Open Collective. Is there any possibility to add Paypal as a payment method?

**Comment by paddatrapper** [comment]
Unfortunately we don't control the payment options on Open Collective...

**Comment by alanna** [comment]
@kaya-karaca For one-off payments, you can contribute credit card, via bank transfer, paypal, or bitcoin. If you go through the checkout process you should see these options (except bitcoin - let me know if you want to do that and I can work with LibreTime to get it set up).

Unfortunately Paypal doesn't allow us to do recurring payments so you can't use it for giving $10/month or something like that. So I suggest you give the amount you'd pay over the course of a year as a one-time contribution if you need to use Paypal.
