### ISSUE TITLE
PostgreSQL : Newb instructions

### ISSUE THREAD

**Issue by PlayBoxTech** [LibreTime/libretime#830]
A little history of me, before trying to work with LibreTime, and its predecessor the extent of my knowledge about PostgreSQL is that I knew it exists. Having been part of the web hosting industry for many years, my experience with MySQL/Maria DB is significantly more. 

It would likely help with the growth of this project if : 
A) switched to MySQL
B) had documentation in the install docs on commands to run to create the database using PostgreSQL
C) had the install app make the database and then skip that section of the web based install

**Comment by Robbt** [comment]
Ok, I suspect that you are thinking that MySQL might work to allow LibreTime to run in say a shared hosting environment that provides a shell account on Linux with Apache Mysql and PHP supported ?This isn't really feasible as LibreTime is a lot more than a website. It basically requires root access to install and the installation will automatically create the PostgreSQL database and a bunch of services.

So while I'm sure things could be modified to support MySQL I don't think it would really provide any distinct advantage. We are currently also using PropelORM for a lot of the database stuff. And I'm not sure what the benefit would be other than people are more familiar with MySQL. If you wanted to play around with this and were able to demonstrate how it could be modified to work with MySQL then feel free to do it but I think that there are a lot of instances where the software is coded specifically to work with PostgreSQL so it'd probably be a lot of work to port it over and would require a lot of coding and I'm not sure what the end benefit would be to users or developers. Replacing PropelORM is probably a better use of time but this would also involve a lot of rewrites etc and perhaps could be done in a database agnostic way so people could use MySQL or PostgreSQL.

B. & C. - I'm not sure what the purpose of installing the database without the web section of the install would be. Can you please explain your reasoning here. It should be possible to find the various SQL database definitions but they are actually produced automatically by propel-gen vs. hand-crafted, so it isn't useful to modify them.

**Comment by PlayBoxTech** [comment]
I have no doubt that this can't work in on a shared server, however I suspect many people are more familiar with MySQL. 

However putting that aside, at minimum the install directions need to include the PostgreSQL commands needed to give. 

When I first allowed the system to do what I thought was all the work, the web interface wouldn't take it because I wasn't in UTF8, for some reason it was in Latin1.

**Comment by Robbt** [comment]
It should be possible to dissect the install script to find the SQL commands. I am just not staring at the code right now.

**Comment by PlayBoxTech** [comment]
As far as my comments about B: As I said most people probably aren't very familiar with PostgreSQL, and expecting them to become experts to use this product, or limiting this product only to people who know PostgreSQL well seems rather limiting on the entire scope of who will use this product. Besides why not tell people the commands to use? such as psql create database, etc. etc.

C: why not have the script that install PostgreSQL also ask what you want the user name / password / database name be for LibreTime and then call the PHP script that actually makes them with those options? This has the side benefit of making sure the database is in UTF8 instead of Latin1 which was my first experience.

**Comment by PlayBoxTech** [comment]
My suggestion for updating the manual: 

createuser --interactive --pwprompt

create database "<< db name >>" with owner "<< db user >>" encoding "UTF8" lc_collate = 'en_US.UTF-8' lc_ctype='en_US.UTF-8' template= template0;

grant all privileges on database <<db name>> to << db user >>

**Comment by Robbt** [comment]
Generally this should be unnecessary. Although certain distros have issues with the database format. Can you share what particular distro of Linux you installed on ?

**Comment by PlayBoxTech** [comment]
Ubuntu 16.04, I have wounded up switching to another product which worked on the first install.

**Comment by hairmare** [comment]
Hey @PlayBoxTech 

Thanks for your input!

> A) switched to MySQL

As Robb elaborated a rewrite to MySQL would be non-trivial and is currently out of scope. I understand that PostgreSQL can be daunting for folks coming from a background in other relational database technologies like MySQL. If you have any recommendations on some reading to help people with such a background please share them and we'll be happy to add them to the documentation. 

> B) had documentation in the install docs on commands to run to create the database using PostgreSQL

We currently have a [section on PostgreSQL](http://libretime.org/manual/preparing-the-server/#postgresql) that tries to point to the upstream resources needed to get you started. If you run LibreTime in production we expect that you will need to familiarize yourself with some aspects of the underlying technology LibreTime uses. The database as well as the storage are the areas we see this as most important due to them being relevant for disaster recovery scenarios.

> C) had the install app make the database and then skip that section of the web based install

For simple test-drive installations there is this code in the installer:

https://github.com/LibreTime/libretime/blob/977b5c002c1ed457b9a6b08c007f07c32b3961ae/install#L1039-L1055

It would certainly be nice to have this set up a "secure by default" database allowing us to skip the web prompt. Currently the web prompt is also used when configuring LibreTime to use a remote database. In an ideal scenario the installer should generate a secure password and also pre-populate the web prompt with that password.

We would certainly welcome any contributions to make this more user friendly.

> I have wounded up switching to another product which worked on the first install.

I guess I'm going to close this issue then. Feel free to reopen if you decide to give LibreTime another go and need further assistance.
