### ISSUE TITLE
Radio.net metadata integration

### ISSUE THREAD

**Issue by togir2** [LibreTime/libretime#840]
Hi.
Libretime has the integration with the "TuneIn Air" api to publish song metadata. I would like to implement the same sort of metadata integration with the Radio.net "Metadata Api". 

I would duplicate the current tunein code so that it can work with radio.net. Maybe in next step these two Implementations than can be merged togeteher.

Are there any concerns? or are there specific reasons why there is no integration with radio.net?

**Comment by Robbt** [comment]
Thanks for your interest. As far as I know, the TuneIn code has not been tested. It is one of these integrations that may or may not work such as the SoundCloud integration. We are open to anyone contributing code that integrates with useful services though. If you want to add code for "radio.net" that could work. If you were interested in testing whether the TuneIn code is working that would be appreciated as well. I don't think any of the current developers have a TuneIn API key to test it.

**Comment by togir2** [comment]
The TuneIn code is working, we are using it for 4 months now and had no errors so far.

I am currently in contact with "radio.net" to get an accesskey for there api. As I get the key I will try to implement the code needed to push metadata to "radio.net".

**Comment by tiagojferreira-IFRS** [comment]
Hello! We are interested in integrating Libretime with online metadata bases like MusicBrainz Picard and the Spotify API itself. The focus is on ensuring the fidelity of the information, that is, correcting the metadata automatically to ensure payment of copyright to the actual composers.

Can anyone help!

Where can we start?

Thank you!

**Comment by Robbt** [comment]
Welcome @tiagojferreira-IFRS something like this could be useful, please feel free to document or link to these APIs so that they can be evaluated. Another item that has been on the radar is analyzing or audio fingerprinting multi-song tracks and compilations and then creating a report with the composite tracks. This could be aided by something like these APIs if they provided the appropriate information. In the past Airtime encouraged people to clean and correct the metadata before entering it into LibreTime. Our current metadata editing mechanism could use some improvements in that it doesn't write the changes back to the files & has no mechanism for editing multiple tracks at once.

**Comment by tiagojferreira-IFRS** [comment]
Great!

I imagine that metadata accuracy should be ensured once the media has been inserted into Libretime which would require serious or even official database integration like ISRC or Spotify. Integration with copyright collection systems makes more sense at the moment or after the works are played.

Doubt: From a code or architectural design point of view, do you have any tips on where to start?

I work at a Federal Institute of Education, Science and Technology in Brazil and the idea is to build a project to provoke technology scholarship students to help in this demand.

**Comment by Robbt** [comment]
@tiagojferreira-IFRS See #283 for a discussion related to this. Specifically a service called ARCCloud is mentioned. We would welcome any help in this regard and feel free to create a Wiki page if you want a shared note space to try to consolidate some of the information. I think there is a lot out there, from identifying the different reporting formats to services that can assist in identifying audio tracks etc.

**Comment by hairmare** [comment]
The api has a `notifyMediaItemStartPlayAction` action that handles tuein updates (amog other things):
https://github.com/LibreTime/libretime/blob/306954cbf1c3630b9198d798d1ca2e61778086d3/airtime_mvc/application/controllers/ApiController.php#L603-L653
This is part of the legacy API surface that has been partially replaced with a slightly more modern RESTful API.

Sending metadata to other services might be added somewhere in the action. We might also need to refactor this part a bit since adding more integrations to it might make it unwieldy. 

Also, the action currently only operates on files. It might also be interesting to look into also sending updates when playing back external streams or other sources. 

The Soundcloud integration (of which we are unsure if it actually works) also sends data to an external service. It's integration is done in the python parts (as a celery task), since it isn't as time sensitive. Maybe something that involves RabbitMQ and the python bits would be a good fit to fan out calls to external services in a way that won't block the main API/webapp.

**Comment by tiagojferreira-IFRS** [comment]
I had not really thought about the external input streams, in which case the complexity must be much greater.

As for media files I've been analyzing this Python code that analyzes and imports the media into Libretime:

https://github.com/LibreTime/libretime/blob/master/python_apps/airtime_analyzer/airtime_analyzer/analyzer_pipeline.py

**Comment by hairmare** [comment]
@tiagojferreira-IFRS The analyzer code is indeed where things link MusicBrainz or any other metadata enhancing/fixing code would end up.

I guess it makes sense to open a new issue to track ay feature-requests regarding this since it involves rather different code-paths than what @togir2 was after with radio.net api integration (publishing metadata from LibreTime vs. enhancing metadata quality at audio ingest and/or playout).

**Comment by numericalatina** [comment]
Yes, maybe it makes sense to think of an interface to which different services can be plugged-in.
Those services should be plug-ins, also meaning it should be possible to plug them off. IMHO
