### ISSUE TITLE
Selecting 'Hardware Audio Output' breaks streams

### ISSUE THREAD

**Issue by dabfree** [LibreTime/libretime#843]
Hi!

Selecting the Hardware Audio Output checkbox causes all streams to fall silent.

There is nothing that suggests this is correct behaviour. If there is a good reason then it should not be possible to select both. A couple of use cases for having both are 1: one wants to stream and still be able to extract audio without it going through a lossy codec. 2: Monitoring. 3: Feeding an outboard audio leveller/processor. 4. Sending PCM to an ALSA loopback device which can be used by another application (such as stereotool).

The fix is very simple on an installed system:

In /usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_script.liq

Change:

if output_sound_device then
success = ref false

to:

if output_sound_device then
success = ref true

And it is as simple as that! I fixed this while trying to find a suitable breakout for PCM to use with stereotool...I've not got that working as I would like yet but I'm happy that I have had a little win along the way as I can now tell ALSA to use loopback as default, and use that for the stereotool input because this machine is running a desktop I can use the stereotool gui. ;-) Ultimately I would like to bring that processed audio back in to use for the encoder (and run the headless stereotool) but this will do for now. I can't spot where that file is in the repo (and I don't really understand how it is generated yet) so I am not sending a pull request - hope that's ok. Beware - this will be broken if libretime is  updated.

Best regards,

Rash.

Tested on Ubuntu 18.04:

**Comment by hairmare** [comment]
Hey @dabfree 

The code you mention seems to be here:

https://github.com/LibreTime/libretime/blob/9b9832ee4e95833a657549d7e3999651f4eec7ee/python_apps/pypo/liquidsoap/ls_script.liq#L345-L389

At a glance it looks like `success` is always set to true if the soundcard output can be selected. Defaulting it to true at the beginning might break what needs to happen if no output can be enabled due to liquidsoap not supporting it..

This might be version/installation specific. How did you install liquidsoap? Are you able to try this with a modern liquidsoap >=1.3.0? Install instructions for that are in #192.

I'm currently using a similar setup to yours. I send my output to a AoIP ALSA driver so I an then send it to a processor that is on the AoIP network. At the same time I have liquidsoap connected to an icecast server so I can listen into the signal before it reaches the audio-processor.

BTW, hooking up things like stereotool might be covered by the feature-request in #229.

**Comment by dabfree** [comment]
Ah, that's a good call...

I haven't moved away from liquidsoap 1.1.1 yet, but I am now more than a little bit interested in your AOIP ALSA driver. Is it open source?

**Comment by hairmare** [comment]
> I haven't moved away from liquidsoap 1.1.1 yet, but I am now more than a little bit interested in your AOIP ALSA driver. Is it open source?

Sadly, no... I'm currently using the [Axia IP Audio Driver for Linux](https://www.telosalliance.com/Axia/Axia-IP-Audio-Driver). 

Given that AES67 has been gaining some popularity and traction I expect an OSS version to get developed at some point.  Currently we are looking into [the driver from Merging](https://www.merging.com/products/alsa_ravenna_aes67_driver) which is somewhat open and [mai](https://github.com/markmcconnell/mai) which is somewhat unsupported.

My guess is that it might still take a couple of years until everything is there, but it sure seems like AES67 is coming at some point.

BTW, there has been some discussion on using stereotool with liquidsoap in their issues lately. Have you seen https://github.com/savonet/liquidsoap/issues/885?

**Comment by dabfree** [comment]
Hi,

I had a hunch it was going to be livewire...

I agree with your projection and as it is an open standard, I much prefer
the idea of it. I'm not interested in realtime for this particular
application as that can bring with it a whole raft of other challenges and
requirements (MPLS switches, PTP and suchlike) if you expect it to work
reliably.

I also encountered the problem with the pipeline breaking mentioned in the
thread you linked to, so I have bitten the bullet and am pulling a 320k
stream from libretime with sox and solving the problem that way. I really
don't like to transcode so I will think about it some more, The (phase
linear) lowpass in stereotool appears to be better than the one in FDK so I
have disabled it in odr-audioenc with good results.


R.
