### ISSUE TITLE
Transfer to new VPS

### ISSUE THREAD

**Issue by hopfrogsalerno** [LibreTime/libretime#846]
Which files should I save to transfer the Radio to a new VPS without losing data and settings? Thank you

**Comment by hairmare** [comment]
You should migrate at least the contents of the PostgreSQL database, the `/srv/airtime` directory as well as (optionally, as needed) `/etc/airtime/airtime.conf`. Coincidentally these are the things that should be included in a proper [backup](https://libretime.org/manual/backing-up-the-server/) of a LibreTime instance.

You will also need to setup RabbitMQ using the same information on the new box as on the old one if you need to migrate `airtime.conf` (ie. if it includes settings not done from the setup web-ui).

I'm closing this issue since it is just a support question. Feel free to chat us op on [discourse](https://libretime.org/manual/backing-up-the-server/) or [Slack](https://discourse.libretime.org/t/slack-for-libretime/80) if you need further assistance as those are the venue where we preferably handle such support issues.
