### ISSUE TITLE
Program block show source not engaging properly?

### ISSUE THREAD

**Issue by delrizzo** [LibreTime/libretime#862]
**Describe the bug**
Hi Everyone,
I'm not sure this is a bug or not, we're still in the process of scouring logs to see what is happening. Essentially, this past week, about 80% of our live program hosts experienced the following issue. Just for information, each program has a custom user authentication configured, and the corresponding user config is stored in BUTT on a remote computer. Using BUTT v0.1.17.

1. User engages remote BUTT session at assigned time.
2. BUTT gives no negative feedback - seems to be working properly.
3. Libretime show source engages briefly, then disconnects within a few seconds of connection. Dead air is now being broadcast. User is generally unaware.
4. User realizes they are not broadcasting, stops BUTT, reengages broadcast, Libretime connects and broadcast begins.

So far, we have not found any indication in any of the logs that we are looking at (system.log, local BUTT logs, etc...) that there is any issue, other than witnessing Libretime stopping the DJ play at shortly after the connection time, and then it restarts when the DJ finally realized and restarted the stream.

This is an odd problem because last week (our first week under Libretime) not one user experienced this issue. I'm not sure that this is relevant to the problem, but each time the user has experienced this issue, i have logged into the Libretime calendar and refreshed the program - either by re-entering the custom connect password, or simply re-saving the program configuration. This may be a red herring.

At this time, we cannot rule out a HW issue with our console (which is a USB board) however, we feel this is an unlikely cause because it eventually works.

Has anyone else experienced this issue at all?

**Expected behavior**
Under Airtime, and in our first week of Libretime, we expect (and experienced) the program host to connect at the appropriate time via BUTT, and that the broadcast continues as per normal.

**LibreTime version:**
977b5c002

**Installation method:**
 - OS: Ubuntu 18.04.2 LTS      
 - OS Version bionic
 - Method: install script (git download)

**Client (please complete the following information if applicable):**
 - OS: Ubuntu
 - Browser chrome
 - Version ?

**Comment by Robbt** [comment]
I suspect that you may have found a bug. We would need to confirm it, but it is possible that LibreTime will do something to refresh the logins after you edit a program since you can modify the people who can login and that information gets interfaced somehow with liquidsoap. It should be easy enough to verify whether this happens or not.

Butt leaves a lot to be desired as well, even though it is by far the best free software streaming interface it has a number of odd behaviors and a somewhat complex UI.

**Comment by delrizzo** [comment]
Absolutely agree with you... but that notwithstanding, it is a bit
concerning that Libretime would have this behaviour. I'm kind of surprised
that no one else has discovered this yet... unless we're using this
differently than most, but I would suspect not.
We use the custom auth instead of master password to prevent erroneous
stream connections...

Cheers,
d
--
Dave Del Rizzo

**Comment by Robbt** [comment]
Ahh, this totally makes sense, if you are using custom auth, I suspect that this feature isn't widely used compared to DJ based logins. And if you edit the show itself then it will need to send the custom auth in case it changed and thus it would disconnect people. Maybe this doesn't happen if the show and user login is used but only custom auth. I haven't had a chance to test it yet.

**Comment by delrizzo** [comment]
Ok, that makes sense.
It worked in Airtime with no issues, so that suggests something fundamental has changed wrt to this functionality?

**Comment by hairmare** [comment]
I only know of one change to how liquidsoap interact with the auth parts in the PHP bits and it is part of the patch for #192 (liquidsoap 1.3.x support).

Can you share some liquidsoap  (and pypo) logs to help debug this? There might be some more info in there that help us arrow this down.

I can certainly confirm that custom_auth has most likely seen less usage ad testing in LibreTime so far. At least I haven't tested it and I would have expected issues like this (as well as useability issues) to have been reported earlier. 

Can you reproduce it on a liquidsoap 1.3 install as well? Overall I feel like the stability of liquidsoap did improve a bit in the bump and you issue might be fixed by a bump.

**Comment by delrizzo** [comment]
Hi sorry just saw this now. I will investigate further tonight and try to provide some logs.  Thanks!

**Comment by delrizzo** [comment]
We are using Liquidsoap 1.1.1. I will endeavour to upgrade soon, and report back here with any news on this. Sorry for taking so long!

**Comment by numericalatina** [comment]
We also have experienced this behaviour, but we have noticed this happens when we have network issues like poor connections.

Note that we are also using custom authentication regularly with no trouble at all.

**Comment by delrizzo** [comment]
Interesting! 
Our studio is connected to our libretime server with a hard line in the next room. So unfortunately network issues are not likely to be the problem for us. But that is certainly good information. 
d
