### ISSUE TITLE
Problem rabbitmq-server?

### ISSUE THREAD

**Issue by hopfrogsalerno** [LibreTime/libretime#991]
The Radio (on Ubuntu 18.04) stops often and then resumes - without any intervention - to transmit. I saw this error: can it depend on this? If YES, how can I correct?
thanks
root@vmi304213:~# invoke-rc.d rabbitmq-server status
● rabbitmq-server.service - RabbitMQ Messaging Server
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor 
   Active: active (running) since Fri 2020-03-27 19:57:46 CET; 2 days ago
  Process: 470 ExecStartPost=/usr/lib/rabbitmq/bin/rabbitmq-server-wait (code=ex
 Main PID: 468 (rabbitmq-server)
    Tasks: 92 (limit: 4915)
   CGroup: /system.slice/rabbitmq-server.service
           ├─ 468 /bin/sh /usr/sbin/rabbitmq-server
           ├─ 484 /bin/sh /usr/lib/rabbitmq/bin/rabbitmq-server
           ├─ 703 /usr/lib/erlang/erts-9.2/bin/epmd -daemon
           ├─ 854 /usr/lib/erlang/erts-9.2/bin/beam.smp -W w -A 64 -P 1048576 -t
           ├─ 980 erl_child_setup 65536
           ├─1232 inet_gethost 4
           └─1233 inet_gethost 4

Mar 27 19:57:35 vmi304213.contaboserver.net systemd[1]: Starting RabbitMQ Messag
Mar 27 19:57:39 vmi304213.contaboserver.net rabbitmq[470]: Waiting for rabbit@vm
Mar 27 19:57:39 vmi304213.contaboserver.net rabbitmq[470]: pid is 484
Mar 27 19:57:46 vmi304213.contaboserver.net systemd[1]: Started RabbitMQ Messagi
Mar 27 21:14:09 vmi304213.contaboserver.net epmd[703]: epmd: got partial packet 
Mar 28 21:16:00 vmi304213.contaboserver.net epmd[703]: epmd: got partial packet 
Mar 29 16:53:29 vmi304213.contaboserver.net epmd[703]: epmd: invalid packet size
Mar 30 10:58:11 vmi304213.contaboserver.net epmd[703]: epmd: got partial packet 
lines 1-23

**Comment by Robbt** [comment]
Hey we need more information to troubleshoot this. By stops and then resumes are you talking about Icecast or the songs playing cut out ? I'd look into some of the other logs such as pypo.log in /var/log/airtime and see if there are any other clues there. 

Rabbit MQ is used to convey messages between the different services but we'd need to know more about how the radio was failing to determine if this was an issue. I'm going to close this for now because it is a support request and we haven't found a specific bug yet, but feel free to converse about it, sorry I haven't been scouring the issue queue lately and just stumbled upon this.
